import { relations, sql } from 'drizzle-orm';
import { index, integer, real, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

/**
 * Conventions used throughout this schema:
 *
 * - Ids are UUIDs generated by the application, not autoincrementing integers. An
 *   order reference that can be guessed by adding one to the last one is a way to
 *   read somebody else's receipt.
 * - Timestamps are ISO-8601 strings in UTC. They sort lexicographically, which is
 *   the only property the queries here need, and they survive a database dump
 *   into any other engine without a timezone argument.
 * - Money is an integer count of cents (see `@fotg/contracts`'s `money.ts`). There
 *   is no REAL column anywhere near a price.
 */

const id = () => text('id').primaryKey();
const createdAt = () =>
  text('created_at')
    .notNull()
    .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`);

export const users = sqliteTable(
  'users',
  {
    id: id(),
    email: text('email').notNull(),
    passwordHash: text('password_hash').notNull(),
    fullName: text('full_name').notNull(),
    phone: text('phone'),
    role: text('role').notNull().default('customer'),
    createdAt: createdAt(),
    updatedAt: createdAt(),
  },
  (table) => [uniqueIndex('users_email_unique').on(table.email)],
);

export const restaurants = sqliteTable(
  'restaurants',
  {
    id: id(),
    ownerId: text('owner_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    description: text('description'),
    cuisine: text('cuisine').notNull(),
    phone: text('phone'),
    addressLine1: text('address_line1').notNull(),
    city: text('city').notNull(),
    region: text('region').notNull(),
    postalCode: text('postal_code').notNull(),
    latitude: real('latitude'),
    longitude: real('longitude'),
    deliveryFeeCents: integer('delivery_fee_cents').notNull().default(299),
    minimumOrderCents: integer('minimum_order_cents').notNull().default(0),
    prepTimeMinutes: integer('prep_time_minutes').notNull().default(25),
    imageUrl: text('image_url'),
    isActive: integer('is_active', { mode: 'boolean' }).notNull().default(true),
    /**
     * Ratings are kept as a running sum and count rather than an average, so a new
     * review is one addition instead of a re-read of every review ever left, and
     * the average is never stored at a precision it does not have.
     */
    ratingSum: integer('rating_sum').notNull().default(0),
    ratingCount: integer('rating_count').notNull().default(0),
    createdAt: createdAt(),
    updatedAt: createdAt(),
  },
  (table) => [
    index('restaurants_owner_idx').on(table.ownerId),
    index('restaurants_cuisine_idx').on(table.cuisine),
    index('restaurants_active_idx').on(table.isActive),
  ],
);

export const openingHours = sqliteTable(
  'opening_hours',
  {
    id: id(),
    restaurantId: text('restaurant_id')
      .notNull()
      .references(() => restaurants.id, { onDelete: 'cascade' }),
    /** 0 = Sunday, matching `Date.prototype.getDay`. */
    weekday: integer('weekday').notNull(),
    opensMinute: integer('opens_minute').notNull(),
    closesMinute: integer('closes_minute').notNull(),
  },
  (table) => [index('opening_hours_restaurant_idx').on(table.restaurantId)],
);

export const menuCategories = sqliteTable(
  'menu_categories',
  {
    id: id(),
    restaurantId: text('restaurant_id')
      .notNull()
      .references(() => restaurants.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    description: text('description'),
    sortOrder: integer('sort_order').notNull().default(0),
    createdAt: createdAt(),
  },
  (table) => [index('menu_categories_restaurant_idx').on(table.restaurantId)],
);

export const menuItems = sqliteTable(
  'menu_items',
  {
    id: id(),
    restaurantId: text('restaurant_id')
      .notNull()
      .references(() => restaurants.id, { onDelete: 'cascade' }),
    categoryId: text('category_id')
      .notNull()
      .references(() => menuCategories.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    description: text('description'),
    priceCents: integer('price_cents').notNull(),
    imageUrl: text('image_url'),
    /** A JSON array of dietary tags; SQLite has no array type and the set is small. */
    dietaryTags: text('dietary_tags').notNull().default('[]'),
    isAvailable: integer('is_available', { mode: 'boolean' }).notNull().default(true),
    sortOrder: integer('sort_order').notNull().default(0),
    createdAt: createdAt(),
    updatedAt: createdAt(),
  },
  (table) => [
    index('menu_items_restaurant_idx').on(table.restaurantId),
    index('menu_items_category_idx').on(table.categoryId),
  ],
);

export const carts = sqliteTable(
  'carts',
  {
    id: id(),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    /**
     * A cart belongs to at most one restaurant at a time. Mixing two kitchens into
     * one delivery is not a thing this platform can do, so the constraint lives in
     * the data rather than being re-checked at every call site.
     */
    restaurantId: text('restaurant_id').references(() => restaurants.id, { onDelete: 'set null' }),
    createdAt: createdAt(),
    updatedAt: createdAt(),
  },
  (table) => [uniqueIndex('carts_user_unique').on(table.userId)],
);

export const cartItems = sqliteTable(
  'cart_items',
  {
    id: id(),
    cartId: text('cart_id')
      .notNull()
      .references(() => carts.id, { onDelete: 'cascade' }),
    menuItemId: text('menu_item_id')
      .notNull()
      .references(() => menuItems.id, { onDelete: 'cascade' }),
    quantity: integer('quantity').notNull(),
    notes: text('notes'),
    createdAt: createdAt(),
  },
  (table) => [index('cart_items_cart_idx').on(table.cartId)],
);

export const orders = sqliteTable(
  'orders',
  {
    id: id(),
    /** Short, human-quotable, and random — what a customer reads out on the phone. */
    reference: text('reference').notNull(),
    customerId: text('customer_id')
      .notNull()
      .references(() => users.id, { onDelete: 'restrict' }),
    restaurantId: text('restaurant_id')
      .notNull()
      .references(() => restaurants.id, { onDelete: 'restrict' }),
    courierId: text('courier_id').references(() => users.id, { onDelete: 'set null' }),
    status: text('status').notNull().default('pending'),

    subtotalCents: integer('subtotal_cents').notNull(),
    deliveryFeeCents: integer('delivery_fee_cents').notNull(),
    serviceFeeCents: integer('service_fee_cents').notNull(),
    taxCents: integer('tax_cents').notNull(),
    tipCents: integer('tip_cents').notNull().default(0),
    totalCents: integer('total_cents').notNull(),

    addressLabel: text('address_label').notNull(),
    addressLine1: text('address_line1').notNull(),
    addressLine2: text('address_line2'),
    addressCity: text('address_city').notNull(),
    addressRegion: text('address_region').notNull(),
    addressPostalCode: text('address_postal_code').notNull(),
    addressLatitude: real('address_latitude'),
    addressLongitude: real('address_longitude'),
    deliveryNotes: text('delivery_notes'),

    customerNotes: text('customer_notes'),
    estimatedReadyAt: text('estimated_ready_at'),
    placedAt: createdAt(),
    updatedAt: createdAt(),
  },
  (table) => [
    uniqueIndex('orders_reference_unique').on(table.reference),
    index('orders_customer_idx').on(table.customerId),
    index('orders_restaurant_idx').on(table.restaurantId),
    index('orders_courier_idx').on(table.courierId),
    index('orders_status_idx').on(table.status),
  ],
);

export const orderItems = sqliteTable(
  'order_items',
  {
    id: id(),
    orderId: text('order_id')
      .notNull()
      .references(() => orders.id, { onDelete: 'cascade' }),
    /**
     * Nullable, and the name and price beside it are copies rather than joins. A
     * receipt has to keep saying what was bought and what it cost even after the
     * restaurant renames the dish or takes it off the menu entirely.
     */
    menuItemId: text('menu_item_id').references(() => menuItems.id, { onDelete: 'set null' }),
    name: text('name').notNull(),
    unitPriceCents: integer('unit_price_cents').notNull(),
    quantity: integer('quantity').notNull(),
    notes: text('notes'),
    lineTotalCents: integer('line_total_cents').notNull(),
  },
  (table) => [index('order_items_order_idx').on(table.orderId)],
);

export const orderEvents = sqliteTable(
  'order_events',
  {
    id: id(),
    orderId: text('order_id')
      .notNull()
      .references(() => orders.id, { onDelete: 'cascade' }),
    status: text('status').notNull(),
    actor: text('actor').notNull(),
    actorUserId: text('actor_user_id').references(() => users.id, { onDelete: 'set null' }),
    reason: text('reason'),
    createdAt: createdAt(),
  },
  (table) => [index('order_events_order_idx').on(table.orderId)],
);

export const reviews = sqliteTable(
  'reviews',
  {
    id: id(),
    /** One review per order, which is what stops a rating being padded by repetition. */
    orderId: text('order_id')
      .notNull()
      .references(() => orders.id, { onDelete: 'cascade' }),
    restaurantId: text('restaurant_id')
      .notNull()
      .references(() => restaurants.id, { onDelete: 'cascade' }),
    customerId: text('customer_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    rating: integer('rating').notNull(),
    comment: text('comment'),
    createdAt: createdAt(),
  },
  (table) => [
    uniqueIndex('reviews_order_unique').on(table.orderId),
    index('reviews_restaurant_idx').on(table.restaurantId),
  ],
);

export const usersRelations = relations(users, ({ many, one }) => ({
  restaurants: many(restaurants),
  orders: many(orders),
  cart: one(carts),
}));

export const restaurantsRelations = relations(restaurants, ({ many, one }) => ({
  owner: one(users, { fields: [restaurants.ownerId], references: [users.id] }),
  openingHours: many(openingHours),
  categories: many(menuCategories),
  items: many(menuItems),
  orders: many(orders),
}));

export const menuCategoriesRelations = relations(menuCategories, ({ many, one }) => ({
  restaurant: one(restaurants, {
    fields: [menuCategories.restaurantId],
    references: [restaurants.id],
  }),
  items: many(menuItems),
}));

export const menuItemsRelations = relations(menuItems, ({ one }) => ({
  restaurant: one(restaurants, { fields: [menuItems.restaurantId], references: [restaurants.id] }),
  category: one(menuCategories, {
    fields: [menuItems.categoryId],
    references: [menuCategories.id],
  }),
}));

export const cartsRelations = relations(carts, ({ many, one }) => ({
  user: one(users, { fields: [carts.userId], references: [users.id] }),
  restaurant: one(restaurants, { fields: [carts.restaurantId], references: [restaurants.id] }),
  items: many(cartItems),
}));

export const cartItemsRelations = relations(cartItems, ({ one }) => ({
  cart: one(carts, { fields: [cartItems.cartId], references: [carts.id] }),
  menuItem: one(menuItems, { fields: [cartItems.menuItemId], references: [menuItems.id] }),
}));

export const ordersRelations = relations(orders, ({ many, one }) => ({
  customer: one(users, { fields: [orders.customerId], references: [users.id] }),
  restaurant: one(restaurants, { fields: [orders.restaurantId], references: [restaurants.id] }),
  items: many(orderItems),
  events: many(orderEvents),
}));

export const orderItemsRelations = relations(orderItems, ({ one }) => ({
  order: one(orders, { fields: [orderItems.orderId], references: [orders.id] }),
}));

export const orderEventsRelations = relations(orderEvents, ({ one }) => ({
  order: one(orders, { fields: [orderEvents.orderId], references: [orders.id] }),
}));
