import { useState } from 'react'
import { Link } from 'react-router-dom'
import { t } from '../../i18n/strings'
import { Card, Drawer, EmptyState, ErrorState, Field, Icon, Skeleton, Tabs, ToastLine, useToastMessage } from '../../dashboard/components/ui'
import { useAdmin } from '../AdminContext'
import { Badge, DevNote } from '../components/DataTable'
import type { Announcement } from '../types'
import { StatusPill, fmtDateTime, KNOWN_MARKET_CODES, useLoad, usePageTitle } from './shared'

type Tab = 'alerts' | 'announcements' | 'templates' | 'delivery'
const blank = (): Omit<Announcement, 'id' | 'createdAt'> & { id?: string } => ({ title: '', audience: 'customers', markets: [], channel: 'push', status: 'DRAFT', scheduledAt: null })

/** Notifications (Module 18): critical alerts, announcements (drafts / schedules), template readiness, delivery status readiness. */
export default function NotificationsPage() {
  const a = useAdmin(); const locale = a.locale; usePageTitle('adm.nav.notifications')
  const [tab, setTab] = useState<Tab>('alerts'); const [form, setForm] = useState<ReturnType<typeof blank> | null>(null); const [busy, setBusy] = useState(false); const [err, setErr] = useState<string | null>(null); const { msg, toast } = useToastMessage()
  const ann = useLoad(() => a.repos.notifications.announcements(), [a.repos]); const tpl = useLoad(() => a.repos.notifications.templates(), [a.repos])
  const canManage = a.can('notifications.manage')
  const save = async () => { if (!form) return; setBusy(true); setErr(null); try { await a.repos.notifications.saveAnnouncement(form, a.admin.id); setForm(null); await ann.refresh(); toast(t('adm.saved', undefined, locale)) } catch (e) { setErr((e as Error).message) } finally { setBusy(false) } }
  return (
    <div className="db-page" data-testid="adm-notifications">
      <div className="db-page__head"><div><h1 className="db-page__title">{t('adm.notifications.title', undefined, locale)}</h1><p className="db-page__lead">{t('adm.notifications.lead', undefined, locale)}</p></div>{canManage && tab === 'announcements' && <div className="db-page__actions"><button type="button" className="db-btn db-btn--primary" onClick={() => setForm(blank())} data-testid="ann-new">{t('adm.notifications.new', undefined, locale)}</button></div>}</div>
      <Tabs tabs={(['alerts', 'announcements', 'templates', 'delivery'] as Tab[]).map((id) => ({ id, label: t(`adm.notifications.tab.${id}`, undefined, locale), count: id === 'alerts' ? a.unreadCount : undefined }))} value={tab} onChange={setTab} label={t('adm.notifications.tabs', undefined, locale)} />
      {tab === 'alerts' && <Card actions={a.unreadCount > 0 ? <button type="button" className="db-btn db-btn--outline db-btn--sm" onClick={() => { void a.markAllRead() }}>{t('dash.notifications.markAll', undefined, locale)}</button> : undefined}>
        {a.alerts.length === 0 ? <EmptyState icon="notifications" title={t('adm.notifications.alertsEmpty', undefined, locale)} /> : <ul className="adm-activity" data-testid="alerts-list">{a.alerts.map((n) => <li key={n.id} style={{ opacity: n.read ? 0.7 : 1 }}><span className={`adm-activity__icon adm-activity__icon--${n.type}`}><Icon name={n.severity === 'critical' ? 'warning' : 'notifications'} size={16} /></span><span><b>{n.title} {!n.read && <Badge tone={n.severity === 'critical' ? 'red' : n.severity === 'warning' ? 'amber' : 'blue'}>{n.severity}</Badge>}</b><small>{n.body}</small>{n.link && <Link to={n.link} className="db-link" onClick={() => { void a.markRead(n.id) }}>{t('adm.table.details', undefined, locale)} →</Link>}</span><time dateTime={n.at}>{fmtDateTime(n.at, locale)}</time></li>)}</ul>}
      </Card>}
      {tab === 'announcements' && <Card>
        {ann.state === 'loading' && <Skeleton rows={4} />}{ann.state === 'error' && <ErrorState title={t('adm.error.loadTitle', undefined, locale)} onRetry={() => { void ann.reload() }} locale={locale} />}
        {ann.state === 'ready' && (ann.data?.length ? <div className="db-table-wrap" tabIndex={0}><table className="db-table" data-testid="announcements-table"><caption className="db-sr-only">{t('adm.notifications.tab.announcements', undefined, locale)}</caption><thead><tr><th scope="col">{t('adm.notifications.col.title', undefined, locale)}</th><th scope="col">{t('adm.notifications.col.audience', undefined, locale)}</th><th scope="col">{t('adm.notifications.col.markets', undefined, locale)}</th><th scope="col">{t('adm.notifications.col.channel', undefined, locale)}</th><th scope="col">{t('adm.notifications.col.status', undefined, locale)}</th><th scope="col">{t('adm.notifications.col.scheduled', undefined, locale)}</th>{canManage && <th scope="col" className="adm-td--end">{t('adm.table.actions', undefined, locale)}</th>}</tr></thead>
          <tbody>{ann.data.map((x) => <tr key={x.id}><td className="adm-td--primary" dir="auto">{x.title}</td><td>{t(`adm.notifications.audience.${x.audience}`, undefined, locale)}</td><td>{x.markets.length ? x.markets.join(', ') : t('adm.notifications.allMarkets', undefined, locale)}</td><td>{t(`adm.notifications.channel.${x.channel}`, undefined, locale)}</td><td><StatusPill status={x.status} prefix="adm.notifications.annStatus" dot /></td><td>{fmtDateTime(x.scheduledAt, locale)}</td>{canManage && <td className="adm-td--end">{x.status !== 'SENT' && <button type="button" className="db-btn db-btn--outline db-btn--sm" onClick={() => setForm({ ...x })}>{t('adm.action.edit', undefined, locale)}</button>}</td>}</tr>)}</tbody></table></div> : <EmptyState title={t('adm.alerts.empty', undefined, locale)} />)}
        <DevNote>{t('adm.notifications.sendNote', undefined, locale)}</DevNote>
      </Card>}
      {tab === 'templates' && <Card>{tpl.state !== 'ready' ? <Skeleton rows={4} /> : <div className="db-table-wrap" tabIndex={0}><table className="db-table" data-testid="templates-table"><caption className="db-sr-only">{t('adm.notifications.tab.templates', undefined, locale)}</caption><thead><tr><th scope="col">{t('adm.notifications.tplCol.key', undefined, locale)}</th><th scope="col">{t('adm.notifications.tplCol.channel', undefined, locale)}</th><th scope="col">{t('adm.notifications.tplCol.audience', undefined, locale)}</th><th scope="col">{t('adm.notifications.tplCol.locales', undefined, locale)}</th><th scope="col">{t('adm.notifications.tplCol.status', undefined, locale)}</th></tr></thead><tbody>{(tpl.data ?? []).map((x) => <tr key={x.id}><td><span className="adm-code">{x.key}</span></td><td>{t(`adm.notifications.channel.${x.channel}`, undefined, locale)}</td><td>{x.audience}</td><td>{x.locales.join(', ')}</td><td><StatusPill status={x.status} prefix="adm.notifications.annStatus" /></td></tr>)}</tbody></table></div>}</Card>}
      {tab === 'delivery' && <Card><EmptyState icon="notifications" title={t('adm.notifications.tab.delivery', undefined, locale)} text={t('adm.notifications.deliveryNote', undefined, locale)} /></Card>}
      <Drawer open={!!form} onClose={() => setForm(null)} title={form?.id ? t('adm.notifications.edit', undefined, locale) : t('adm.notifications.new', undefined, locale)} footer={<><button type="button" className="db-btn db-btn--ghost" onClick={() => setForm(null)}>{t('dash.action.cancel', undefined, locale)}</button><button type="button" className="db-btn db-btn--primary" disabled={busy} onClick={() => { void save() }} data-testid="ann-save">{t('adm.action.save', undefined, locale)}</button></>}>
        {form && <form className="db-grid" style={{ gap: 12 }} onSubmit={(e) => { e.preventDefault(); void save() }}>
          <Field label={t('adm.notifications.f.title', undefined, locale)} required error={err ? t('adm.promotions.err.required', undefined, locale) : undefined} id="an-title"><input id="an-title" className="db-input" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></Field>
          <div className="db-form-row"><Field label={t('adm.notifications.f.audience', undefined, locale)} id="an-aud"><select id="an-aud" className="db-select" value={form.audience} onChange={(e) => setForm({ ...form, audience: e.target.value as Announcement['audience'] })}>{(['customers', 'restaurants', 'admins'] as const).map((x) => <option key={x} value={x}>{t(`adm.notifications.audience.${x}`, undefined, locale)}</option>)}</select></Field><Field label={t('adm.notifications.f.channel', undefined, locale)} id="an-ch"><select id="an-ch" className="db-select" value={form.channel} onChange={(e) => setForm({ ...form, channel: e.target.value as Announcement['channel'] })}>{(['email', 'sms', 'push', 'in_app'] as const).map((x) => <option key={x} value={x}>{t(`adm.notifications.channel.${x}`, undefined, locale)}</option>)}</select></Field></div>
          <Field label={t('adm.notifications.f.markets', undefined, locale)} id="an-mk"><div className="db-tags">{KNOWN_MARKET_CODES.map((c) => <label key={c} className="db-chip" style={{ display: 'inline-flex', gap: 6 }}><input type="checkbox" checked={form.markets.includes(c)} onChange={(e) => setForm({ ...form, markets: e.target.checked ? [...form.markets, c] : form.markets.filter((x) => x !== c) })} />{c}</label>)}</div></Field>
          <div className="db-form-row"><Field label={t('adm.notifications.f.status', undefined, locale)} id="an-st"><select id="an-st" className="db-select" value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as Announcement['status'] })}><option value="DRAFT">{t('adm.notifications.annStatus.DRAFT', undefined, locale)}</option><option value="SCHEDULED">{t('adm.notifications.annStatus.SCHEDULED', undefined, locale)}</option></select></Field><Field label={t('adm.notifications.f.scheduledAt', undefined, locale)} id="an-at"><input id="an-at" type="datetime-local" className="db-input" value={form.scheduledAt ? form.scheduledAt.slice(0, 16) : ''} onChange={(e) => setForm({ ...form, scheduledAt: e.target.value ? new Date(e.target.value).toISOString() : null })} /></Field></div>
        </form>}
      </Drawer>
      <ToastLine msg={msg} />
    </div>
  )
}
