import { useMemo, useState } from 'react'
import { t } from '../../i18n/strings'
import { Card, Drawer, ErrorState, Field, Skeleton, Tabs, Toggle, ToastLine, useToastMessage } from '../../dashboard/components/ui'
import { fixtureScope } from '../../market/fixtureScope'
import { useAdmin } from '../AdminContext'
import { Badge, DevNote, ReasonDialog } from '../components/DataTable'
import type { ConfigItem, FeatureFlag, FeeConfig, Market } from '../types'
import { StatusPill, useLoad, usePageTitle } from './shared'

/* ------------------------------------------------------------------ Markets */
type MTab = 'markets' | 'taxes' | 'fees'
export function MarketsPage() {
  const a = useAdmin(); const locale = a.locale; usePageTitle('adm.nav.markets')
  const [tab, setTab] = useState<MTab>('markets'); const [form, setForm] = useState<Market | null>(null); const [fee, setFee] = useState<FeeConfig | null>(null); const [err, setErr] = useState<string | null>(null); const [busy, setBusy] = useState(false); const { msg, toast } = useToastMessage()
  const markets = useLoad(() => a.repos.markets.list(), [a.repos]); const taxes = useLoad(() => a.repos.markets.taxes(), [a.repos]); const fees = useLoad(() => a.repos.markets.fees(), [a.repos])
  const canManage = a.can('markets.manage')
  const saveMarket = async () => { if (!form) return; setBusy(true); setErr(null); try { await a.repos.markets.save(form, a.admin.id); setForm(null); await markets.refresh(); toast(t('adm.saved', undefined, locale)) } catch { setErr(t('adm.markets.err', undefined, locale)) } finally { setBusy(false) } }
  const saveFee = async () => { if (!fee) return; setBusy(true); setErr(null); try { await a.repos.markets.saveFee(fee, a.admin.id); setFee(null); await fees.refresh(); toast(t('adm.saved', undefined, locale)) } catch { setErr(t('adm.fees.err', undefined, locale)) } finally { setBusy(false) } }
  const list = (s: 'loading' | 'ready' | 'error', reload: () => void, body: React.ReactNode) => (s === 'loading' ? <Skeleton rows={4} /> : s === 'error' ? <ErrorState title={t('adm.error.loadTitle', undefined, locale)} onRetry={reload} locale={locale} /> : body)
  return (
    <div className="db-page" data-testid="adm-markets">
      <div className="db-page__head"><div><h1 className="db-page__title">{t('adm.mkt.registryTitle', undefined, locale)}</h1><p className="db-page__lead">{t('adm.markets.lead', undefined, locale)}</p></div>{canManage && tab === 'markets' && <div className="db-page__actions"><button type="button" className="db-btn db-btn--primary" onClick={() => setForm({ code: '', name: '', countryCode: '', defaultLocale: '', languages: [], currency: '', timezoneDefault: '', unitSystem: 'metric', paymentProviders: [], taxConfigRef: null, status: 'INACTIVE', restaurants: 0 })} data-testid="market-new">{t('adm.markets.new', undefined, locale)}</button></div>}</div>
      <Tabs tabs={(['markets', 'taxes', 'fees'] as MTab[]).map((id) => ({ id, label: t(`adm.markets.tab.${id}`, undefined, locale) }))} value={tab} onChange={setTab} label={t('adm.markets.tabs', undefined, locale)} />
      {tab === 'markets' && <Card>{list(markets.state, () => { void markets.reload() }, <div className="db-table-wrap" tabIndex={0}><table className="db-table" data-testid="markets-table"><caption className="db-sr-only">{t('adm.markets.tab.markets', undefined, locale)}</caption><thead><tr><th scope="col">{t('adm.markets.col.market', undefined, locale)}</th><th scope="col">{t('adm.markets.col.currency', undefined, locale)}</th><th scope="col">{t('adm.markets.col.locale', undefined, locale)}</th><th scope="col">{t('adm.markets.col.timezone', undefined, locale)}</th><th scope="col">{t('adm.markets.col.units', undefined, locale)}</th><th scope="col">{t('adm.markets.col.providers', undefined, locale)}</th><th scope="col">{t('adm.markets.col.tax', undefined, locale)}</th><th scope="col" className="adm-td--end">{t('adm.markets.col.restaurants', undefined, locale)}</th><th scope="col">{t('adm.markets.col.status', undefined, locale)}</th>{canManage && <th scope="col" className="adm-td--end">{t('adm.table.actions', undefined, locale)}</th>}</tr></thead>
        <tbody>{(markets.data ?? []).map((m) => <tr key={m.code}><td className="adm-td--primary">{m.name} <Badge tone="muted">{m.code}</Badge></td><td>{m.currency}</td><td>{m.defaultLocale}<br /><small className="db-muted">{m.languages.join(', ')}</small></td><td>{m.timezoneDefault}</td><td>{t(`adm.markets.units.${m.unitSystem}`, undefined, locale)}</td><td>{m.paymentProviders.length ? m.paymentProviders.join(', ') : <span className="db-muted">{t('adm.markets.noProviders', undefined, locale)}</span>}</td><td>{m.taxConfigRef ? <span className="adm-code">{m.taxConfigRef}</span> : '—'}</td><td className="adm-td--end">{m.restaurants}</td><td><StatusPill status={m.status} prefix="adm.markets.status" dot /></td>{canManage && <td className="adm-td--end"><button type="button" className="db-btn db-btn--outline db-btn--sm" onClick={() => setForm({ ...m })} data-testid={`market-edit-${m.code}`}>{t('adm.action.edit', undefined, locale)}</button></td>}</tr>)}</tbody></table></div>)}</Card>}
      {tab === 'taxes' && <Card title={t('adm.markets.tab.taxes', undefined, locale)} subtitle={t('adm.taxes.note', undefined, locale)}>{list(taxes.state, () => { void taxes.reload() }, <div className="db-table-wrap" tabIndex={0}><table className="db-table" data-testid="taxes-table"><caption className="db-sr-only">{t('adm.markets.tab.taxes', undefined, locale)}</caption><thead><tr><th scope="col">{t('adm.taxes.col.name', undefined, locale)}</th><th scope="col">{t('adm.taxes.col.market', undefined, locale)}</th><th scope="col">{t('adm.taxes.col.kind', undefined, locale)}</th><th scope="col" className="adm-td--end">{t('adm.taxes.col.rate', undefined, locale)}</th><th scope="col">{t('adm.taxes.col.applies', undefined, locale)}</th><th scope="col">{t('adm.taxes.col.effective', undefined, locale)}</th><th scope="col">{t('adm.taxes.col.status', undefined, locale)}</th></tr></thead><tbody>{(taxes.data ?? []).map((x) => <tr key={x.id}><td className="adm-td--primary">{x.name}<br /><small className="adm-code">{x.id}</small></td><td>{x.marketCode}</td><td>{x.kind}</td><td className="adm-td--end">{x.ratePercent == null ? t('adm.taxes.providerRate', undefined, locale) : `${x.ratePercent}%`}</td><td>{x.appliesTo}</td><td>{x.effectiveFrom}</td><td><StatusPill status={x.status} prefix="adm.notifications.annStatus" /></td></tr>)}</tbody></table></div>)}</Card>}
      {tab === 'fees' && <Card title={t('adm.markets.tab.fees', undefined, locale)} subtitle={t('adm.fees.note', undefined, locale)}>{list(fees.state, () => { void fees.reload() }, <div className="db-table-wrap" tabIndex={0}><table className="db-table" data-testid="fees-table"><caption className="db-sr-only">{t('adm.markets.tab.fees', undefined, locale)}</caption><thead><tr><th scope="col">{t('adm.fees.col.name', undefined, locale)}</th><th scope="col">{t('adm.fees.col.market', undefined, locale)}</th><th scope="col">{t('adm.fees.col.kind', undefined, locale)}</th><th scope="col">{t('adm.fees.col.model', undefined, locale)}</th><th scope="col" className="adm-td--end">{t('adm.fees.col.value', undefined, locale)}</th><th scope="col">{t('adm.fees.col.applies', undefined, locale)}</th><th scope="col">{t('adm.fees.col.status', undefined, locale)}</th>{canManage && <th scope="col" className="adm-td--end">{t('adm.table.actions', undefined, locale)}</th>}</tr></thead><tbody>{(fees.data ?? []).map((x) => <tr key={x.id}><td className="adm-td--primary">{x.name}</td><td>{x.marketCode === 'ALL' ? t('adm.fees.allMarkets', undefined, locale) : x.marketCode}</td><td>{t(`adm.fees.kind.${x.kind}`, undefined, locale)}</td><td>{t(`adm.fees.model.${x.model}`, undefined, locale)}</td><td className="adm-td--end">{x.model === 'percentage' ? `${x.value}%` : `${x.value} ${x.currency ?? ''}`}</td><td>{x.appliesTo}</td><td><StatusPill status={x.status} prefix="adm.notifications.annStatus" /></td>{canManage && <td className="adm-td--end"><button type="button" className="db-btn db-btn--outline db-btn--sm" onClick={() => setFee({ ...x })} data-testid={`fee-edit-${x.id}`}>{t('adm.action.edit', undefined, locale)}</button></td>}</tr>)}</tbody></table></div>)}</Card>}
      <Drawer open={!!form} onClose={() => setForm(null)} title={form?.name ? `${t('adm.markets.edit', undefined, locale)} · ${form.name}` : t('adm.markets.new', undefined, locale)} footer={<><button type="button" className="db-btn db-btn--ghost" onClick={() => setForm(null)}>{t('dash.action.cancel', undefined, locale)}</button><button type="button" className="db-btn db-btn--primary" disabled={busy} onClick={() => { void saveMarket() }} data-testid="market-save">{t('adm.action.save', undefined, locale)}</button></>}>
        {form && <form className="db-grid" style={{ gap: 12 }} onSubmit={(e) => { e.preventDefault(); void saveMarket() }} data-testid="market-form">
          {err && <p className="db-field__error" role="alert">{err}</p>}
          <div className="db-form-row"><Field label={t('adm.markets.f.code', undefined, locale)} required id="m-code"><input id="m-code" className="db-input" value={form.code} maxLength={2} onChange={(e) => setForm({ ...form, code: e.target.value.toUpperCase(), countryCode: e.target.value.toUpperCase() })} /></Field><Field label={t('adm.markets.f.name', undefined, locale)} required id="m-name"><input id="m-name" className="db-input" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Field></div>
          <div className="db-form-row"><Field label={t('adm.markets.f.currency', undefined, locale)} required id="m-cur"><input id="m-cur" className="db-input" value={form.currency} maxLength={3} onChange={(e) => setForm({ ...form, currency: e.target.value.toUpperCase() })} data-testid="market-currency" /></Field><Field label={t('adm.markets.f.locale', undefined, locale)} id="m-loc"><input id="m-loc" className="db-input" value={form.defaultLocale} onChange={(e) => setForm({ ...form, defaultLocale: e.target.value })} /></Field></div>
          <div className="db-form-row"><Field label={t('adm.markets.f.timezone', undefined, locale)} required id="m-tz"><input id="m-tz" className="db-input" value={form.timezoneDefault} onChange={(e) => setForm({ ...form, timezoneDefault: e.target.value })} /></Field><Field label={t('adm.markets.f.units', undefined, locale)} id="m-units"><select id="m-units" className="db-select" value={form.unitSystem} onChange={(e) => setForm({ ...form, unitSystem: e.target.value as Market['unitSystem'] })}><option value="metric">{t('adm.markets.units.metric', undefined, locale)}</option><option value="imperial">{t('adm.markets.units.imperial', undefined, locale)}</option></select></Field></div>
          <Field label={t('adm.markets.f.languages', undefined, locale)} id="m-lang"><input id="m-lang" className="db-input" value={form.languages.join(', ')} onChange={(e) => setForm({ ...form, languages: e.target.value.split(',').map((x) => x.trim()).filter(Boolean) })} /></Field>
          <Field label={t('adm.markets.f.providers', undefined, locale)} id="m-prov"><input id="m-prov" className="db-input" value={form.paymentProviders.join(', ')} onChange={(e) => setForm({ ...form, paymentProviders: e.target.value.split(',').map((x) => x.trim()).filter(Boolean) })} /></Field>
          <Field label={t('adm.markets.f.status', undefined, locale)} id="m-status"><select id="m-status" className="db-select" disabled={fixtureScope() !== 'global'} aria-describedby="m-status-note" value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as Market['status'] })}>{(['ACTIVE', 'PILOT', 'INACTIVE'] as const).map((st) => <option key={st} value={st}>{t(`adm.markets.status.${st}`, undefined, locale)}</option>)}</select><p id="m-status-note" className="db-field__hint">{t('adm.mkt.registryStatusNote', undefined, locale)}</p></Field>
        </form>}
      </Drawer>
      <Drawer open={!!fee} onClose={() => setFee(null)} title={fee ? `${t('adm.fees.edit', undefined, locale)} · ${fee.name}` : ''} footer={<><button type="button" className="db-btn db-btn--ghost" onClick={() => setFee(null)}>{t('dash.action.cancel', undefined, locale)}</button><button type="button" className="db-btn db-btn--primary" disabled={busy} onClick={() => { void saveFee() }} data-testid="fee-save">{t('adm.action.save', undefined, locale)}</button></>}>
        {fee && <form className="db-grid" style={{ gap: 12 }} onSubmit={(e) => { e.preventDefault(); void saveFee() }}>{err && <p className="db-field__error" role="alert">{err}</p>}
          <Field label={t('adm.fees.f.value', undefined, locale)} required id="f-val"><input id="f-val" className="db-input" inputMode="decimal" value={String(fee.value)} onChange={(e) => setFee({ ...fee, value: Number(e.target.value) })} data-testid="fee-value" /></Field>
          <Field label={t('adm.fees.f.status', undefined, locale)} id="f-st"><select id="f-st" className="db-select" value={fee.status} onChange={(e) => setFee({ ...fee, status: e.target.value as FeeConfig['status'] })}><option value="DRAFT">{t('adm.notifications.annStatus.DRAFT', undefined, locale)}</option><option value="ACTIVE">{t('adm.markets.status.ACTIVE', undefined, locale)}</option></select></Field>
          <DevNote>{t('adm.fees.note', undefined, locale)}</DevNote></form>}
      </Drawer>
      <ToastLine msg={msg} />
    </div>
  )
}

/* ------------------------------------------------------------------ Configuration */
export function ConfigurationPage() {
  const a = useAdmin(); const locale = a.locale; usePageTitle('adm.nav.configuration')
  const [tab, setTab] = useState<'settings' | 'flags'>('settings'); const [edit, setEdit] = useState<ConfigItem | null>(null); const [value, setValue] = useState(''); const [flag, setFlag] = useState<FeatureFlag | null>(null); const [busy, setBusy] = useState(false); const { msg, toast } = useToastMessage()
  const items = useLoad(() => a.repos.configuration.items(), [a.repos]); const flags = useLoad(() => a.repos.configuration.flags(), [a.repos])
  const grouped = useMemo(() => { const g = new Map<string, ConfigItem[]>(); for (const i of items.data ?? []) g.set(i.category, [...(g.get(i.category) ?? []), i]); return g }, [items.data])
  const parse = (item: ConfigItem, v: string): ConfigItem['value'] => (typeof item.value === 'number' ? Number(v) : typeof item.value === 'boolean' ? v === 'true' : v)
  return (
    <div className="db-page" data-testid="adm-configuration">
      <div className="db-page__head"><div><h1 className="db-page__title">{t('adm.config.title', undefined, locale)}</h1><p className="db-page__lead">{t('adm.config.lead', undefined, locale)}</p></div></div>
      <Tabs tabs={[{ id: 'settings' as const, label: t('adm.config.tab.settings', undefined, locale) }, { id: 'flags' as const, label: t('adm.config.tab.flags', undefined, locale) }]} value={tab} onChange={setTab} label={t('adm.config.tabs', undefined, locale)} />
      {tab === 'settings' && (items.state !== 'ready' ? <Card><Skeleton rows={5} /></Card> : Array.from(grouped, ([cat, list]) => <Card key={cat} title={t(`adm.config.category.${cat}`, undefined, locale)}><div className="db-table-wrap" tabIndex={0}><table className="db-table" data-testid={`config-${cat}`}><caption className="db-sr-only">{cat}</caption><thead><tr><th scope="col">{t('adm.config.col.key', undefined, locale)}</th><th scope="col">{t('adm.config.col.value', undefined, locale)}</th><th scope="col" className="adm-hide-mobile">{t('adm.config.col.description', undefined, locale)}</th><th scope="col" className="adm-td--end">{t('adm.table.actions', undefined, locale)}</th></tr></thead><tbody>{list.map((i) => <tr key={i.key}><td><span className="adm-code">{i.key}</span></td><td><b>{String(i.value)}</b></td><td className="adm-hide-mobile">{i.description}</td><td className="adm-td--end">{i.editable ? <button type="button" className="db-btn db-btn--outline db-btn--sm" onClick={() => { setEdit(i); setValue(String(i.value)) }} data-testid={`config-edit-${i.key}`}>{t('adm.action.edit', undefined, locale)}</button> : <Badge tone="muted">{t('adm.config.locked', undefined, locale)}</Badge>}</td></tr>)}</tbody></table></div></Card>))}
      {tab === 'flags' && <Card title={t('adm.config.tab.flags', undefined, locale)} subtitle={t('adm.config.flagNote', undefined, locale)}>{flags.state !== 'ready' ? <Skeleton rows={5} /> : <div data-testid="flags">{(flags.data ?? []).map((f) => <div key={f.key} className="adm-flag"><span className="adm-flag__text"><b><span className="adm-code">{f.key}</span> <Badge tone="muted">{t(`adm.config.scope.${f.scope}`, undefined, locale)}{f.markets.length ? ` · ${f.markets.join(', ')}` : ''}</Badge></b><small>{f.description}</small></span><Toggle checked={f.enabled} onChange={() => setFlag(f)} label={f.key} testId={`flag-${f.key}`} /></div>)}</div>}</Card>}
      <ReasonDialog open={!!edit} title={edit ? t('adm.config.editTitle', { key: edit.key }, locale) : ''} text={edit?.description} confirmLabel={t('adm.action.save', undefined, locale)} danger={false} busy={busy} locale={locale} onCancel={() => setEdit(null)} extraFields={edit && <Field label={t('adm.config.newValue', undefined, locale)} id="cfg-val">{typeof edit.value === 'boolean' ? <select id="cfg-val" className="db-select" value={value} onChange={(e) => setValue(e.target.value)} data-testid="config-value"><option value="true">true</option><option value="false">false</option></select> : <input id="cfg-val" className="db-input" value={value} inputMode={typeof edit.value === 'number' ? 'numeric' : undefined} onChange={(e) => setValue(e.target.value)} data-testid="config-value" />}</Field>} onConfirm={async (reason) => { if (!edit) return; setBusy(true); try { await a.repos.configuration.setValue(edit.key, parse(edit, value), a.admin.id, reason); setEdit(null); await items.refresh(); toast(t('adm.saved', undefined, locale)) } finally { setBusy(false) } }} testId="config-dialog" />
      <ReasonDialog open={!!flag} title={flag ? t('adm.config.flagTitle', { key: flag.key, state: t(flag.enabled ? 'adm.config.flagOff' : 'adm.config.flagOn', undefined, locale) }, locale) : ''} text={t('adm.config.flagNote', undefined, locale)} confirmLabel={t('adm.action.apply', undefined, locale)} danger={!!flag?.enabled} busy={busy} locale={locale} onCancel={() => setFlag(null)} onConfirm={async (reason) => { if (!flag) return; setBusy(true); try { await a.repos.configuration.setFlag(flag.key, !flag.enabled, a.admin.id, reason); setFlag(null); await flags.refresh(); toast(t('adm.updated', undefined, locale)) } finally { setBusy(false) } }} testId="flag-dialog" />
      <ToastLine msg={msg} />
    </div>
  )
}
