import { useMemo, useState } from 'react'
import { t } from '../../i18n/strings'
import { Card, Drawer, Field, ToastLine, useToastMessage } from '../../dashboard/components/ui'
import { useAdmin } from '../AdminContext'
import { validatePromotion } from '../mock/mockAdmin'
import { Badge, DataTable, DevNote, ReasonDialog, Select, Toolbar, useUrlState, type Column } from '../components/DataTable'
import type { Promotion, PromotionIssue, PromotionStatus } from '../types'
import { Cell, KNOWN_MARKET_CODES, StatusPill, fmtDate, money, useLoad, usePageTitle } from './shared'

const DEFAULTS = { q: '', status: 'all', page: '1' }
const STATUSES: PromotionStatus[] = ['DRAFT', 'SCHEDULED', 'ACTIVE', 'PAUSED', 'EXPIRED', 'DISABLED']
const CURRENCIES = ['INR', 'USD', 'GBP', 'JPY', 'EUR', 'AED']
type Form = Omit<Promotion, 'id' | 'usedCount' | 'createdAt' | 'value' | 'minimumSpendMinor' | 'maximumDiscountMinor' | 'usageLimit' | 'perCustomerLimit'> & { id?: string; value: string; minimumSpendMinor: string; maximumDiscountMinor: string; usageLimit: string; perCustomerLimit: string }
const blank = (): Form => ({ code: '', name: '', description: '', type: 'percentage', value: '', currency: null, startsAt: new Date().toISOString().slice(0, 10), endsAt: '', minimumSpendMinor: '', maximumDiscountMinor: '', usageLimit: '', perCustomerLimit: '1', scope: 'platform', marketCode: null, restaurantId: null, status: 'DRAFT' })
const toForm = (p: Promotion): Form => ({ ...p, value: String(p.value), minimumSpendMinor: p.minimumSpendMinor == null ? '' : String(p.minimumSpendMinor), maximumDiscountMinor: p.maximumDiscountMinor == null ? '' : String(p.maximumDiscountMinor), usageLimit: p.usageLimit == null ? '' : String(p.usageLimit), perCustomerLimit: p.perCustomerLimit == null ? '' : String(p.perCustomerLimit), startsAt: p.startsAt.slice(0, 10), endsAt: p.endsAt.slice(0, 10) })
const num = (s: string) => (s.trim() === '' ? null : Number(s))
export const fromForm = (f: Form) => ({ ...f, code: f.code.trim().toUpperCase(), value: Number(f.value), currency: f.type === 'fixed' ? f.currency : null, minimumSpendMinor: num(f.minimumSpendMinor), maximumDiscountMinor: num(f.maximumDiscountMinor), usageLimit: num(f.usageLimit), perCustomerLimit: num(f.perCustomerLimit), startsAt: f.startsAt ? `${f.startsAt}T00:00:00.000Z` : '', endsAt: f.endsAt ? `${f.endsAt}T23:59:59.000Z` : '', marketCode: f.scope === 'market' ? f.marketCode : f.scope === 'restaurant' ? f.marketCode : null, restaurantId: f.scope === 'restaurant' ? f.restaurantId : null })

/** Promotions (Module 18): campaigns with validation; eligibility and discount computation are backend-authoritative. */
export default function PromotionsPage() {
  const a = useAdmin(); const locale = a.locale; usePageTitle('adm.nav.promotions')
  const [s, set] = useUrlState(DEFAULTS); const [form, setForm] = useState<Form | null>(null); const [issues, setIssues] = useState<PromotionIssue[]>([]); const [statusTarget, setStatusTarget] = useState<{ p: Promotion; to: PromotionStatus } | null>(null); const [busy, setBusy] = useState(false); const { msg, toast } = useToastMessage()
  const filter = useMemo(() => ({ query: s.q, status: s.status as PromotionStatus | 'all', page: Number(s.page) || 1, pageSize: 10 }), [s])
  const { data, state, reload, refresh } = useLoad(() => a.repos.promotions.list(filter), [a.repos, filter])
  const canManage = a.can('promotions.manage')
  const issue = (field: string) => { const i = issues.find((x) => x.field === field); return i ? t(`adm.promotions.err.${i.code}`, undefined, locale) : undefined }
  const save = async () => { if (!form) return; const p = fromForm(form); const v = validatePromotion(p); setIssues(v); if (v.length) return; setBusy(true); try { await a.repos.promotions.save(p, a.admin.id); setForm(null); await refresh(); toast(t('adm.saved', undefined, locale)) } catch (e) { const x = e as Error & { issues?: PromotionIssue[] }; setIssues(x.issues ?? [{ field: 'code', code: 'invalid' }]) } finally { setBusy(false) } }
  const next = (p: Promotion): Array<{ to: PromotionStatus; label: string }> => p.status === 'ACTIVE' ? [{ to: 'PAUSED', label: t('adm.promotions.pause', undefined, locale) }, { to: 'DISABLED', label: t('adm.promotions.disable', undefined, locale) }] : p.status === 'PAUSED' ? [{ to: 'ACTIVE', label: t('adm.promotions.resume', undefined, locale) }, { to: 'DISABLED', label: t('adm.promotions.disable', undefined, locale) }] : p.status === 'DRAFT' || p.status === 'SCHEDULED' ? [{ to: 'ACTIVE', label: t('adm.promotions.activate', undefined, locale) }, { to: 'DISABLED', label: t('adm.promotions.disable', undefined, locale) }] : p.status === 'EXPIRED' ? [{ to: 'DISABLED', label: t('adm.promotions.disable', undefined, locale) }] : []
  const columns: Array<Column<Promotion>> = [
    { id: 'code', label: t('adm.promotions.col.code', undefined, locale), primary: true, render: (p) => <Cell primary={<span className="adm-code">{p.code}</span>} secondary={p.name} /> },
    { id: 'type', label: t('adm.promotions.col.type', undefined, locale), hideMobile: true, render: (p) => t(`adm.promotions.type.${p.type}`, undefined, locale) },
    { id: 'value', label: t('adm.promotions.col.value', undefined, locale), align: 'end', render: (p) => (p.type === 'percentage' ? `${p.value}%` : <span>{money(p.value, p.currency!, locale)} <Badge tone="muted">{p.currency}</Badge></span>) },
    { id: 'scope', label: t('adm.promotions.col.scope', undefined, locale), hideMobile: true, render: (p) => <span>{t(`adm.promotions.scope.${p.scope}`, undefined, locale)}{p.marketCode ? ` · ${p.marketCode}` : ''}{p.restaurantId ? ` · ${p.restaurantId}` : ''}</span> },
    { id: 'period', label: t('adm.promotions.col.period', undefined, locale), hideMobile: true, render: (p) => `${fmtDate(p.startsAt, locale)} – ${fmtDate(p.endsAt, locale)}` },
    { id: 'usage', label: t('adm.promotions.col.usage', undefined, locale), align: 'end', hideMobile: true, render: (p) => t('adm.promotions.usage', { used: p.usedCount.toLocaleString(locale), limit: p.usageLimit == null ? t('adm.promotions.unlimited', undefined, locale) : p.usageLimit.toLocaleString(locale) }, locale) },
    { id: 'status', label: t('adm.promotions.col.status', undefined, locale), render: (p) => <StatusPill status={p.status} prefix="adm.promoStatus" dot /> },
  ]
  return (
    <div className="db-page" data-testid="adm-promotions">
      <div className="db-page__head"><div><h1 className="db-page__title">{t('adm.promotions.title', undefined, locale)}</h1><p className="db-page__lead">{t('adm.promotions.lead', undefined, locale)}</p></div>{canManage && <div className="db-page__actions"><button type="button" className="db-btn db-btn--primary" onClick={() => { setIssues([]); setForm(blank()) }} data-testid="promo-new">{t('adm.promotions.new', undefined, locale)}</button></div>}</div>
      <Card>
        <Toolbar search={s.q} onSearch={(q) => set({ q })} placeholder={t('adm.promotions.search', undefined, locale)} locale={locale}><Select label={t('adm.promotions.col.status', undefined, locale)} value={s.status} onChange={(status) => set({ status })} options={[{ value: 'all', label: t('adm.status.all', undefined, locale) }, ...STATUSES.map((v) => ({ value: v, label: t(`adm.promoStatus.${v}`, undefined, locale) }))]} testId="filter-status" /></Toolbar>
        <DataTable columns={columns} rows={data?.items ?? []} keyOf={(p) => p.id} state={state} total={data?.total ?? 0} page={filter.page} pageSize={10} onPage={(page) => set({ page: String(page) })} empty={{ icon: 'promotions', title: t('adm.promotions.empty', undefined, locale) }} onRetry={() => { void reload() }} locale={locale} testId="promotions-table" caption={t('adm.promotions.title', undefined, locale)} actions={canManage ? (p) => <>{next(p).map((n) => <button key={n.to} type="button" className={`db-btn db-btn--sm ${n.to === 'DISABLED' ? 'db-btn--danger' : 'db-btn--outline'}`} onClick={() => setStatusTarget({ p, to: n.to })} data-testid={`promo-${n.to.toLowerCase()}`}>{n.label}</button>)}{p.status !== 'DISABLED' && <button type="button" className="db-btn db-btn--ghost db-btn--sm" onClick={() => { setIssues([]); setForm(toForm(p)) }}>{t('adm.action.edit', undefined, locale)}</button>}</> : undefined} />
      </Card>
      <DevNote>{t('adm.promotions.lead', undefined, locale)}</DevNote>
      <Drawer open={!!form} onClose={() => setForm(null)} title={form?.id ? t('adm.promotions.edit', undefined, locale) : t('adm.promotions.new', undefined, locale)} wide footer={<><button type="button" className="db-btn db-btn--ghost" onClick={() => setForm(null)}>{t('dash.action.cancel', undefined, locale)}</button><button type="button" className="db-btn db-btn--primary" onClick={() => { void save() }} disabled={busy} data-testid="promo-save">{busy ? t('dash.action.saving', undefined, locale) : t('adm.action.save', undefined, locale)}</button></>}>
        {form && <form className="db-grid" style={{ gap: 12 }} onSubmit={(e) => { e.preventDefault(); void save() }} data-testid="promo-form">
          <div className="db-form-row"><Field label={t('adm.promotions.f.code', undefined, locale)} required error={issue('code')} id="p-code"><input id="p-code" className="db-input" value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value.toUpperCase() })} /></Field><Field label={t('adm.promotions.f.name', undefined, locale)} required error={issue('name')} id="p-name"><input id="p-name" className="db-input" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Field></div>
          <Field label={t('adm.promotions.f.description', undefined, locale)} id="p-desc"><input id="p-desc" className="db-input" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></Field>
          <div className="db-form-row"><Field label={t('adm.promotions.f.type', undefined, locale)} id="p-type"><select id="p-type" className="db-select" value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value as Promotion['type'], currency: e.target.value === 'fixed' ? form.currency ?? (a.marketModel?.defaultCurrency ?? CURRENCIES[0]) : null })}><option value="percentage">{t('adm.promotions.type.percentage', undefined, locale)}</option><option value="fixed">{t('adm.promotions.type.fixed', undefined, locale)}</option></select></Field><Field label={form.type === 'percentage' ? t('adm.promotions.f.valuePct', undefined, locale) : t('adm.promotions.f.valueFixed', { currency: form.currency ?? '' }, locale)} required error={issue('value')} id="p-value"><input id="p-value" className="db-input" inputMode="numeric" value={form.value} onChange={(e) => setForm({ ...form, value: e.target.value })} /></Field></div>
          {form.type === 'fixed' && <Field label={t('adm.promotions.f.currency', undefined, locale)} required error={issue('currency')} id="p-cur"><select id="p-cur" className="db-select" value={form.currency ?? ''} onChange={(e) => setForm({ ...form, currency: e.target.value || null })}><option value="">—</option>{CURRENCIES.map((c) => <option key={c} value={c}>{c}</option>)}</select></Field>}
          <div className="db-form-row"><Field label={t('adm.promotions.f.starts', undefined, locale)} required error={issue('dates')} id="p-start"><input id="p-start" type="date" className="db-input" value={form.startsAt} onChange={(e) => setForm({ ...form, startsAt: e.target.value })} /></Field><Field label={t('adm.promotions.f.ends', undefined, locale)} required id="p-end"><input id="p-end" type="date" className="db-input" value={form.endsAt} onChange={(e) => setForm({ ...form, endsAt: e.target.value })} /></Field></div>
          <div className="db-form-row"><Field label={t('adm.promotions.f.minSpend', undefined, locale)} error={issue('minimumSpendMinor')} id="p-min"><input id="p-min" className="db-input" inputMode="numeric" value={form.minimumSpendMinor} onChange={(e) => setForm({ ...form, minimumSpendMinor: e.target.value })} /></Field><Field label={t('adm.promotions.f.maxDiscount', undefined, locale)} id="p-max"><input id="p-max" className="db-input" inputMode="numeric" value={form.maximumDiscountMinor} onChange={(e) => setForm({ ...form, maximumDiscountMinor: e.target.value })} /></Field></div>
          <div className="db-form-row"><Field label={t('adm.promotions.f.usageLimit', undefined, locale)} error={issue('usageLimit')} id="p-lim"><input id="p-lim" className="db-input" inputMode="numeric" value={form.usageLimit} onChange={(e) => setForm({ ...form, usageLimit: e.target.value })} /></Field><Field label={t('adm.promotions.f.perCustomer', undefined, locale)} id="p-pc"><input id="p-pc" className="db-input" inputMode="numeric" value={form.perCustomerLimit} onChange={(e) => setForm({ ...form, perCustomerLimit: e.target.value })} /></Field></div>
          <div className="db-form-row"><Field label={t('adm.promotions.f.scope', undefined, locale)} id="p-scope"><select id="p-scope" className="db-select" value={form.scope} onChange={(e) => setForm({ ...form, scope: e.target.value as Promotion['scope'] })}>{(['platform', 'market', 'restaurant'] as const).map((sc) => <option key={sc} value={sc}>{t(`adm.promotions.scope.${sc}`, undefined, locale)}</option>)}</select></Field>{form.scope !== 'platform' && <Field label={t('adm.promotions.f.market', undefined, locale)} required error={issue('marketCode')} id="p-mkt"><select id="p-mkt" className="db-select" value={form.marketCode ?? ''} onChange={(e) => setForm({ ...form, marketCode: e.target.value || null })}><option value="">—</option>{KNOWN_MARKET_CODES.map((c) => <option key={c} value={c}>{c}</option>)}</select></Field>}</div>
          {form.scope === 'restaurant' && <Field label={t('adm.promotions.f.restaurant', undefined, locale)} required error={issue('restaurantId')} id="p-rest"><input id="p-rest" className="db-input" value={form.restaurantId ?? ''} onChange={(e) => setForm({ ...form, restaurantId: e.target.value || null })} placeholder="burger-hub" /></Field>}
          <Field label={t('adm.promotions.f.status', undefined, locale)} id="p-status"><select id="p-status" className="db-select" value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as PromotionStatus })}>{(['DRAFT', 'SCHEDULED', 'ACTIVE'] as PromotionStatus[]).map((st) => <option key={st} value={st}>{t(`adm.promoStatus.${st}`, undefined, locale)}</option>)}</select></Field>
          <DevNote>{t('adm.promotions.lead', undefined, locale)}</DevNote>
        </form>}
      </Drawer>
      <ReasonDialog open={!!statusTarget} title={statusTarget ? t('adm.promotions.statusTitle', { code: statusTarget.p.code, status: t(`adm.promoStatus.${statusTarget.to}`, undefined, locale) }, locale) : ''} confirmLabel={t('adm.action.apply', undefined, locale)} danger={statusTarget?.to === 'DISABLED'} requireReason={statusTarget?.to === 'DISABLED' || statusTarget?.to === 'PAUSED'} busy={busy} locale={locale} onCancel={() => setStatusTarget(null)} onConfirm={async (reason) => { if (!statusTarget) return; setBusy(true); try { await a.repos.promotions.setStatus(statusTarget.p.id, statusTarget.to, a.admin.id, reason); setStatusTarget(null); await refresh(); toast(t('adm.updated', undefined, locale)) } finally { setBusy(false) } }} testId="promo-status-dialog" />
      <ToastLine msg={msg} />
    </div>
  )
}
