import { useMemo, useState } from 'react'
import { t } from '../../i18n/strings'
import { Avatar, Card, Drawer, ErrorState, Field, Skeleton, Tabs, ToastLine, useToastMessage } from '../../dashboard/components/ui'
import { useAdmin } from '../AdminContext'
import { Badge, DataTable, Details, DevNote, ReasonDialog, Select, Stat, Toolbar, useUrlState, type Column } from '../components/DataTable'
import type { AdminRoleId, AdminStatus, AdminUser, AuditEvent, AuditFilter } from '../types'
import { Cell, StatusPill, fmtDateTime, useLoad, usePageTitle } from './shared'

/* ------------------------------------------------------------------ Admin users & roles */
const ROLE_IDS: AdminRoleId[] = ['super_admin', 'operations_admin', 'restaurant_onboarding', 'support_admin', 'finance_admin', 'moderation_admin', 'analyst']
export function AdminUsersPage() {
  const a = useAdmin(); const locale = a.locale; usePageTitle('adm.nav.adminUsers')
  const [tab, setTab] = useState<'users' | 'roles'>('users'); const [invite, setInvite] = useState<{ name: string; email: string; role: AdminRoleId } | null>(null); const [target, setTarget] = useState<{ u: AdminUser; role?: AdminRoleId; status?: AdminStatus } | null>(null); const [err, setErr] = useState<string | null>(null); const [busy, setBusy] = useState(false); const { msg, toast } = useToastMessage()
  const users = useLoad(() => a.repos.adminUsers.list(), [a.repos]); const roles = a.repos.adminUsers.roles(); const canManage = a.can('admin_users.manage')
  const doInvite = async () => { if (!invite) return; setBusy(true); setErr(null); try { await a.repos.adminUsers.invite(invite, a.admin.id); setInvite(null); await users.refresh(); toast(t('adm.saved', undefined, locale)) } catch (e) { setErr((e as Error).message === 'duplicate_email' ? t('adm.users.err.duplicate', undefined, locale) : t('adm.users.err.invalid', undefined, locale)) } finally { setBusy(false) } }
  const [newRole, setNewRole] = useState<AdminRoleId>('analyst')
  return (
    <div className="db-page" data-testid="adm-users">
      <div className="db-page__head"><div><h1 className="db-page__title">{t('adm.users.title', undefined, locale)}</h1><p className="db-page__lead">{t('adm.users.lead', undefined, locale)}</p></div>{canManage && <div className="db-page__actions"><button type="button" className="db-btn db-btn--primary" onClick={() => { setErr(null); setInvite({ name: '', email: '', role: 'analyst' }) }} data-testid="user-invite">{t('adm.users.invite', undefined, locale)}</button></div>}</div>
      <Tabs tabs={[{ id: 'users' as const, label: t('adm.users.tab.users', undefined, locale), count: users.data?.length }, { id: 'roles' as const, label: t('adm.users.tab.roles', undefined, locale) }]} value={tab} onChange={setTab} label={t('adm.users.tabs', undefined, locale)} />
      {tab === 'users' && <Card>{users.state === 'loading' ? <Skeleton rows={5} /> : users.state === 'error' ? <ErrorState title={t('adm.error.loadTitle', undefined, locale)} onRetry={() => { void users.reload() }} locale={locale} /> : <div className="db-table-wrap" tabIndex={0}><table className="db-table" data-testid="users-table"><caption className="db-sr-only">{t('adm.users.tab.users', undefined, locale)}</caption><thead><tr><th scope="col">{t('adm.users.col.user', undefined, locale)}</th><th scope="col">{t('adm.users.col.role', undefined, locale)}</th><th scope="col">{t('adm.users.col.status', undefined, locale)}</th><th scope="col" className="adm-hide-mobile">{t('adm.users.col.mfa', undefined, locale)}</th><th scope="col" className="adm-hide-mobile">{t('adm.users.col.lastLogin', undefined, locale)}</th>{canManage && <th scope="col" className="adm-td--end">{t('adm.table.actions', undefined, locale)}</th>}</tr></thead>
        <tbody>{(users.data ?? []).map((u) => <tr key={u.id}><td><Cell thumb={<Avatar name={u.name} size={34} />} primary={<>{u.name}{u.id === a.admin.id && <Badge tone="blue">you</Badge>}</>} secondary={u.email} /></td><td>{t(`adm.role.${u.role}`, undefined, locale)}</td><td><StatusPill status={u.status} prefix="adm.userStatus" dot /></td><td className="adm-hide-mobile">{u.mfaEnrolled ? <Badge tone="green">{t('adm.users.mfaOn', undefined, locale)}</Badge> : <Badge tone="amber">{t('adm.users.mfaOff', undefined, locale)}</Badge>}</td><td className="adm-hide-mobile">{u.lastLoginAt ? fmtDateTime(u.lastLoginAt, locale) : t('adm.users.never', undefined, locale)}</td>{canManage && <td className="adm-td--end"><div className="db-table__actions">{u.id !== a.admin.id && <><button type="button" className="db-btn db-btn--outline db-btn--sm" onClick={() => { setNewRole(u.role); setTarget({ u, role: u.role }) }} data-testid={`user-role-${u.id}`}>{t('adm.users.changeRole', undefined, locale)}</button>{u.status === 'ACTIVE' || u.status === 'INVITED' ? <button type="button" className="db-btn db-btn--danger db-btn--sm" onClick={() => setTarget({ u, status: 'SUSPENDED' })} data-testid={`user-suspend-${u.id}`}>{t('adm.action.suspend', undefined, locale)}</button> : u.status === 'SUSPENDED' ? <button type="button" className="db-btn db-btn--success db-btn--sm" onClick={() => setTarget({ u, status: 'ACTIVE' })}>{t('adm.action.reactivate', undefined, locale)}</button> : null}</>}</div></td>}</tr>)}</tbody></table></div>}<DevNote>{t('adm.users.mfaNote', undefined, locale)} {t('adm.users.selfNote', undefined, locale)}</DevNote></Card>}
      {tab === 'roles' && <Card><div className="adm-perm-grid" data-testid="roles-grid">{roles.map((r) => <div key={r.id} className="adm-perm-card"><h3>{t(`adm.role.${r.id}`, undefined, locale)}</h3><p>{t(`adm.users.roleDesc.${r.id}`, undefined, locale)}</p><ul aria-label={t('adm.users.permissions', undefined, locale)}>{r.permissions.map((p) => <li key={p}>{p}</li>)}</ul></div>)}</div></Card>}
      <Drawer open={!!invite} onClose={() => setInvite(null)} title={t('adm.users.invite', undefined, locale)} footer={<><button type="button" className="db-btn db-btn--ghost" onClick={() => setInvite(null)}>{t('dash.action.cancel', undefined, locale)}</button><button type="button" className="db-btn db-btn--primary" disabled={busy} onClick={() => { void doInvite() }} data-testid="invite-save">{t('adm.action.invite', undefined, locale)}</button></>}>
        {invite && <form className="db-grid" style={{ gap: 12 }} onSubmit={(e) => { e.preventDefault(); void doInvite() }}>{err && <p className="db-field__error" role="alert">{err}</p>}<Field label={t('adm.users.f.name', undefined, locale)} required id="u-name"><input id="u-name" className="db-input" value={invite.name} onChange={(e) => setInvite({ ...invite, name: e.target.value })} /></Field><Field label={t('adm.users.f.email', undefined, locale)} required id="u-email"><input id="u-email" type="email" className="db-input" value={invite.email} onChange={(e) => setInvite({ ...invite, email: e.target.value })} /></Field><Field label={t('adm.users.f.role', undefined, locale)} id="u-role"><select id="u-role" className="db-select" value={invite.role} onChange={(e) => setInvite({ ...invite, role: e.target.value as AdminRoleId })}>{ROLE_IDS.map((r) => <option key={r} value={r}>{t(`adm.role.${r}`, undefined, locale)}</option>)}</select></Field><DevNote>{t('adm.users.mfaNote', undefined, locale)}</DevNote></form>}
      </Drawer>
      <ReasonDialog open={!!target} title={target?.status ? t('adm.users.statusTitle', { name: target.u.name, status: t(`adm.userStatus.${target.status}`, undefined, locale) }, locale) : target ? t('adm.users.roleTitle', { name: target.u.name }, locale) : ''} confirmLabel={t('adm.action.apply', undefined, locale)} danger={target?.status === 'SUSPENDED'} busy={busy} locale={locale} onCancel={() => setTarget(null)} extraFields={target && !target.status ? <Field label={t('adm.users.f.role', undefined, locale)} id="u-newrole"><select id="u-newrole" className="db-select" value={newRole} onChange={(e) => setNewRole(e.target.value as AdminRoleId)} data-testid="user-newrole">{ROLE_IDS.map((r) => <option key={r} value={r}>{t(`adm.role.${r}`, undefined, locale)}</option>)}</select></Field> : undefined} onConfirm={async (reason) => { if (!target) return; setBusy(true); try { await a.repos.adminUsers.update(target.u.id, target.status ? { status: target.status } : { role: newRole }, a.admin.id, reason); setTarget(null); await users.refresh(); toast(t('adm.updated', undefined, locale)) } finally { setBusy(false) } }} testId="user-dialog" />
      <ToastLine msg={msg} />
    </div>
  )
}

/* ------------------------------------------------------------------ Audit logs */
const A_DEFAULTS = { q: '', action: 'all', target: 'all', result: 'all', from: '', to: '', page: '1', src: '' }
export function AuditLogsPage() {
  const a = useAdmin(); const locale = a.locale; usePageTitle('adm.nav.auditLogs')
  const [s, set] = useUrlState(A_DEFAULTS); const [open, setOpen] = useState<AuditEvent | null>(null)
  const filter = useMemo<AuditFilter>(() => ({ query: s.q, action: s.action, targetType: s.target, result: s.result as AuditFilter['result'], from: s.from || undefined, to: s.to || undefined, page: Number(s.page) || 1, pageSize: 15 }), [s])
  // With the backend there are two sources: the trail the backend writes (default) and the development log of the areas that are still mock.
  const backend = a.repos.backendAudit; const live = !!backend && s.src !== 'dev'; const repo = live ? backend! : a.repos.audit
  const { data, state, reload } = useLoad(() => repo.list(filter), [repo, filter])
  const actions = useMemo(() => repo.actions(), [repo, data]); const targets = useMemo(() => repo.targetTypes(), [repo, data]) // eslint-disable-line react-hooks/exhaustive-deps
  const columns: Array<Column<AuditEvent>> = [
    { id: 'time', label: t('adm.audit.col.time', undefined, locale), render: (e) => fmtDateTime(e.at, locale) },
    { id: 'actor', label: t('adm.audit.col.actor', undefined, locale), primary: true, render: (e) => <Cell primary={e.actor} secondary={e.actorRole} /> },
    { id: 'action', label: t('adm.audit.col.action', undefined, locale), render: (e) => <span className="adm-code">{e.action}</span> },
    { id: 'target', label: t('adm.audit.col.target', undefined, locale), hideMobile: true, render: (e) => <Cell primary={e.targetRef} secondary={e.targetType} /> },
    { id: 'result', label: t('adm.audit.col.result', undefined, locale), render: (e) => <StatusPill status={e.result} prefix="adm.auditResult" dot /> },
    { id: 'desc', label: t('adm.audit.col.description', undefined, locale), hideMobile: true, render: (e) => <span dir="auto">{e.description}</span> },
  ]
  return (
    <div className="db-page" data-testid="adm-audit">
      <div className="db-page__head"><div><h1 className="db-page__title">{t('adm.audit.title', undefined, locale)}</h1><p className="db-page__lead">{t('adm.audit.lead', undefined, locale)}</p></div></div>
      {backend && <Tabs tabs={[{ id: 'backend', label: t('adm.audit.src.backend', undefined, locale) }, { id: 'dev', label: t('adm.audit.src.dev', undefined, locale) }]} value={live ? 'backend' : 'dev'} onChange={(v) => set({ ...A_DEFAULTS, src: v === 'dev' ? 'dev' : '' })} label={t('adm.audit.src.label', undefined, locale)} />}
      <Card>
        <Toolbar search={s.q} onSearch={(q) => set({ q, page: '1' })} placeholder={t(live ? 'adm.audit.searchBackend' : 'adm.audit.search', undefined, locale)} locale={locale}>
          <Select label={t('adm.audit.col.action', undefined, locale)} value={s.action} onChange={(action) => set({ action })} options={[{ value: 'all', label: t('adm.audit.action.all', undefined, locale) }, ...actions.map((x) => ({ value: x, label: x }))]} testId="filter-action" />
          <Select label={t('adm.audit.col.target', undefined, locale)} value={s.target} onChange={(target) => set({ target })} options={[{ value: 'all', label: t('adm.audit.target.all', undefined, locale) }, ...targets.map((x) => ({ value: x, label: x }))]} testId="filter-target" />
          {!live && <Select label={t('adm.audit.col.result', undefined, locale)} value={s.result} onChange={(result) => set({ result })} options={[{ value: 'all', label: t('adm.audit.result.all', undefined, locale) }, ...(['SUCCESS', 'DENIED', 'FAILED'] as const).map((x) => ({ value: x, label: t(`adm.auditResult.${x}`, undefined, locale) }))]} testId="filter-result" />}
          <label className="adm-select"><span className="db-sr-only">{t('adm.audit.from', undefined, locale)}</span><input type="date" className="db-input db-input--sm" value={s.from} onChange={(e) => set({ from: e.target.value })} aria-label={t('adm.audit.from', undefined, locale)} data-testid="filter-from" /></label>
          <label className="adm-select"><span className="db-sr-only">{t('adm.audit.to', undefined, locale)}</span><input type="date" className="db-input db-input--sm" value={s.to} onChange={(e) => set({ to: e.target.value })} aria-label={t('adm.audit.to', undefined, locale)} data-testid="filter-to" /></label>
        </Toolbar>
        <DataTable columns={columns} rows={data?.items ?? []} keyOf={(e) => e.id} state={state} total={data?.total ?? 0} page={filter.page!} pageSize={15} onPage={(page) => set({ page: String(page) })} empty={{ icon: 'audit', title: t('adm.audit.empty', undefined, locale) }} onRetry={() => { void reload() }} locale={locale} testId="audit-table" caption={t('adm.audit.title', undefined, locale)} onRowClick={setOpen} actions={(e) => <button type="button" className="db-btn db-btn--ghost db-btn--sm" onClick={() => setOpen(e)}>{t('adm.table.view', undefined, locale)}</button>} />
      </Card>
      <DevNote>{t(live ? 'adm.audit.backendNote' : backend ? 'adm.audit.devNote' : 'adm.audit.immutable', undefined, locale)}</DevNote>
      <Drawer open={!!open} onClose={() => setOpen(null)} title={t('adm.audit.detail', undefined, locale)}>{open && <div className="db-grid" style={{ gap: 14 }} data-testid="audit-drawer"><Details rows={[[t('adm.audit.col.time', undefined, locale), fmtDateTime(open.at, locale)], [t('adm.audit.col.actor', undefined, locale), `${open.actor} (${open.actorRole})`], [t('adm.audit.col.action', undefined, locale), open.action], [t('adm.audit.col.target', undefined, locale), `${open.targetType} · ${open.targetRef}`], [t('adm.audit.col.result', undefined, locale), <StatusPill key="r" status={open.result} prefix="adm.auditResult" dot />], open.requestId !== undefined ? [t('adm.audit.requestId', undefined, locale), <span key="rid" className="adm-code">{open.requestId ?? t('adm.audit.none', undefined, locale)}</span>] : [t('adm.audit.ip', undefined, locale), open.ip ?? t('adm.audit.none', undefined, locale)], [t('adm.audit.reason', undefined, locale), open.reason ?? t('adm.audit.none', undefined, locale)]]} /><p dir="auto">{open.description}</p><div className="db-form-row"><div><b>{t('adm.audit.before', undefined, locale)}</b><pre className="adm-json">{JSON.stringify(open.before, null, 2) ?? '—'}</pre></div><div><b>{t('adm.audit.after', undefined, locale)}</b><pre className="adm-json">{JSON.stringify(open.after, null, 2) ?? '—'}</pre></div></div><DevNote>{t('adm.audit.immutable', undefined, locale)}</DevNote></div>}</Drawer>
    </div>
  )
}

/* ------------------------------------------------------------------ Security dashboard */
export function SecurityPage() {
  const a = useAdmin(); const locale = a.locale; usePageTitle('adm.nav.security')
  const { data: sec, state, reload } = useLoad(() => a.repos.security.summary(), [a.repos])
  return (
    <div className="db-page" data-testid="adm-security">
      <div className="db-page__head"><div><h1 className="db-page__title">{t('adm.security.title', undefined, locale)}</h1><p className="db-page__lead">{t('adm.security.lead', undefined, locale)}</p></div></div>
      {state === 'loading' && <Skeleton rows={5} />}{state === 'error' && <ErrorState title={t('adm.error.loadTitle', undefined, locale)} onRetry={() => { void reload() }} locale={locale} />}
      {state === 'ready' && sec && <>
        <div className="adm-stats" data-testid="security-kpis"><Stat label={t('adm.security.kpi.failedLogins', undefined, locale)} value={sec.failedAdminLogins24h} tone={sec.failedAdminLogins24h > 0 ? 'amber' : undefined} /><Stat label={t('adm.security.kpi.suspicious', undefined, locale)} value={sec.suspiciousActivity} tone={sec.suspiciousActivity > 0 ? 'red' : undefined} /><Stat label={t('adm.security.kpi.locked', undefined, locale)} value={sec.lockedAccounts} tone={sec.lockedAccounts ? 'red' : undefined} /><Stat label={t('adm.security.kpi.highRisk', undefined, locale)} value={sec.highRiskActions24h} /><Stat label={t('adm.security.kpi.permChanges', undefined, locale)} value={sec.recentPermissionChanges} /><Stat label={t('adm.security.kpi.mfa', undefined, locale)} value={`${sec.mfaCoverage.enrolled}/${sec.mfaCoverage.total}`} tone={sec.mfaCoverage.enrolled === sec.mfaCoverage.total ? 'green' : 'amber'} /></div>
        <div className="db-grid db-grid--2">
          <Card title={t('adm.security.alerts', undefined, locale)} tone={sec.alerts.length ? 'warn' : undefined}>{sec.alerts.length === 0 ? <p className="db-muted">{t('adm.security.noAlerts', undefined, locale)}</p> : <ul className="db-list" data-testid="security-alerts">{sec.alerts.map((e) => <li key={e.id}><StatusPill status={e.severity} prefix="adm.security.sev" dot /> <span style={{ flex: 1 }}>{e.detail}</span><small className="db-muted">{fmtDateTime(e.at, locale)}</small></li>)}</ul>}</Card>
          <Card title={t('adm.security.kpi.mfa', undefined, locale)}><p className="db-kpi__value">{Math.round((sec.mfaCoverage.enrolled / Math.max(1, sec.mfaCoverage.total)) * 100)}%</p><p className="db-muted">{t('adm.security.mfaNote', { enrolled: sec.mfaCoverage.enrolled, total: sec.mfaCoverage.total }, locale)}</p><DevNote>{t('adm.users.mfaNote', undefined, locale)}</DevNote></Card>
        </div>
        <Card title={t('adm.security.events', undefined, locale)}><div className="db-table-wrap" tabIndex={0}><table className="db-table" data-testid="security-events"><caption className="db-sr-only">{t('adm.security.events', undefined, locale)}</caption><thead><tr><th scope="col">{t('adm.security.col.time', undefined, locale)}</th><th scope="col">{t('adm.security.col.kind', undefined, locale)}</th><th scope="col">{t('adm.security.col.severity', undefined, locale)}</th><th scope="col" className="adm-hide-mobile">{t('adm.security.col.actor', undefined, locale)}</th><th scope="col">{t('adm.security.col.detail', undefined, locale)}</th><th scope="col" className="adm-hide-mobile">{t('adm.security.col.ip', undefined, locale)}</th></tr></thead><tbody>{sec.events.map((e) => <tr key={e.id}><td>{fmtDateTime(e.at, locale)}</td><td>{t(`adm.security.kind.${e.kind}`, undefined, locale)}</td><td><StatusPill status={e.severity} prefix="adm.security.sev" dot /></td><td className="adm-hide-mobile">{e.actor ?? '—'}</td><td>{e.detail}</td><td className="adm-hide-mobile"><span className="adm-code">{e.ip ?? '—'}</span></td></tr>)}</tbody></table></div></Card>
      </>}
    </div>
  )
}
