/** Staff sign-in and account-security strings (both dashboards) — English source table, merged into the global bundle. */
export const staffStrings: Record<string, string> = {
  'staff.brand.restaurant': 'FoodOnTheGo for restaurants', 'staff.brand.admin': 'FoodOnTheGo administration',
  'staff.title.restaurant': 'Restaurant Dashboard', 'staff.title.admin': 'Platform Admin',
  'staff.lead.restaurant': 'Sign in with your restaurant staff account.', 'staff.lead.admin': 'Sign in with your FoodOnTheGo administrator account.',
  'staff.checking': 'Checking your session…', 'staff.unreachable': 'Cannot reach FoodOnTheGo right now. Check your connection and try again.', 'staff.tryAgain': 'Try again',
  'staff.sessionEnded': 'Your session has ended. Please sign in again.', 'staff.signedOut': 'You have been signed out.',
  'staff.mustEnrolContact': 'This account must set up multi-factor authentication before it can sign in. Please contact your administrator.',
  'staff.mustEnrolNow': 'Your account must use multi-factor authentication. Set it up now to finish signing in.',
  'staff.codeLead': 'Enter the 6-digit code from your authenticator app, or a recovery code.', 'staff.code': 'Verification code',
  'staff.email': 'E-mail', 'staff.password': 'Password', 'staff.signingIn': 'Signing in…', 'staff.verify': 'Verify and sign in', 'staff.signIn': 'Sign in',
  'staff.otherAccount': 'Use a different account', 'staff.forgot': 'Forgot your password?', 'staff.back': 'Back to FoodOnTheGo',

  'staff.err.generic': 'Something went wrong. Please try again.', 'staff.err.network': 'Cannot reach FoodOnTheGo right now. Check your connection and try again.',
  'staff.err.tooManyCodes': 'Too many incorrect codes. Please sign in again.', 'staff.err.rateWait': 'Too many attempts. Try again in {seconds} seconds.', 'staff.err.rate': 'Too many attempts. Please wait a moment and try again.',
  'staff.err.credentials': 'The e-mail or password is incorrect.', 'staff.err.notActive': 'This account cannot sign in. Please contact your administrator.',
  'staff.err.codeInvalid': 'That code is not correct.', 'staff.err.challengeGone': 'This sign-in attempt has expired. Please sign in again.',
  'staff.err.resetInvalid': 'This reset link is invalid or has expired. Request a new one.', 'staff.err.mfaAlready': 'Multi-factor authentication is already enabled.', 'staff.err.mfaSetupAgain': 'Start the setup again.',
  'staff.err.check': 'Please check what you entered.', 'staff.err.server': 'Something went wrong on our side. Please try again.',

  'staff.forgot.title': 'Forgot your password?', 'staff.forgot.enterEmail': 'Enter your e-mail address.',
  'staff.forgot.sent': 'If an account exists for this e-mail, a link to choose a new password has been sent. It is valid for a short time and works once.',
  'staff.forgot.lead': 'Enter the e-mail of your account. We will send a link to choose a new password.', 'staff.forgot.sending': 'Sending…', 'staff.forgot.send': 'Send reset link', 'staff.backToSignIn': 'Back to sign in',
  'staff.reset.title': 'Choose a new password', 'staff.pw.minError': 'Use at least {n} characters.', 'staff.pw.mismatch': 'The two passwords are not the same.',
  'staff.reset.done': 'Your password has been changed and every device has been signed out. Sign in with the new password.', 'staff.goSignIn': 'Go to sign in',
  'staff.reset.incomplete': 'This reset link is not complete. Open the link from the e-mail again, or request a new one.', 'staff.reset.requestNew': 'Request a new link',
  'staff.pw.new': 'New password', 'staff.pw.hint': 'At least {n} characters. A long phrase is better than a short complicated one.', 'staff.pw.repeat': 'Repeat the password', 'staff.saving': 'Saving…', 'staff.pw.change': 'Change password',

  'staff.accept.docTitle': 'Set your password · FoodOnTheGo Platform Admin', 'staff.accept.brand': 'FoodOnTheGo · Platform Admin', 'staff.accept.title': 'Set your password',
  'staff.accept.done': 'Your password is set. You can sign in now.',
  'staff.accept.incomplete': 'This invitation link is not complete. Open the link from your invitation e-mail again, or ask an administrator to send a new one.',
  'staff.accept.lead': 'Choose a password to activate your administrator account.', 'staff.accept.set': 'Set password',

  'staff.mfa.codesTitle': 'Save your recovery codes',
  'staff.mfa.codesLead': 'Multi-factor authentication is on. Each code below signs you in once if you lose your authenticator app.', 'staff.mfa.codesOnce': 'They are shown only now.', 'staff.mfa.codesKeep': 'Keep them somewhere safe — not in your e-mail.',
  'staff.mfa.codesLabel': 'Recovery codes', 'staff.mfa.copied': 'Copied', 'staff.mfa.copy': 'Copy codes', 'staff.mfa.saved': 'I have saved these codes', 'staff.continue': 'Continue',
  'staff.mfa.setupTitle': 'Set up multi-factor authentication',
  'staff.mfa.step1': 'Install an authenticator app (Google Authenticator, Microsoft Authenticator, Authy, 1Password …).', 'staff.mfa.step2': 'Scan this code with the app, or type the key by hand.', 'staff.mfa.step3': 'Enter the 6-digit code the app shows.',
  'staff.mfa.preparing': 'Preparing…', 'staff.mfa.qrAlt': 'QR code for your authenticator app', 'staff.mfa.qrFail': 'The QR code could not be drawn. Use the key below.', 'staff.mfa.key': 'Setup key',
  'staff.mfa.code6': '6-digit code', 'staff.checkingCode': 'Checking…', 'staff.mfa.turnOn': 'Turn on', 'staff.cancel': 'Cancel',

  'staff.sec.title': 'Account security', 'staff.sec.mock': 'Sign-in, multi-factor authentication and sessions are managed by the backend. This build runs on development fixtures and has no account to manage.',
  'staff.sec.mfa': 'Multi-factor authentication', 'staff.on': 'On', 'staff.off': 'Off', 'staff.sec.mfaOffNote': 'Multi-factor authentication is off.', 'staff.sec.mfaOnNote': 'Multi-factor authentication is on.',
  'staff.sec.mfaOnText': 'Signing in asks for a 6-digit code from your authenticator app, or a recovery code.', 'staff.sec.turnOff': 'Turn off',
  'staff.sec.mfaOffText': 'Add a second step to your sign-in: a code from an authenticator app on your phone. Strongly recommended for every account, and required for administrators before going live.', 'staff.sec.setUp': 'Set up',
  'staff.sec.disableLead': 'Turning this off makes your account easier to break into. Confirm with your password and a current code from your app.', 'staff.sec.currentPassword': 'Current password',
  'staff.sec.pwDifferent': 'The new password must be different from the current one.', 'staff.sec.pwMismatch': 'The two new passwords are not the same.', 'staff.sec.pwDone': 'Password changed. Your other devices have been signed out.',
  'staff.sec.pwMin': 'At least {n} characters.', 'staff.sec.pwRepeatNew': 'Repeat the new password',
  'staff.sec.devices': 'Signed-in devices', 'staff.loading': 'Loading…', 'staff.sec.col.device': 'Device', 'staff.sec.col.signedIn': 'Signed in', 'staff.sec.col.lastUsed': 'Last used', 'staff.sec.col.expires': 'Expires', 'staff.sec.col.actions': 'Actions',
  'staff.sec.unknown': 'Unknown', 'staff.sec.thisDevice': 'This device', 'staff.sec.signOut': 'Sign out', 'staff.sec.everywhere': 'Sign out everywhere',
  'staff.you': 'you',
  'staff.lang.title': 'Language', 'staff.lang.lead': 'The language of these screens and of the e-mails FoodOnTheGo sends you (password reset links and security notices). Messages that come from the server, such as some error texts, stay in English.',
  'staff.lang.saved': 'Saved.', 'staff.lang.label': 'Language', 'staff.lang.none': 'No preference — screens in English, e-mails in every language ({languages})',
}
