/** Hindi for the staff sign-in and account-security screens. Same keys as strings.ts (checked by a test). */
export const staffStringsHi: Record<string, string> = {
  'staff.brand.restaurant': 'रेस्टोरेंट के लिए FoodOnTheGo', 'staff.brand.admin': 'FoodOnTheGo एडमिनिस्ट्रेशन',
  'staff.title.restaurant': 'रेस्टोरेंट डैशबोर्ड', 'staff.title.admin': 'प्लेटफ़ॉर्म एडमिन',
  'staff.lead.restaurant': 'अपने रेस्टोरेंट स्टाफ़ खाते से साइन इन करें।', 'staff.lead.admin': 'अपने FoodOnTheGo एडमिनिस्ट्रेटर खाते से साइन इन करें।',
  'staff.checking': 'आपका सेशन जांचा जा रहा है…', 'staff.unreachable': 'अभी FoodOnTheGo से संपर्क नहीं हो पा रहा है। अपना कनेक्शन जांचें और फिर से कोशिश करें।', 'staff.tryAgain': 'फिर से कोशिश करें',
  'staff.sessionEnded': 'आपका सेशन समाप्त हो गया है। कृपया फिर से साइन इन करें।', 'staff.signedOut': 'आप साइन आउट हो गए हैं।',
  'staff.mustEnrolContact': 'साइन इन करने से पहले इस खाते में मल्टी-फ़ैक्टर ऑथेंटिकेशन सेट करना ज़रूरी है। कृपया अपने एडमिनिस्ट्रेटर से संपर्क करें।',
  'staff.mustEnrolNow': 'आपके खाते के लिए मल्टी-फ़ैक्टर ऑथेंटिकेशन ज़रूरी है। साइन इन पूरा करने के लिए इसे अभी सेट करें।',
  'staff.codeLead': 'अपने ऑथेंटिकेटर ऐप का 6 अंकों का कोड या कोई रिकवरी कोड डालें।', 'staff.code': 'वेरिफ़िकेशन कोड',
  'staff.email': 'ई-मेल', 'staff.password': 'पासवर्ड', 'staff.signingIn': 'साइन इन हो रहा है…', 'staff.verify': 'जांचें और साइन इन करें', 'staff.signIn': 'साइन इन करें',
  'staff.otherAccount': 'दूसरे खाते का इस्तेमाल करें', 'staff.forgot': 'पासवर्ड भूल गए?', 'staff.back': 'FoodOnTheGo पर वापस जाएं',

  'staff.err.generic': 'कुछ गड़बड़ हो गई। कृपया फिर से कोशिश करें।', 'staff.err.network': 'अभी FoodOnTheGo से संपर्क नहीं हो पा रहा है। अपना कनेक्शन जांचें और फिर से कोशिश करें।',
  'staff.err.tooManyCodes': 'बहुत बार गलत कोड डाला गया। कृपया फिर से साइन इन करें।', 'staff.err.rateWait': 'बहुत ज़्यादा कोशिशें हुईं। {seconds} सेकंड बाद फिर से कोशिश करें।', 'staff.err.rate': 'बहुत ज़्यादा कोशिशें हुईं। कृपया थोड़ी देर रुककर फिर से कोशिश करें।',
  'staff.err.credentials': 'ई-मेल या पासवर्ड गलत है।', 'staff.err.notActive': 'यह खाता साइन इन नहीं कर सकता। कृपया अपने एडमिनिस्ट्रेटर से संपर्क करें।',
  'staff.err.codeInvalid': 'यह कोड सही नहीं है।', 'staff.err.challengeGone': 'साइन इन की यह कोशिश समाप्त हो गई है। कृपया फिर से साइन इन करें।',
  'staff.err.resetInvalid': 'यह रीसेट लिंक अमान्य है या समाप्त हो चुका है। नया लिंक मंगवाएं।', 'staff.err.mfaAlready': 'मल्टी-फ़ैक्टर ऑथेंटिकेशन पहले से चालू है।', 'staff.err.mfaSetupAgain': 'सेटअप फिर से शुरू करें।',
  'staff.err.check': 'कृपया अपनी डाली हुई जानकारी जांचें।', 'staff.err.server': 'हमारी तरफ़ से कुछ गड़बड़ हो गई। कृपया फिर से कोशिश करें।',

  'staff.forgot.title': 'पासवर्ड भूल गए?', 'staff.forgot.enterEmail': 'अपना ई-मेल पता डालें।',
  'staff.forgot.sent': 'अगर इस ई-मेल से कोई खाता है, तो नया पासवर्ड चुनने का लिंक भेज दिया गया है। यह थोड़े समय के लिए मान्य है और केवल एक बार काम करता है।',
  'staff.forgot.lead': 'अपने खाते का ई-मेल डालें। हम नया पासवर्ड चुनने का लिंक भेजेंगे।', 'staff.forgot.sending': 'भेजा जा रहा है…', 'staff.forgot.send': 'रीसेट लिंक भेजें', 'staff.backToSignIn': 'साइन इन पर वापस जाएं',
  'staff.reset.title': 'नया पासवर्ड चुनें', 'staff.pw.minError': 'कम से कम {n} अक्षर इस्तेमाल करें।', 'staff.pw.mismatch': 'दोनों पासवर्ड एक जैसे नहीं हैं।',
  'staff.reset.done': 'आपका पासवर्ड बदल दिया गया है और हर डिवाइस से साइन आउट कर दिया गया है। नए पासवर्ड से साइन इन करें।', 'staff.goSignIn': 'साइन इन पर जाएं',
  'staff.reset.incomplete': 'यह रीसेट लिंक अधूरा है। ई-मेल का लिंक फिर से खोलें या नया लिंक मंगवाएं।', 'staff.reset.requestNew': 'नया लिंक मंगवाएं',
  'staff.pw.new': 'नया पासवर्ड', 'staff.pw.hint': 'कम से कम {n} अक्षर। छोटे और जटिल पासवर्ड से लंबा वाक्यांश बेहतर है।', 'staff.pw.repeat': 'पासवर्ड दोबारा डालें', 'staff.saving': 'सेव हो रहा है…', 'staff.pw.change': 'पासवर्ड बदलें',

  'staff.accept.docTitle': 'अपना पासवर्ड सेट करें · FoodOnTheGo प्लेटफ़ॉर्म एडमिन', 'staff.accept.brand': 'FoodOnTheGo · प्लेटफ़ॉर्म एडमिन', 'staff.accept.title': 'अपना पासवर्ड सेट करें',
  'staff.accept.done': 'आपका पासवर्ड सेट हो गया है। अब आप साइन इन कर सकते हैं।',
  'staff.accept.incomplete': 'यह आमंत्रण लिंक अधूरा है। आमंत्रण ई-मेल का लिंक फिर से खोलें या किसी एडमिनिस्ट्रेटर से नया लिंक भेजने को कहें।',
  'staff.accept.lead': 'अपना एडमिनिस्ट्रेटर खाता सक्रिय करने के लिए पासवर्ड चुनें।', 'staff.accept.set': 'पासवर्ड सेट करें',

  'staff.mfa.codesTitle': 'अपने रिकवरी कोड सेव करें',
  'staff.mfa.codesLead': 'मल्टी-फ़ैक्टर ऑथेंटिकेशन चालू है। अगर आपका ऑथेंटिकेटर ऐप खो जाए, तो नीचे का हर कोड एक बार साइन इन करने के काम आएगा।', 'staff.mfa.codesOnce': 'ये कोड केवल अभी दिखाए जा रहे हैं।', 'staff.mfa.codesKeep': 'इन्हें किसी सुरक्षित जगह पर रखें — अपने ई-मेल में नहीं।',
  'staff.mfa.codesLabel': 'रिकवरी कोड', 'staff.mfa.copied': 'कॉपी हो गया', 'staff.mfa.copy': 'कोड कॉपी करें', 'staff.mfa.saved': 'मैंने ये कोड सेव कर लिए हैं', 'staff.continue': 'जारी रखें',
  'staff.mfa.setupTitle': 'मल्टी-फ़ैक्टर ऑथेंटिकेशन सेट करें',
  'staff.mfa.step1': 'कोई ऑथेंटिकेटर ऐप इंस्टॉल करें (Google Authenticator, Microsoft Authenticator, Authy, 1Password …)।', 'staff.mfa.step2': 'ऐप से यह कोड स्कैन करें या की हाथ से टाइप करें।', 'staff.mfa.step3': 'ऐप में दिख रहा 6 अंकों का कोड डालें।',
  'staff.mfa.preparing': 'तैयार किया जा रहा है…', 'staff.mfa.qrAlt': 'आपके ऑथेंटिकेटर ऐप के लिए QR कोड', 'staff.mfa.qrFail': 'QR कोड नहीं बन सका। नीचे दी गई की का इस्तेमाल करें।', 'staff.mfa.key': 'सेटअप की',
  'staff.mfa.code6': '6 अंकों का कोड', 'staff.checkingCode': 'जांचा जा रहा है…', 'staff.mfa.turnOn': 'चालू करें', 'staff.cancel': 'रद्द करें',

  'staff.sec.title': 'खाते की सुरक्षा', 'staff.sec.mock': 'साइन इन, मल्टी-फ़ैक्टर ऑथेंटिकेशन और सेशन बैकएंड संभालता है। यह बिल्ड डेवलपमेंट फ़िक्स्चर पर चलता है और इसमें संभालने के लिए कोई खाता नहीं है।',
  'staff.sec.mfa': 'मल्टी-फ़ैक्टर ऑथेंटिकेशन', 'staff.on': 'चालू', 'staff.off': 'बंद', 'staff.sec.mfaOffNote': 'मल्टी-फ़ैक्टर ऑथेंटिकेशन बंद है।', 'staff.sec.mfaOnNote': 'मल्टी-फ़ैक्टर ऑथेंटिकेशन चालू है।',
  'staff.sec.mfaOnText': 'साइन इन करते समय आपके ऑथेंटिकेटर ऐप का 6 अंकों का कोड या कोई रिकवरी कोड मांगा जाता है।', 'staff.sec.turnOff': 'बंद करें',
  'staff.sec.mfaOffText': 'अपने साइन इन में दूसरा चरण जोड़ें: आपके फ़ोन के ऑथेंटिकेटर ऐप का कोड। हर खाते के लिए इसकी पुरज़ोर सलाह दी जाती है, और लाइव होने से पहले एडमिनिस्ट्रेटर के लिए यह ज़रूरी है।', 'staff.sec.setUp': 'सेट करें',
  'staff.sec.disableLead': 'इसे बंद करने से आपके खाते में सेंध लगाना आसान हो जाता है। अपने पासवर्ड और ऐप के मौजूदा कोड से पुष्टि करें।', 'staff.sec.currentPassword': 'मौजूदा पासवर्ड',
  'staff.sec.pwDifferent': 'नया पासवर्ड मौजूदा पासवर्ड से अलग होना चाहिए।', 'staff.sec.pwMismatch': 'दोनों नए पासवर्ड एक जैसे नहीं हैं।', 'staff.sec.pwDone': 'पासवर्ड बदल गया। आपके दूसरे डिवाइस साइन आउट कर दिए गए हैं।',
  'staff.sec.pwMin': 'कम से कम {n} अक्षर।', 'staff.sec.pwRepeatNew': 'नया पासवर्ड दोबारा डालें',
  'staff.sec.devices': 'साइन इन किए हुए डिवाइस', 'staff.loading': 'लोड हो रहा है…', 'staff.sec.col.device': 'डिवाइस', 'staff.sec.col.signedIn': 'साइन इन किया', 'staff.sec.col.lastUsed': 'आख़िरी इस्तेमाल', 'staff.sec.col.expires': 'समाप्ति', 'staff.sec.col.actions': 'कार्रवाई',
  'staff.sec.unknown': 'अज्ञात', 'staff.sec.thisDevice': 'यह डिवाइस', 'staff.sec.signOut': 'साइन आउट करें', 'staff.sec.everywhere': 'हर जगह से साइन आउट करें',
  'staff.you': 'आप',
  'staff.lang.title': 'भाषा', 'staff.lang.lead': 'इन स्क्रीन की और FoodOnTheGo से आपको मिलने वाले ई-मेल (पासवर्ड रीसेट लिंक और सुरक्षा सूचनाएं) की भाषा। सर्वर से आने वाले संदेश, जैसे कुछ त्रुटि संदेश, अंग्रेज़ी में ही रहेंगे।',
  'staff.lang.saved': 'सेव हो गया।', 'staff.lang.label': 'भाषा', 'staff.lang.none': 'कोई पसंद नहीं — स्क्रीन अंग्रेज़ी में, ई-मेल हर भाषा में ({languages})',
}
