<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\Market;
use App\Models\MarketRegion;
use App\Models\RouteCorridor;
use App\Models\ServiceArea;
use App\Services\Market\MarketContext;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * DEVELOPMENT FIXTURES — local and testing only, never production. A city, area or corridor listed here
 * does NOT mean FoodOnTheGo operates there: the statuses are deliberately mixed so every availability
 * outcome can be exercised. They mirror the fixtures the clients used before this module.
 *
 * Service areas are circles (32-gon polygons generated by PostGIS around a centre) and corridor centrelines
 * are straight lines between the city centres — stand-ins for real surveyed boundaries and road geometry.
 * Existing rows are left untouched, so administrative changes made locally survive a re-seed.
 */
class LocalGeographyFixtureSeeder extends Seeder
{
    private const REGION_STATUS = [
        'IN-UP' => 'ACTIVE', 'IN-DL' => 'ACTIVE', 'IN-HR' => 'ACTIVE', 'IN-PB' => 'PILOT', 'IN-CH' => 'PILOT', 'IN-RJ' => 'ACTIVE', 'IN-GJ' => 'ACTIVE',
        'IN-WB' => 'DISABLED', 'IN-JK' => 'DISABLED',
    ];

    /** slug => [name, region, lat, lng, status, launch stage, launched, aliases] */
    private const CITIES = [
        'noida' => ['Noida', 'IN-UP', 28.5355, 77.391, 'ACTIVE', 'Launched', '2026-09-01', []],
        'delhi' => ['Delhi', 'IN-DL', 28.6139, 77.209, 'ACTIVE', 'Launched', '2026-09-01', ['New Delhi']],
        'gurugram' => ['Gurugram', 'IN-HR', 28.4595, 77.0266, 'PILOT', 'Pilot', null, ['Gurgaon']],
        'karnal' => ['Karnal', 'IN-HR', 29.6857, 76.9905, 'PILOT', 'Highway pilot', null, []],
        'ambala' => ['Ambala', 'IN-HR', 30.3782, 76.7767, 'ACTIVE', 'Launched', '2026-09-08', []],
        'chandigarh' => ['Chandigarh', 'IN-CH', 30.7333, 76.7794, 'PILOT', 'Pilot', null, []],
        'rupnagar' => ['Rupnagar', 'IN-PB', 30.9685, 76.5265, 'ACTIVE', 'Launched', '2026-09-15', ['Ropar']],
        'hoshiarpur' => ['Hoshiarpur', 'IN-PB', 31.5273, 75.9115, 'PILOT', 'Pilot', null, []],
        'pathankot' => ['Pathankot', 'IN-PB', 32.2643, 75.6421, 'PILOT', 'Pilot', null, []],
        'ludhiana' => ['Ludhiana', 'IN-PB', 30.901, 75.8573, 'PLANNED', 'Planned', null, []],
        'jaipur' => ['Jaipur', 'IN-RJ', 26.9124, 75.7873, 'ACTIVE', 'Launched', '2026-09-10', []],
        'udaipur' => ['Udaipur', 'IN-RJ', 24.5854, 73.7125, 'PLANNED', 'Planned', null, []],
        'ahmedabad' => ['Ahmedabad', 'IN-GJ', 23.0225, 72.5714, 'ACTIVE', 'Launched', '2026-09-12', []],
        'vadodara' => ['Vadodara', 'IN-GJ', 22.3072, 73.1812, 'ACTIVE', 'Launched', '2026-09-12', []],
        'surat' => ['Surat', 'IN-GJ', 21.1702, 72.8311, 'ACTIVE', 'Launched', '2026-09-18', []],
        'vapi' => ['Vapi', 'IN-GJ', 20.3893, 72.9106, 'PAUSED', 'Paused — restaurant onboarding', null, []],
        'mumbai' => ['Mumbai', 'IN-MH', 19.076, 72.8777, 'PLANNED', 'Planned', null, ['Bombay']],
        'pune' => ['Pune', 'IN-MH', 18.5204, 73.8567, 'PLANNED', 'Planned', null, []],
        'bengaluru' => ['Bengaluru', 'IN-KA', 12.9716, 77.5946, 'PLANNED', 'Planned', null, ['Bangalore']],
        'hyderabad' => ['Hyderabad', 'IN-TS', 17.385, 78.4867, 'PLANNED', 'Planned', null, []],
        'chennai' => ['Chennai', 'IN-TN', 13.0827, 80.2707, 'PLANNED', 'Planned', null, []],
        'panaji' => ['Panaji', 'IN-GA', 15.4909, 73.8278, 'PLANNED', 'Planned', null, []],
        'kolkata' => ['Kolkata', 'IN-WB', 22.5726, 88.3639, 'UNAVAILABLE', 'Not planned', null, []],
    ];

    /**
     * slug => [name, city, lat, lng, radius km, status, launch stage].
     * An area in a pilot city is ACTIVE here: "pilot" is the city's state, the area itself is live.
     */
    private const SERVICE_AREAS = [
        'noida-62' => ['Noida · Sector 62 & NH24', 'noida', 28.622, 77.372, 6, 'ACTIVE', 'Launched'],
        'noida-expressway' => ['Noida · Expressway / Sector 18', 'noida', 28.57, 77.324, 5, 'ACTIVE', 'Launched'],
        'delhi-central' => ['Delhi · Central', 'delhi', 28.6139, 77.209, 12, 'ACTIVE', 'Launched — restaurant onboarding'],
        'gurugram-cyber' => ['Gurugram · Cyber City / NH48', 'gurugram', 28.4595, 77.0266, 8, 'ACTIVE', 'Pilot'],
        'karnal-nh44' => ['Karnal · NH44', 'karnal', 29.6857, 76.9905, 8, 'ACTIVE', 'Highway pilot'],
        'ambala-nh44' => ['Ambala · Cantt / NH44', 'ambala', 30.3782, 76.7767, 10, 'ACTIVE', 'Launched'],
        'chandigarh-tricity' => ['Chandigarh · Tricity', 'chandigarh', 30.7333, 76.7794, 12, 'ACTIVE', 'Pilot'],
        'rupnagar-nh205' => ['Rupnagar · NH205', 'rupnagar', 30.9685, 76.5265, 8, 'ACTIVE', 'Launched'],
        'hoshiarpur' => ['Hoshiarpur · Town', 'hoshiarpur', 31.5273, 75.9115, 8, 'ACTIVE', 'Pilot'],
        'pathankot' => ['Pathankot · NH44', 'pathankot', 32.2643, 75.6421, 8, 'ACTIVE', 'Pilot'],
        'jaipur-mi-road' => ['Jaipur · MI Road / NH48', 'jaipur', 26.9124, 75.7873, 12, 'ACTIVE', 'Launched'],
        'ahmedabad-sg' => ['Ahmedabad · SG Highway', 'ahmedabad', 23.0225, 72.5714, 12, 'ACTIVE', 'Launched'],
        'vadodara-ne1' => ['Vadodara · NE1 Expressway', 'vadodara', 22.3072, 73.1812, 10, 'ACTIVE', 'Launched'],
        'surat-nh48' => ['Surat · NH48', 'surat', 21.1702, 72.8311, 10, 'ACTIVE', 'Launched'],
        'vapi-nh48' => ['Vapi · NH48', 'vapi', 20.3893, 72.9106, 8, 'PAUSED', 'Paused'],
    ];

    /** slug => [name, origin, destination, via, highway, status] */
    private const CORRIDORS = [
        'delhi-chandigarh' => ['Delhi NCR → Chandigarh', 'delhi', 'chandigarh', ['karnal', 'ambala'], 'NH44', 'ACTIVE'],
        'chandigarh-pathankot' => ['Chandigarh → Pathankot', 'chandigarh', 'pathankot', ['rupnagar', 'hoshiarpur'], 'NH205 / NH503A', 'TESTING'],
        'delhi-jaipur' => ['Delhi NCR → Jaipur', 'delhi', 'jaipur', ['gurugram'], 'NH48', 'ACTIVE'],
        'ahmedabad-surat' => ['Ahmedabad → Surat', 'ahmedabad', 'surat', ['vadodara'], 'NE1 / NH48', 'ACTIVE'],
        'surat-vapi' => ['Surat → Vapi', 'surat', 'vapi', [], 'NH48', 'PAUSED'],
        'jaipur-udaipur' => ['Jaipur → Udaipur', 'jaipur', 'udaipur', [], 'NH48', 'PLANNED'],
        'mumbai-pune' => ['Mumbai → Pune', 'mumbai', 'pune', [], 'Expressway', 'PLANNED'],
    ];

    public function run(MarketContext $markets): void
    {
        $india = Market::query()->where('country_code', 'IN')->first();
        if ($india === null) {
            return;
        }

        // Fixture statuses apply only to regions nobody has touched yet (still version 1 and PLANNED).
        foreach (self::REGION_STATUS as $code => $status) {
            MarketRegion::query()->where('market_id', $india->id)->where('code', $code)->where('status', 'PLANNED')->where('version', 1)->update(['status' => $status]);
        }
        $regions = MarketRegion::query()->where('market_id', $india->id)->pluck('id', 'code');

        foreach (self::CITIES as $slug => [$name, $region, $lat, $lng, $status, $stage, $launched, $aliases]) {
            if (City::query()->where('cities.market_id', $india->id)->where('cities.slug', $slug)->exists()) {
                continue;
            }
            (new City)->forceFill([
                'market_id' => $india->id, 'region_id' => $regions[$region], 'name' => $name, 'slug' => $slug, 'aliases' => $aliases,
                'timezone' => 'Asia/Kolkata', 'status' => $status, 'launch_stage' => $stage, 'launched_at' => $launched,
            ])->insertWithSpatial(['center' => City::centerExpression($lat, $lng)]);
        }
        $cities = City::query()->where('cities.market_id', $india->id)->get()->keyBy('slug');

        foreach (self::SERVICE_AREAS as $slug => [$name, $city, $lat, $lng, $radiusKm, $status, $stage]) {
            if (ServiceArea::query()->where('service_areas.market_id', $india->id)->where('service_areas.slug', $slug)->exists()) {
                continue;
            }
            (new ServiceArea)->forceFill([
                'market_id' => $india->id, 'city_id' => $cities[$city]->id, 'name' => $name, 'slug' => $slug, 'status' => $status, 'launch_stage' => $stage,
            ])->insertWithSpatial(['geometry' => [
                "ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(?, ?), 4326)::geography, ?, 'quad_segs=8')::geometry)", [$lng, $lat, $radiusKm * 1000],
            ]]);
        }

        foreach (self::CORRIDORS as $slug => [$name, $origin, $destination, $via, $highway, $status]) {
            if (RouteCorridor::query()->where('route_corridors.market_id', $india->id)->where('route_corridors.slug', $slug)->exists()) {
                continue;
            }
            $line = ['type' => 'LineString', 'coordinates' => array_map(fn (string $c): array => [$cities[$c]->longitude, $cities[$c]->latitude], [$origin, ...$via, $destination])];

            (new RouteCorridor)->forceFill([
                'market_id' => $india->id, 'origin_city_id' => $cities[$origin]->id, 'destination_city_id' => $cities[$destination]->id,
                'via_city_ids' => array_map(fn (string $c): string => $cities[$c]->public_id, $via),
                'name' => $name, 'slug' => $slug, 'highway' => $highway, 'status' => $status, 'corridor_width_meters' => 5000,
            ])->insertWithSpatial(['centerline' => RouteCorridor::centerlineExpression((string) json_encode($line))]);
        }

        DB::statement('analyze service_areas');
        $markets->flush();
    }
}
