/** Restaurant Dashboard strings — Hindi. Same keys as the English table (checked by a test). Machine-assisted translation: wording to be reviewed by a native speaker before go-live. */
export const dashStringsHi: Record<string, string> = {
  'dash.chart.label': 'लेबल',
  'dash.chart.value': 'मान',
  'dash.brand': 'रेस्टोरेंट डैशबोर्ड',
  'dash.skip': 'सीधे सामग्री पर जाएं',
  'dash.pending': 'लंबित',
  'dash.nav.label': 'डैशबोर्ड नेविगेशन',
  'dash.nav.overview': 'ओवरव्यू',
  'dash.nav.orders': 'ऑर्डर',
  'dash.nav.pickup': 'पिकअप सत्यापन',
  'dash.nav.menu': 'मेन्यू',
  'dash.nav.profile': 'रेस्टोरेंट प्रोफ़ाइल',
  'dash.nav.hours': 'खुलने का समय',
  'dash.nav.pickupSettings': 'पिकअप सेटिंग्स',
  'dash.nav.reviews': 'समीक्षाएं',
  'dash.nav.staff': 'स्टाफ़',
  'dash.nav.analytics': 'एनालिटिक्स',
  'dash.nav.notifications': 'सूचनाएं',
  'dash.nav.settings': 'सेटिंग्स',
  'dash.nav.help': 'मदद',
  'dash.nav.more': 'और',
  'dash.nav.collapse': 'नेविगेशन छोटा करें',
  'dash.nav.open': 'नेविगेशन खोलें',
  'dash.header.switchLocation': 'लोकेशन बदलें',
  'dash.header.locationsRestricted': '{n} और लोकेशन आपकी पहुंच से बाहर हैं',
  'dash.header.accepting': 'ऑर्डर ले रहे हैं',
  'dash.header.notAccepting': 'ऑर्डर नहीं ले रहे हैं',
  'dash.header.acceptingToggle': 'इस लोकेशन पर FoodOnTheGo ऑर्डर लें',
  'dash.header.notifications': 'सूचनाएं, {n} बिना पढ़ी',
  'dash.header.profileMenu': 'स्टाफ़ मेन्यू',
  'dash.header.switchStaff': 'स्टाफ़ बदलें (डेवलपमेंट)',
  'dash.header.exit': 'डैशबोर्ड से बाहर निकलें',
  'dash.role.owner': 'मालिक',
  'dash.role.manager': 'मैनेजर',
  'dash.role.order_staff': 'ऑर्डर स्टाफ़',
  'dash.role.menu_manager': 'मेन्यू मैनेजर',
  'dash.role.viewer': 'दर्शक',
  'dash.error.loadTitle': 'डैशबोर्ड लोड नहीं हो सका',
  'dash.error.loadText': 'एक अस्थायी समस्या के कारण यह डेटा लोड नहीं हो सका। कृपया फिर से कोशिश करें।',
  'dash.error.noLocationTitle': 'कोई लोकेशन उपलब्ध नहीं',
  'dash.error.noLocationText': 'आपके स्टाफ़ खाते के पास किसी लोकेशन की पहुंच नहीं है। पहुंच पाने के लिए मालिक या मैनेजर से कहें।',
  'dash.error.permissionTitle': 'अनुमति नहीं है',
  'dash.error.permissionText': 'आपकी भूमिका ({role}) में यह हिस्सा शामिल नहीं है। पहुंच चाहिए तो मालिक या मैनेजर से कहें।',
  'dash.action.retry': 'फिर से कोशिश करें',
  'dash.action.cancel': 'रद्द करें',
  'dash.action.close': 'बंद करें',
  'dash.action.save': 'सेव करें',
  'dash.action.saveChanges': 'बदलाव सेव करें',
  'dash.action.saving': 'सेव हो रहा है…',
  'dash.action.edit': 'संपादित करें',
  'dash.action.remove': 'हटाएं',
  'dash.action.add': 'जोड़ें',
  'dash.action.more': 'और कार्रवाई:',
  'dash.action.duplicate': 'कॉपी बनाएं',
  'dash.action.archive': 'आर्काइव करें',
  'dash.action.moveUp': 'ऊपर ले जाएं',
  'dash.action.moveDown': 'नीचे ले जाएं',
  'dash.action.clearSearch': 'खोज साफ़ करें',
  'dash.action.loadMore': 'और लोड करें ({total} में से {shown})',
  'dash.units.minutes': '{n} मिनट',
  'dash.units.items': '{n} आइटम',
  'dash.units.orders': '{n} ऑर्डर',
  'dash.status.PAYMENT_PENDING': 'भुगतान लंबित',
  'dash.status.CONFIRMED': 'नया',
  'dash.status.AWAITING_RESTAURANT_ACCEPTANCE': 'नया',
  'dash.status.ACCEPTED': 'स्वीकार किया गया',
  'dash.status.PREPARING': 'तैयार हो रहा है',
  'dash.status.READY_FOR_PICKUP': 'तैयार',
  'dash.status.PICKUP_VERIFICATION': 'पिकअप सत्यापन जारी',
  'dash.status.PICKED_UP': 'पिकअप हो गया',
  'dash.status.COMPLETED': 'पूरा हुआ',
  'dash.status.CANCELLED': 'रद्द',
  'dash.status.REJECTED': 'अस्वीकृत',
  'dash.status.REFUND_PENDING': 'रिफ़ंड लंबित',
  'dash.status.REFUNDED': 'रिफ़ंड हो गया',
  'dash.availability.available': 'उपलब्ध',
  'dash.availability.sold_out': 'स्टॉक में नहीं',
  'dash.availability.temporarily_unavailable': 'अभी अनुपलब्ध',
  'dash.availability.unavailable': 'अनुपलब्ध',
  'dash.availability.inactive': 'आर्काइव किया गया',
  'dash.onboarding.DRAFT': 'ड्राफ़्ट',
  'dash.onboarding.SUBMITTED': 'सबमिट किया गया',
  'dash.onboarding.UNDER_REVIEW': 'जांच जारी',
  'dash.onboarding.APPROVED': 'स्वीकृत',
  'dash.onboarding.REJECTED': 'अस्वीकृत',
  'dash.onboarding.SUSPENDED': 'निलंबित',
  'dash.overview.title': 'ओवरव्यू',
  'dash.overview.lead': 'आज {restaurant} में क्या चल रहा है, यहां देखें।',
  'dash.overview.today': 'आज',
  'dash.overview.revenue': 'आय का सारांश',
  'dash.overview.revenueSub': 'आज की आय {currency} में',
  'dash.overview.revenueNote': 'डेवलपमेंट के आंकड़े — सेटलमेंट डेटा बैकएंड के साथ आएगा।',
  'dash.overview.revenueByHour': 'घंटे के अनुसार आय',
  'dash.overview.viewItems': 'आइटम देखें',
  'dash.overview.recentOrders': 'हाल के ऑर्डर',
  'dash.overview.viewAll': 'सभी ऑर्डर देखें',
  'dash.overview.topItems': 'आज के टॉप आइटम',
  'dash.overview.menuAnalytics': 'मेन्यू एनालिटिक्स देखें',
  'dash.kpi.ordersToday': 'आज के ऑर्डर',
  'dash.kpi.preparing': 'तैयार हो रहे हैं',
  'dash.kpi.ready': 'पिकअप के लिए तैयार',
  'dash.kpi.completed': 'पूरे हुए',
  'dash.kpi.avgPrep': 'औसत तैयारी समय',
  'dash.kpi.avgRating': 'औसत रेटिंग',
  'dash.kpi.unavailable': 'अनुपलब्ध आइटम',
  'dash.orders.title': 'ऑर्डर',
  'dash.orders.lead': 'इस लोकेशन के पिकअप ऑर्डर स्वीकार करें, तैयार करें और ग्राहक को सौंपें।',
  'dash.orders.tabs': 'ऑर्डर के चरण',
  'dash.orders.tab.new': 'नए',
  'dash.orders.tab.preparing': 'तैयार हो रहे हैं',
  'dash.orders.tab.ready': 'तैयार',
  'dash.orders.tab.completed': 'पूरे हुए',
  'dash.orders.tab.cancelled': 'रद्द',
  'dash.orders.search': 'ऑर्डर खोजें',
  'dash.orders.searchPlaceholder': 'ऑर्डर नंबर या ग्राहक के नाम से खोजें…',
  'dash.orders.filterDate': 'दिखाएं',
  'dash.orders.allDates': 'सभी तारीखें',
  'dash.orders.col.number': 'ऑर्डर #',
  'dash.orders.col.customer': 'ग्राहक',
  'dash.orders.col.items': 'आइटम',
  'dash.orders.col.pickup': 'पिकअप का समय',
  'dash.orders.col.status': 'स्थिति',
  'dash.orders.col.actions': 'कार्रवाई',
  'dash.orders.customerAnon': 'ग्राहक',
  'dash.orders.placed': '{time} ऑर्डर किया गया',
  'dash.orders.pickupTime': 'पिकअप का समय',
  'dash.orders.newEta': 'नया ETA {time}',
  'dash.orders.delayed': 'देरी से',
  'dash.orders.accept': 'स्वीकार करें',
  'dash.orders.reject': 'अस्वीकार करें',
  'dash.orders.markReady': 'तैयार मार्क करें',
  'dash.orders.reportDelay': 'देरी बताएं',
  'dash.orders.verifyPickup': 'पिकअप सत्यापित करें',
  'dash.orders.view': 'देखें',
  'dash.orders.actionFailed': 'अपडेट लागू नहीं हो सका। रीफ़्रेश करके फिर से कोशिश करें।',
  'dash.orders.updated': 'ऑर्डर अपडेट हो गया',
  'dash.orders.rejectTitle': 'ऑर्डर {n} अस्वीकार करें?',
  'dash.orders.rejectText': 'ग्राहक को सूचना दी जाएगी और रिफ़ंड नीति के अनुसार रिफ़ंड किया जाएगा। एक कारण चुनें।',
  'dash.orders.rejectConfirm': 'ऑर्डर अस्वीकार करें',
  'dash.orders.rejectReason': 'कारण',
  'dash.orders.rejectReason.item_unavailable': 'आइटम अनुपलब्ध',
  'dash.orders.rejectReason.kitchen_capacity': 'किचन की क्षमता',
  'dash.orders.rejectReason.closing': 'बंद हो रहा है',
  'dash.orders.rejectReason.unable_to_prepare': 'तैयार नहीं कर सकते',
  'dash.orders.rejectReason.other': 'अन्य',
  'dash.orders.internalNote': 'आंतरिक नोट (वैकल्पिक)',
  'dash.orders.internalNoteHint': 'सिर्फ़ आपकी टीम को दिखता है — ग्राहक को कभी नहीं भेजा जाता।',
  'dash.orders.rejectCustomerSees': 'ग्राहक को दिखेगा: "{reason}"',
  'dash.orders.delayTitle': '{n} के लिए देरी बताएं',
  'dash.orders.delayConfirm': 'ETA अपडेट करें',
  'dash.orders.delayBy': 'कितनी देरी',
  'dash.orders.delayReason': 'कारण',
  'dash.orders.delayReason.high_demand': 'ज़्यादा मांग',
  'dash.orders.delayReason.taking_longer': 'उम्मीद से ज़्यादा समय लग रहा है',
  'dash.orders.delayReason.capacity': 'किचन की क्षमता',
  'dash.orders.delayReason.other': 'अन्य',
  'dash.orders.delayCustomerSees': 'ग्राहक को सिर्फ़ तैयार होने का नया समय और ग्राहक को बताने लायक कारण दिखता है।',
  'dash.orders.emptyTitle': 'अभी कोई ऑर्डर नहीं',
  'dash.orders.emptyText': 'ग्राहक के ऑर्डर देते ही नए पिकअप ऑर्डर यहां दिखेंगे।',
  'dash.orders.emptySearch': 'आपकी खोज से कुछ भी मेल नहीं खाता।',
  'dash.orders.empty.new': 'कोई नया ऑर्डर नहीं',
  'dash.orders.empty.preparing': 'कुछ भी तैयार नहीं हो रहा',
  'dash.orders.empty.ready': 'कोई ऑर्डर पिकअप के इंतज़ार में नहीं',
  'dash.orders.empty.completed': 'इस अवधि में कोई पूरा हुआ ऑर्डर नहीं',
  'dash.orders.empty.cancelled': 'कोई रद्द या अस्वीकृत ऑर्डर नहीं',
  'dash.orders.errorTitle': 'ऑर्डर लोड नहीं हो सके',
  'dash.orders.detailsTitle': 'ऑर्डर',
  'dash.orders.notFound': 'ऑर्डर नहीं मिला',
  'dash.orders.notFoundText': 'यह ऑर्डर चुनी गई लोकेशन का नहीं है।',
  'dash.orders.payment': 'भुगतान',
  'dash.orders.pickupVerification': 'पिकअप',
  'dash.orders.privacyNote': 'सिर्फ़ वही जानकारी दिखाई जाती है जो ऑर्डर पूरा करने के लिए ज़रूरी है।',
  'dash.orders.orderNote': 'ऑर्डर नोट',
  'dash.orders.subtotal': 'उप-योग',
  'dash.orders.discount': 'छूट',
  'dash.orders.total': 'कुल',
  'dash.orders.timeline': 'टाइमलाइन',
  'dash.orders.paymentSafe': '{method} से भुगतान किया गया · प्रोवाइडर रेफ़रेंस {ref}। कार्ड और खाते का विवरण कभी नहीं दिखाया जाता।',
  'dash.event.ORDER_CREATED': 'ऑर्डर दिया गया',
  'dash.event.PAYMENT_VERIFIED': 'भुगतान की पुष्टि हुई',
  'dash.event.ORDER_CONFIRMED': 'ऑर्डर की पुष्टि हुई',
  'dash.event.SENT_TO_RESTAURANT': 'रेस्टोरेंट को भेजा गया',
  'dash.event.RESTAURANT_ACCEPTED': 'रेस्टोरेंट ने स्वीकार किया',
  'dash.event.RESTAURANT_REJECTED': 'रेस्टोरेंट ने अस्वीकार किया',
  'dash.event.PREPARING': 'तैयार हो रहा है',
  'dash.event.DELAYED': 'देरी बताई गई',
  'dash.event.ETA_UPDATED': 'ETA अपडेट हुआ',
  'dash.event.READY_FOR_PICKUP': 'पिकअप के लिए तैयार',
  'dash.event.PICKUP_VERIFICATION': 'पिकअप कोड सत्यापित हुआ',
  'dash.event.PICKED_UP': 'पिकअप हो गया',
  'dash.event.COMPLETED': 'पूरा हुआ',
  'dash.event.CANCELLED': 'रद्द',
  'dash.event.REFUND_UPDATED': 'रिफ़ंड अपडेट हुआ',
  'dash.actor.customer': 'ग्राहक',
  'dash.actor.system': 'सिस्टम',
  'dash.actor.restaurant': 'रेस्टोरेंट',
  'dash.pickup.title': 'पिकअप सत्यापन',
  'dash.pickup.lead': '{restaurant} पर ऑर्डर सौंपने के लिए ग्राहक का QR कोड स्कैन करें या पिकअप कोड डालें।',
  'dash.pickup.readyOrders': 'तैयार ऑर्डर',
  'dash.pickup.orderHint': '{n} का पिकअप सत्यापित हो रहा है — ग्राहक से उनका कोड पूछें।',
  'dash.pickup.modes': 'सत्यापन का तरीका',
  'dash.pickup.scan': 'QR कोड स्कैन करें',
  'dash.pickup.enterCode': 'कोड डालें',
  'dash.pickup.scannerAria': 'QR स्कैनर प्रीव्यू क्षेत्र (कैमरा इंटीग्रेशन लंबित)',
  'dash.pickup.scannerTitle': 'ग्राहक का QR कोड स्कैन करें',
  'dash.pickup.scannerText': 'QR कोड को फ़्रेम के अंदर रखें।',
  'dash.pickup.scannerPending': 'कैमरा / QR स्कैनर इंटीग्रेशन = लंबित — स्कैनिंग सिम्युलेट नहीं की जाती।',
  'dash.pickup.useCode': 'इसके बजाय कोड डालें',
  'dash.pickup.codeLabel': 'पिकअप कोड',
  'dash.pickup.codeHint': 'ग्राहक के ऑर्डर कन्फ़र्मेशन पर दिखाए गए 6 अक्षर।',
  'dash.pickup.verify': 'पिकअप सत्यापित करें',
  'dash.pickup.verifying': 'सत्यापित हो रहा है…',
  'dash.pickup.resultTitle': 'परिणाम',
  'dash.pickup.resultEmpty': 'सत्यापन के नतीजे यहां दिखेंगे।',
  'dash.pickup.success': 'पिकअप सत्यापित',
  'dash.pickup.successText': '{customer} का ऑर्डर {n} पिकअप हो गया और पूरा हुआ के रूप में दर्ज है।',
  'dash.pickup.lastCode': 'दर्ज किया गया कोड: {code}',
  'dash.pickup.fail.invalid': 'अमान्य कोड',
  'dash.pickup.failText.invalid': 'यह कोड किसी पिकअप ऑर्डर से मेल नहीं खाता। ग्राहक से अपना कन्फ़र्मेशन जांचने को कहें।',
  'dash.pickup.fail.expired': 'कोड की समय-सीमा खत्म',
  'dash.pickup.failText.expired': 'यह पिकअप कोड अब मान्य नहीं है। ऑर्डर सौंपने के लिए सहायता से संपर्क करें।',
  'dash.pickup.fail.wrong_location': 'गलत लोकेशन',
  'dash.pickup.failText.wrong_location': 'यह कोड किसी दूसरे रेस्टोरेंट या लोकेशन के ऑर्डर का है।',
  'dash.pickup.fail.already_used': 'पहले ही इस्तेमाल हो चुका',
  'dash.pickup.failText.already_used': 'यह ऑर्डर पहले ही सौंपा जा चुका है। दोबारा स्कैन करने से दूसरा पिकअप नहीं बनता।',
  'dash.pickup.fail.not_ready': 'ऑर्डर तैयार नहीं',
  'dash.pickup.failText.not_ready': 'पिकअप सत्यापित करने से पहले ऑर्डर को तैयार के रूप में चिह्नित करें।',
  'dash.pickup.fail.permission': 'अनुमति नहीं है',
  'dash.pickup.failText.permission': 'आपकी भूमिका पिकअप सत्यापित नहीं कर सकती।',
  'dash.pickup.backendNote': 'केवल डेवलपमेंट सत्यापन। बैकएंड ऑर्डर, रेस्टोरेंट, लोकेशन, स्थिति, कोड, इस्तेमाल की स्थिति और स्टाफ़ की अनुमति को एटॉमिक और आइडेम्पोटेंट तरीके से जांचेगा।',
  'dash.menu.title': 'मेन्यू',
  'dash.menu.lead': 'इस लोकेशन की श्रेणियां, आइटम, वेरिएंट और मॉडिफ़ायर। कीमतें {currency} में।',
  'dash.menu.preview': 'ग्राहक व्यू का प्रीव्यू देखें',
  'dash.menu.addItem': 'आइटम जोड़ें',
  'dash.menu.editItem': 'आइटम संपादित करें',
  'dash.menu.tabs': 'मेन्यू के सेक्शन',
  'dash.menu.tab.categories': 'श्रेणियां',
  'dash.menu.tab.items': 'आइटम',
  'dash.menu.tab.modifiers': 'मॉडिफ़ायर',
  'dash.menu.search': 'मेन्यू आइटम खोजें',
  'dash.menu.searchPlaceholder': 'मेन्यू आइटम खोजें…',
  'dash.menu.allCategories': 'सभी श्रेणियां',
  'dash.menu.allStatus': 'सभी स्थितियां',
  'dash.menu.anyUnavailable': 'कोई भी अनुपलब्ध',
  'dash.menu.count': '{n} आइटम',
  'dash.menu.emptyTitle': 'कोई मेन्यू आइटम नहीं',
  'dash.menu.emptyText': 'अपना पहला आइटम जोड़ें या फ़िल्टर बदलें।',
  'dash.menu.errorTitle': 'मेन्यू लोड नहीं हो सका',
  'dash.menu.itemName': 'नाम',
  'dash.menu.itemDescription': 'विवरण',
  'dash.menu.category': 'श्रेणी',
  'dash.menu.price': 'कीमत',
  'dash.menu.basePrice': 'मूल कीमत ({currency})',
  'dash.menu.priceHint': 'अधिकतम {digits} दशमलव स्थानों वाली दशमलव राशि; पूर्णांक माइनर यूनिट के रूप में सेव होती है।',
  'dash.menu.status': 'स्थिति',
  'dash.menu.prepTime': 'तैयारी का समय (मिनट)',
  'dash.menu.availability': 'उपलब्धता',
  'dash.menu.dietary': 'आहार संबंधी जानकारी',
  'dash.menu.dietaryHint': 'कॉमा से अलग किए गए टैग (शाकाहारी, वीगन, ग्लूटेन-फ़्री…)। यह कोई मेडिकल गारंटी नहीं है।',
  'dash.menu.image': 'इमेज',
  'dash.menu.imageHint': 'डिश की चौकोर फ़ोटो, JPG / PNG / WebP, अधिकतम 8 MB — 800 × 800 px में क्रॉप की जाती है।',
  'dash.menu.featured': 'फ़ीचर्ड आइटम',
  'dash.menu.variants': 'वेरिएंट',
  'dash.menu.variantsSub': 'साइज़ या पोर्शन जैसे ज़रूरी विकल्प ग्रुप (नाम आपका अपना डेटा हैं)।',
  'dash.menu.modifiers': 'मॉडिफ़ायर',
  'dash.menu.modifiersSub': 'न्यूनतम / अधिकतम नियमों के साथ वैकल्पिक ऐड-ऑन और हटाने के विकल्प।',
  'dash.menu.addGroup': 'ग्रुप जोड़ें',
  'dash.menu.noGroups': 'अभी कोई ग्रुप नहीं है।',
  'dash.menu.groupName': 'ग्रुप का नाम',
  'dash.menu.groupNameVariantHint': 'जैसे साइज़',
  'dash.menu.groupNameModifierHint': 'जैसे ऐड-ऑन',
  'dash.menu.minSelections': 'न्यूनतम',
  'dash.menu.maxSelections': 'अधिकतम',
  'dash.menu.groupRequired': 'ज़रूरी (ग्राहक को चुनना होगा)',
  'dash.menu.optionName': 'विकल्प',
  'dash.menu.priceAdj': 'कीमत में बदलाव ({currency})',
  'dash.menu.optionAvailable': 'उपलब्ध',
  'dash.menu.addOption': 'विकल्प जोड़ें',
  'dash.menu.removeGroup': 'ग्रुप हटाएं',
  'dash.menu.markAs': '{status} के रूप में चिह्नित करें',
  'dash.menu.availabilityUpdated': '{name}: {status}',
  'dash.menu.itemSaved': '{name} सेव हो गया',
  'dash.menu.saveFailed': 'आइटम सेव नहीं हो सका। कृपया फिर से कोशिश करें।',
  'dash.menu.duplicated': 'आइटम की कॉपी बन गई',
  'dash.menu.archiveTitle': '{name} को आर्काइव करें?',
  'dash.menu.archiveText': 'यह आइटम ग्राहकों से छिपा रहेगा और आपके रिकॉर्ड में बना रहेगा। आप इसे बाद में वापस ला सकते हैं।',
  'dash.menu.archived': 'आइटम आर्काइव हो गया',
  'dash.menu.addCategory': 'श्रेणी जोड़ें',
  'dash.menu.editCategory': 'श्रेणी संपादित करें',
  'dash.menu.categoryName': 'श्रेणी का नाम',
  'dash.menu.categorySaved': 'श्रेणी सेव हो गई',
  'dash.menu.noCategories': 'अभी कोई श्रेणी नहीं है',
  'dash.menu.displayOrder': 'क्रम',
  'dash.menu.modifiersLead': 'पूरे मेन्यू के सभी वेरिएंट और मॉडिफ़ायर ग्रुप। इन्हें आइटम से संपादित करें।',
  'dash.menu.noModifiers': 'अभी कोई विकल्प ग्रुप नहीं है',
  'dash.menu.kind': 'प्रकार',
  'dash.menu.kind.variant': 'वेरिएंट',
  'dash.menu.kind.modifier': 'मॉडिफ़ायर',
  'dash.menu.rules': 'नियम',
  'dash.menu.options': 'विकल्प',
  'dash.menu.required': 'ज़रूरी',
  'dash.menu.optional': 'वैकल्पिक',
  'dash.validation.required': 'यह फ़ील्ड ज़रूरी है।',
  'dash.validation.price': 'मान्य कीमत दर्ज करें।',
  'dash.validation.range': 'मान सीमा से बाहर है।',
  'dash.validation.minMax': 'न्यूनतम / अधिकतम चयन जांचें।',
  'dash.validation.noOptions': 'कम से कम एक विकल्प जोड़ें।',
  'dash.validation.duplicate': 'यह नाम पहले से मौजूद है।',
  'dash.validation.summary': 'सेव करने से पहले कृपया {n} समस्या(एं) ठीक करें।',
  'dash.validation.url': 'http:// या https:// से शुरू होने वाला मान्य URL दर्ज करें।',
  'dash.validation.email': 'मान्य ई-मेल पता दर्ज करें।',
  'dash.validation.maxLength': 'अधिकतम {max} अक्षर।',
  'dash.validation.date': 'तारीख चुनें।',
  'dash.validation.time': 'मान्य समय दर्ज करें।',
  'dash.profile.title': 'रेस्टोरेंट प्रोफ़ाइल',
  'dash.profile.lead': 'ग्राहकों को यह लोकेशन कैसी दिखती है। आपके रेस्टोरेंट का लोगो FoodOnTheGo के लोगो से अलग है।',
  'dash.profile.tabs': 'प्रोफ़ाइल के सेक्शन',
  'dash.profile.tab.general': 'सामान्य जानकारी',
  'dash.profile.tab.images': 'इमेज',
  'dash.profile.tab.cuisine': 'व्यंजन और सुविधाएं',
  'dash.profile.name': 'रेस्टोरेंट का नाम',
  'dash.profile.description': 'विवरण',
  'dash.profile.phone': 'बिज़नेस फ़ोन',
  'dash.profile.phoneHint': 'अंतरराष्ट्रीय फ़ॉर्मेट (+देश कोड)।',
  'dash.profile.website': 'वेबसाइट (वैकल्पिक)',
  'dash.profile.email': 'सार्वजनिक संपर्क ई-मेल (वैकल्पिक)',
  'dash.profile.prep': 'डिफ़ॉल्ट तैयारी का समय (मिनट)',
  'dash.profile.prepHint': 'शुरुआती अनुमान — बैकएंड इसे डायनामिक रूप से बदल सकता है।',
  'dash.profile.imagesNote': 'डेवलपमेंट के दौरान इमेज ब्राउज़र में जांची, रीसाइज़ और क्रॉप की जाती हैं और इसी डिवाइस पर सेव होती हैं; बैकएंड वायरस स्कैनिंग, स्टोरेज और CDN डिलीवरी जोड़ेगा।',
  'dash.profile.logo': 'रेस्टोरेंट का लोगो',
  'dash.profile.logoAlt': 'रेस्टोरेंट का लोगो',
  'dash.profile.noLogo': 'अभी कोई लोगो नहीं है',
  'dash.profile.logoHint': 'सुझाया गया साइज़ 512 × 512 px, PNG या SVG।',
  'dash.profile.logoUrl': 'लोगो इमेज का पाथ',
  'dash.profile.cover': 'कवर इमेज',
  'dash.profile.coverAlt': 'रेस्टोरेंट की कवर इमेज',
  'dash.profile.noCover': 'अभी कोई कवर नहीं है',
  'dash.profile.coverHint': 'सुझाया गया साइज़ 1200 × 400 px, JPG या PNG।',
  'dash.profile.coverUrl': 'कवर इमेज का पाथ',
  'dash.profile.gallery': 'गैलरी (वैकल्पिक)',
  'dash.profile.noGallery': 'गैलरी में कोई इमेज नहीं है।',
  'dash.profile.galleryUrl': 'गैलरी इमेज का पाथ',
  'dash.profile.uploadPending': 'सर्वर-साइड अपलोड, मॉडरेशन और CDN डिलीवरी बैकएंड का काम है (CF-215); अपलोड फ़्लो, वैलिडेशन और इमेज ऑप्टिमाइज़ेशन फ़ाइनल हैं।',
  'dash.profile.cuisines': 'व्यंजन श्रेणियां',
  'dash.profile.addCuisine': 'व्यंजन जोड़ें',
  'dash.profile.cuisineHint': 'व्यंजन आपका अपना डेटा हैं — किसी मार्केट के लिए कुछ भी हार्डकोड नहीं है।',
  'dash.profile.features': 'सुविधाएं',
  'dash.profile.addFeature': 'सुविधा जोड़ें',
  'dash.profile.readOnly': 'आप यह प्रोफ़ाइल देख सकते हैं। संपादित करने के लिए profile.edit अनुमति ज़रूरी है।',
  'dash.profile.saved': 'प्रोफ़ाइल सेव हो गई',
  'dash.profile.saveFailed': 'प्रोफ़ाइल सेव नहीं हो सकी। कृपया फिर से कोशिश करें।',
  'dash.profile.status': 'संचालन स्थिति',
  'dash.profile.active': 'रेस्टोरेंट सक्रिय',
  'dash.profile.activeHint': 'प्लेटफ़ॉर्म द्वारा नियंत्रित लिस्टिंग स्थिति।',
  'dash.profile.activeYes': 'सक्रिय',
  'dash.profile.activeNo': 'निष्क्रिय',
  'dash.profile.openNow': 'रेस्टोरेंट खुला',
  'dash.profile.openHint': 'रेस्टोरेंट के टाइम ज़ोन में खुलने के समय के अनुसार।',
  'dash.profile.openYes': 'अभी खुला',
  'dash.profile.openNo': 'अभी बंद',
  'dash.profile.accepting': 'FoodOnTheGo ऑर्डर ले रहे हैं',
  'dash.profile.acceptingHint': 'खुला होने से ऑर्डर अपने आप स्वीकार नहीं होते।',
  'dash.profile.location': 'लोकेशन',
  'dash.profile.address': 'पता',
  'dash.profile.country': 'देश',
  'dash.profile.coordinates': 'कोऑर्डिनेट',
  'dash.profile.timezone': 'टाइम ज़ोन',
  'dash.profile.currency': 'मुद्रा',
  'dash.profile.locationNote': 'पता, कोऑर्डिनेट और टाइम ज़ोन बाद में प्लेसेस / मैप प्रोवाइडर से सत्यापित किए जाएंगे; हर लोकेशन का अपना IANA टाइम ज़ोन रहता है।',
  'dash.hours.title': 'खुलने का समय',
  'dash.hours.lead': 'रेस्टोरेंट के टाइम ज़ोन ({zone}) में साप्ताहिक शेड्यूल। एक से ज़्यादा अवधियां और रात भर का समय सपोर्ट किया जाता है।',
  'dash.hours.weekly': 'साप्ताहिक समय',
  'dash.hours.weeklySub': 'दिन को चालू या बंद करें, फिर एक या ज़्यादा अवधियां जोड़ें।',
  'dash.hours.openToggle': 'खुला',
  'dash.hours.open': 'खुला',
  'dash.hours.closed': 'बंद',
  'dash.hours.from': 'से',
  'dash.hours.to': 'तक',
  'dash.hours.overnight': 'रात भर → अगला दिन',
  'dash.hours.addPeriod': 'अवधि जोड़ें',
  'dash.hours.removePeriod': 'अवधि हटाएं',
  'dash.hours.errors': '{n} समस्या(एं) — हाइलाइट की गई अवधियां ठीक करें।',
  'dash.hours.issue.invalid_time': 'अमान्य समय',
  'dash.hours.issue.overlap': 'दूसरी अवधि से टकराती है',
  'dash.hours.issue.zero_length': 'खुलने और बंद होने का समय एक ही है',
  'dash.hours.issue.too_many': 'प्रतिदिन अधिकतम 4 अवधियां',
  'dash.hours.note': 'ग्राहकों के लिए उपलब्धता रेस्टोरेंट के टाइम ज़ोन में गिनी जाती है, डिवाइस के ज़ोन में कभी नहीं।',
  'dash.hours.saved': 'समय सेव हो गया',
  'dash.hours.saveFailed': 'समय सेव नहीं हो सका। कृपया फिर से कोशिश करें।',
  'dash.hours.special': 'विशेष समय और बंदी',
  'dash.hours.specialSub': 'किसी खास तारीख के लिए छुट्टियां, खुलने का विशेष समय या अस्थायी बंदी।',
  'dash.hours.noSpecial': 'अभी कोई विशेष समय नहीं है।',
  'dash.hours.date': 'तारीख',
  'dash.hours.label': 'लेबल',
  'dash.hours.labelHint': 'जैसे सार्वजनिक छुट्टी',
  'dash.hours.closedAllDay': 'पूरे दिन बंद',
  'dash.hours.specialOpenHours': 'विशेष समय',
  'dash.hours.closure': 'बंदी',
  'dash.hours.specialOpen': 'विशेष समय',
  'dash.hours.addSpecial': 'विशेष समय जोड़ें',
  'dash.hours.specialSaved': 'विशेष समय सेव हो गया',
  'dash.hours.removeSpecialTitle': 'यह विशेष समय हटाएं?',
  'dash.pickupSettings.title': 'पिकअप सेटिंग्स',
  'dash.pickupSettings.lead': 'ग्राहक इस लोकेशन पर ऑर्डर कैसे शेड्यूल और पिकअप कर सकते हैं।',
  'dash.pickupSettings.general': 'पिकअप ऑर्डर',
  'dash.pickupSettings.enable': 'पिकअप ऑर्डर चालू करें',
  'dash.pickupSettings.enableHint': 'अपनी लिस्टिंग बदले बिना शेड्यूलिंग रोकने के लिए बंद करें।',
  'dash.pickupSettings.asap': 'जल्द से जल्द (ASAP) ऑर्डर',
  'dash.pickupSettings.asapHint': 'ग्राहक सबसे जल्दी तैयार होने वाले समय के लिए ऑर्डर कर सकते हैं।',
  'dash.pickupSettings.scheduled': 'शेड्यूल किए गए ऑर्डर',
  'dash.pickupSettings.scheduledHint': 'ग्राहक आगे का कोई स्लॉट चुन सकते हैं।',
  'dash.pickupSettings.methods': 'पिकअप के तरीके',
  'dash.pickupSettings.methodsHint': 'ग्राहकों को केवल चालू किए गए तरीके ही दिखाए जाते हैं।',
  'dash.pickupSettings.method.counter': 'काउंटर पिकअप',
  'dash.pickupSettings.method.curbside': 'कर्बसाइड',
  'dash.pickupSettings.method.drive_through': 'ड्राइव-थ्रू',
  'dash.pickupSettings.vehicleInfo': 'ग्राहक से वाहन का विवरण मांगा जाता है।',
  'dash.pickupSettings.timing': 'समय',
  'dash.pickupSettings.timingSub': 'स्लॉट {zone} में बनाए जाते हैं।',
  'dash.pickupSettings.prep': 'तैयारी का समय',
  'dash.pickupSettings.prepHint': 'प्रोफ़ाइल से डिफ़ॉल्ट {n} मिनट; बैकएंड इसे डायनामिक रूप से गिन सकता है।',
  'dash.pickupSettings.interval': 'स्लॉट का अंतराल',
  'dash.pickupSettings.intervalHint': 'पिकअप स्लॉट के बीच का अंतर।',
  'dash.pickupSettings.minLead': 'न्यूनतम लीड टाइम (मिनट)',
  'dash.pickupSettings.horizon': 'अधिकतम कितना पहले शेड्यूल करें (मिनट)',
  'dash.pickupSettings.horizonHint': '1440 = एक दिन।',
  'dash.pickupSettings.buffer': 'बफ़र (मिनट)',
  'dash.pickupSettings.cutoff': 'बंद होने से पहले ऑर्डर लेने की आख़िरी सीमा (मिनट)',
  'dash.pickupSettings.instructions': 'पिकअप निर्देश',
  'dash.pickupSettings.instructionsHint': 'ग्राहकों को पुष्टि और ट्रैकिंग पर दिखाए जाते हैं।',
  'dash.pickupSettings.capacity': 'क्षमता नियम',
  'dash.pickupSettings.capacityHint': 'प्रति स्लॉट ऑर्डर / किचन लोड — बैकएंड स्लॉट इंजन।',
  'dash.pickupSettings.saved': 'पिकअप सेटिंग्स सेव हो गईं',
  'dash.pickupSettings.saveFailed': 'सेटिंग्स सेव नहीं हो सकीं। कृपया फिर से कोशिश करें।',
  'dash.pickupSettings.error.interval': 'कोई समर्थित अंतराल चुनें।',
  'dash.pickupSettings.error.range': 'मान सीमा से बाहर है।',
  'dash.pickupSettings.error.horizon': 'पहले शेड्यूल करने का समय लीड टाइम से ज़्यादा होना चाहिए।',
  'dash.pickupSettings.error.modes': 'कम से कम एक ऑर्डरिंग मोड चालू करें या पिकअप ऑर्डर बंद करें।',
  'dash.pickupSettings.error.methods': 'कम से कम एक पिकअप तरीका चालू करें।',
  'dash.reviews.title': 'समीक्षाएं',
  'dash.reviews.lead': 'इस लोकेशन के लिए सत्यापित ऑर्डर की समीक्षाएं। रेटिंग और ग्राहक का लिखा टेक्स्ट रेस्टोरेंट कभी संपादित नहीं कर सकता।',
  'dash.reviews.average': 'औसत रेटिंग',
  'dash.reviews.count': 'समीक्षाएं',
  'dash.reviews.answered': 'जवाब दिया गया',
  'dash.reviews.recent': 'हाल की समीक्षाएं',
  'dash.reviews.filter.all': 'सभी',
  'dash.reviews.filter.unanswered': 'बिना जवाब',
  'dash.reviews.filter.low': '3★ और उससे कम',
  'dash.reviews.emptyTitle': 'अभी कोई समीक्षा नहीं',
  'dash.reviews.emptyText': 'ग्राहकों के पिकअप ऑर्डर पूरे होने के बाद समीक्षाएं यहां दिखती हैं।',
  'dash.reviews.customer': 'ग्राहक',
  'dash.reviews.noText': 'सिर्फ़ रेटिंग — कोई लिखित समीक्षा नहीं।',
  'dash.reviews.responseFrom': '{name} का जवाब',
  'dash.reviews.respond': 'समीक्षा का जवाब दें',
  'dash.reviews.responseLabel': 'आपका जवाब',
  'dash.reviews.responseHint': 'मॉडरेशन के बाद सार्वजनिक होगा। भाषा पेशेवर रखें; ग्राहक की जानकारी कभी साझा न करें।',
  'dash.reviews.send': 'जवाब भेजें',
  'dash.reviews.responded': 'जवाब सेव हो गया',
  'dash.reviews.respondFailed': 'जवाब सेव नहीं हो सका।',
  'dash.reviews.distribution': 'रेटिंग वितरण',
  'dash.reviews.distributionSub': 'हर स्टार पर समीक्षाओं का हिस्सा',
  'dash.reviews.moderationNote': 'कुल आंकड़े बाद में सर्वर पर गिने जाएंगे; जवाब मॉडरेशन से होकर जाते हैं।',
  'dash.staff.title': 'स्टाफ़ प्रबंधन',
  'dash.staff.lead': 'आपके संगठन के टीम सदस्य, भूमिकाएं और लोकेशन एक्सेस।',
  'dash.staff.invite': 'स्टाफ़ को आमंत्रित करें',
  'dash.staff.col.name': 'नाम',
  'dash.staff.col.role': 'भूमिका',
  'dash.staff.col.access': 'लोकेशन एक्सेस',
  'dash.staff.col.status': 'स्थिति',
  'dash.staff.status.active': 'सक्रिय',
  'dash.staff.status.invited': 'आमंत्रित',
  'dash.staff.status.suspended': 'निलंबित',
  'dash.staff.allLocations': 'सभी लोकेशन',
  'dash.staff.someLocations': 'चुनी हुई लोकेशन',
  'dash.staff.emptyTitle': 'अभी कोई स्टाफ़ नहीं',
  'dash.staff.emptyText': 'अपने पहले टीम सदस्य को आमंत्रित करें।',
  'dash.staff.editTitle': 'स्टाफ़ सदस्य संपादित करें',
  'dash.staff.email': 'ई-मेल',
  'dash.staff.sendInvite': 'आमंत्रण भेजें',
  'dash.staff.inviteNote': 'आमंत्रण भेजने की सुविधा (ई-मेल / SMS) बैकएंड के साथ आएगी; सदस्य आमंत्रित के रूप में दिखेगा।',
  'dash.staff.invited': '{name} को आमंत्रित किया गया',
  'dash.staff.updated': 'स्टाफ़ सदस्य अपडेट हो गया',
  'dash.staff.duplicate': 'इस ई-मेल वाला सदस्य पहले से मौजूद है।',
  'dash.staff.lastOwner': 'संगठन में कम से कम एक मालिक होना ज़रूरी है।',
  'dash.staff.saveFailed': 'सेव नहीं हो सका। कृपया फिर से कोशिश करें।',
  'dash.staff.accessRequired': 'कम से कम एक लोकेशन चुनें।',
  'dash.staff.suspend': 'निलंबित करें',
  'dash.staff.reactivate': 'फिर से सक्रिय करें',
  'dash.staff.removeTitle': '{name} को हटाएं?',
  'dash.staff.removeText': 'उनका डैशबोर्ड एक्सेस तुरंत खत्म हो जाएगा।',
  'dash.staff.permissions': 'भूमिकाएं और अनुमतियां',
  'dash.staff.permissionsSub': 'भूमिकाएं अनुमतियों के समूह हैं; UI अनुमतियां जांचता है, भूमिका के नाम नहीं।',
  'dash.staff.permission': 'अनुमति',
  'dash.staff.granted': 'दी गई',
  'dash.staff.notGranted': 'नहीं दी गई',
  'dash.staff.permissionsFor': 'चुनी हुई भूमिका की अनुमतियां',
  'dash.staff.rbacNote': 'बटन छिपाना ऑथराइज़ेशन नहीं है — RBAC, टेनेंट आइसोलेशन और लोकेशन एक्सेस बैकएंड लागू करता है।',
  'dash.analytics.title': 'एनालिटिक्स',
  'dash.analytics.lead': 'इस लोकेशन का प्रदर्शन {currency} में। अलग-अलग लोकेशन की मुद्राएं कभी जोड़ी नहीं जातीं।',
  'dash.analytics.range': 'तारीख सीमा',
  'dash.analytics.range.today': 'आज',
  'dash.analytics.range.7d': '7 दिन',
  'dash.analytics.range.30d': '30 दिन',
  'dash.analytics.range.custom': 'कस्टम',
  'dash.analytics.from': 'से',
  'dash.analytics.to': 'तक',
  'dash.analytics.mockNote': 'डेवलपमेंट एनालिटिक्स — तय सैंपल डेटा, प्रोडक्शन के आंकड़े नहीं।',
  'dash.analytics.orders': 'ऑर्डर',
  'dash.analytics.revenue': 'आय ({currency})',
  'dash.analytics.aov': 'औसत ऑर्डर मूल्य',
  'dash.analytics.prep': 'तैयारी का औसत समय',
  'dash.analytics.revenueTrend': 'आय का रुझान',
  'dash.analytics.orderVolume': 'ऑर्डर की संख्या',
  'dash.analytics.statusDist': 'ऑर्डर स्थिति वितरण',
  'dash.analytics.cancelRate': 'रद्द होने की दर {rate}%',
  'dash.analytics.topItems': 'लोकप्रिय आइटम',
  'dash.analytics.ratings': 'रेटिंग वितरण',
  'dash.analytics.ratingSub': '{n} समीक्षाओं से औसत {avg}',
  'dash.analytics.pickupHours': 'सबसे व्यस्त पिकअप समय',
  'dash.analytics.pickupHoursSub': 'पिकअप के घंटे के अनुसार ऑर्डर ({zone})',
  'dash.analytics.emptyTitle': 'अभी कोई एनालिटिक्स नहीं',
  'dash.notifications.title': 'सूचनाएं',
  'dash.notifications.lead': 'इस लोकेशन के नए ऑर्डर, अपडेट, समीक्षाएं, पिकअप और प्लेटफ़ॉर्म की सूचनाएं।',
  'dash.notifications.unread': '{n} अपठित',
  'dash.notifications.markAll': 'सभी को पढ़ा हुआ मार्क करें',
  'dash.notifications.prefs': 'प्राथमिकताएं',
  'dash.notifications.filter': 'प्रकार के अनुसार फ़िल्टर करें',
  'dash.notifications.type.all': 'सभी',
  'dash.notifications.type.new_order': 'नया ऑर्डर',
  'dash.notifications.type.order_update': 'ऑर्डर अपडेट',
  'dash.notifications.type.pickup': 'पिकअप',
  'dash.notifications.type.review': 'समीक्षा',
  'dash.notifications.type.platform': 'प्लेटफ़ॉर्म सूचना',
  'dash.notifications.type.warning': 'संचालन चेतावनी',
  'dash.notifications.empty': 'कोई सूचना नहीं',
  'dash.notifications.emptyText': 'आपने सब कुछ देख लिया है।',
  'dash.notifications.new': 'नया',
  'dash.notifications.open': 'खोलें',
  'dash.notifications.viewAll': 'सभी सूचनाएं देखें',
  'dash.notifications.realtimeNote': 'लाइव सूचनाएं (WebSockets, पुश, ई-मेल, SMS) बैकएंड के साथ आएंगी; यह सूची डेवलपमेंट डेटा है।',
  'dash.settings.title': 'सेटिंग्स',
  'dash.settings.lead': 'इस लोकेशन की प्राथमिकताएं और संचालन सेटिंग्स।',
  'dash.settings.operational': 'संचालन',
  'dash.settings.sound': 'नए ऑर्डर पर आवाज़',
  'dash.settings.soundHint': 'नया ऑर्डर आने पर घंटी बजाएं।',
  'dash.settings.onboarding': 'ऑनबोर्डिंग स्थिति',
  'dash.settings.onboardingHint': 'स्वीकृति प्लेटफ़ॉर्म एडमिन के नियंत्रण में है।',
  'dash.settings.locale': 'भाषा और क्षेत्र',
  'dash.settings.language': 'डैशबोर्ड की भाषा',
  'dash.settings.languageHint': 'अनुवाद लोकलाइज़ेशन के साथ आएंगे; अंग्रेज़ी मूल भाषा है।',
  'dash.settings.timezoneHint': 'लोकेशन प्रोफ़ाइल से लिया गया IANA आइडेंटिफ़ायर।',
  'dash.settings.currencyHint': 'लोकेशन प्रोफ़ाइल से लिया गया ISO 4217।',
  'dash.settings.tax': 'टैक्स कॉन्फ़िगरेशन',
  'dash.settings.taxHint': 'मार्केट-स्तर के टैक्स नियम प्लेटफ़ॉर्म द्वारा कॉन्फ़िगर किए जाते हैं।',
  'dash.settings.notifications': 'सूचना प्राथमिकताएं',
  'dash.settings.notificationsSub': 'इस लोकेशन को किन बातों की सूचना चाहिए।',
  'dash.settings.pref.newOrders': 'नए ऑर्डर',
  'dash.settings.prefHint.newOrders': 'हर नया पिकअप ऑर्डर।',
  'dash.settings.pref.orderDelays': 'ऑर्डर में देरी',
  'dash.settings.prefHint.orderDelays': 'देर से चल रहे ऑर्डर।',
  'dash.settings.pref.pickup': 'पिकअप',
  'dash.settings.prefHint.pickup': 'सत्यापित हैंडओवर और पिकअप की समस्याएं।',
  'dash.settings.pref.reviews': 'समीक्षाएं',
  'dash.settings.prefHint.reviews': 'ग्राहकों की नई समीक्षाएं।',
  'dash.settings.pref.platform': 'प्लेटफ़ॉर्म संदेश',
  'dash.settings.prefHint.platform': 'FoodOnTheGo की सूचनाएं।',
  'dash.settings.deliveryNote': 'सूचना भेजने के चैनल (पुश, ई-मेल, SMS) बैकएंड इंटीग्रेशन के साथ कॉन्फ़िगर किए जाते हैं।',
  'dash.settings.account': 'खाता और सुरक्षा',
  'dash.settings.signedIn': 'इस खाते से साइन इन हैं',
  'dash.settings.password': 'पासवर्ड और साइन इन',
  'dash.settings.passwordHint': 'रेस्टोरेंट ऑथेंटिकेशन बाद के मॉड्यूल में आएगा।',
  'dash.settings.payouts': 'पेआउट और बैंकिंग',
  'dash.settings.payoutsHint': 'पेआउट प्रोवाइडर द्वारा सुरक्षित रूप से संभाला जाता है — डैशबोर्ड में कभी स्टोर नहीं होता।',
  'dash.settings.documents': 'व्यवसाय के दस्तावेज़',
  'dash.settings.documentsHint': 'ज़रूरतें हर मार्केट के अनुसार कॉन्फ़िगर की जाती हैं।',
  'dash.settings.devReset': 'डैशबोर्ड डेटा रीसेट करें (डेवलपमेंट)',
  'dash.settings.devResetHint': 'इस ब्राउज़र पर सिर्फ़ डैशबोर्ड का डेवलपमेंट डेटा मिटाता है।',
  'dash.settings.reset': 'रीसेट करें',
  'dash.settings.saved': 'सेटिंग्स सेव हो गईं',
  'dash.help.title': 'सहायता',
  'dash.help.lead': 'रेस्टोरेंट पार्टनर के लिए गाइड और सहायता।',
  'dash.help.search': 'सहायता खोजें',
  'dash.help.searchPlaceholder': 'सहायता विषय खोजें…',
  'dash.help.topic.orders': 'ऑर्डर',
  'dash.help.topicText.orders': 'ऑर्डर स्वीकार करना, अस्वीकार करना, देरी और तैयार मार्क करना।',
  'dash.help.topic.menu': 'मेन्यू',
  'dash.help.topicText.menu': 'श्रेणियां, आइटम, वेरिएंट, मॉडिफ़ायर और उपलब्धता।',
  'dash.help.topic.pickup': 'पिकअप',
  'dash.help.topicText.pickup': 'काउंटर पर पिकअप कोड और QR स्कैन की जांच।',
  'dash.help.topic.reviews': 'समीक्षाएं',
  'dash.help.topicText.reviews': 'ग्राहकों की राय पढ़ना और जवाब देना।',
  'dash.help.topic.payments': 'भुगतान',
  'dash.help.topicText.payments': 'सेटलमेंट, शुल्क और पेआउट (बैकएंड के साथ आएंगे)।',
  'dash.help.topic.account': 'खाता',
  'dash.help.topicText.account': 'स्टाफ़, भूमिकाएं और लोकेशन एक्सेस।',
  'dash.help.topic.technical': 'तकनीकी सहायता',
  'dash.help.topicText.technical': 'डैशबोर्ड की समस्याएं, ब्राउज़र और डिवाइस।',
  'dash.upload.drop': 'इमेज यहां छोड़ें',
  'dash.upload.browse': 'या चुनने के लिए क्लिक करें',
  'dash.upload.uploading': 'इमेज प्रोसेस हो रही है…',
  'dash.upload.replace': 'बदलें',
  'dash.upload.remove': 'हटाएं',
  'dash.upload.hint': '{types} · अधिकतम {max} · सुझाया गया साइज़ {size} px',
  'dash.upload.optimized': 'वेब के लिए ऑप्टिमाइज़ की गई',
  'dash.upload.addPhotos': 'फ़ोटो जोड़ें',
  'dash.upload.galleryAlt': 'गैलरी फ़ोटो {n}',
  'dash.upload.error.type': 'यह फ़ाइल प्रकार समर्थित नहीं है। {types} इस्तेमाल करें।',
  'dash.upload.error.size': 'फ़ाइल {max} से बड़ी है।',
  'dash.upload.error.dimensions': 'इमेज सुझाए गए {min} px से छोटी है ({detail}); यह धुंधली दिख सकती है।',
  'dash.upload.error.decode': 'यह फ़ाइल इमेज के रूप में पढ़ी नहीं जा सकी।',
  'dash.upload.error.storage': 'डेवलपमेंट स्टोरेज भर गया है — कुछ इमेज हटाएं और फिर से कोशिश करें।',
  'dash.upload.error.empty': 'कोई इमेज फ़ाइल चुनें।',
  'dash.upload.error.max': 'गैलरी में अधिकतम {max} फ़ोटो आ सकती हैं।',
  'dash.menu.categoryIcon': 'श्रेणी आइकन (वैकल्पिक)',
  'dash.menu.categoryIconHint': 'श्रेणी के नाम के पास दिखने वाला छोटा चौकोर आइकन।',
  'dash.staff.photo': 'प्रोफ़ाइल फ़ोटो (वैकल्पिक)',
  'dash.staff.photoHint': 'चौकोर फ़ोटो; हेडर और स्टाफ़ सूची में दिखती है।',
  'dash.help.contact': 'पार्टनर सहायता से संपर्क करें',
  'dash.help.contactSub': 'सहायता चैनल बैकएंड के साथ कॉन्फ़िगर किए जाते हैं।',
  'dash.help.partnerSupport': 'पार्टनर सहायता लाइन',
  'dash.help.partnerSupportHint': 'आधिकारिक संपर्क विवरण लंबित (CF-023)।',
  'dash.help.status': 'प्लेटफ़ॉर्म स्थिति',
  'dash.help.statusHint': 'डेवलपमेंट एनवायरनमेंट।',
  'dash.help.operational': 'चालू है',
  'dash.help.customerHelp': 'ग्राहक सहायता केंद्र',
  'dash.help.customerHelpHint': 'आपके ग्राहक क्या देखते हैं।',
  'dash.help.openCustomerHelp': 'खोलें',
}
