/**
 * Order domain (Module 13) — the confirmed order, its immutable snapshots, pickup verification and receipt.
 *
 * Permanent rules:
 *  - The customer sees a public order reference (orderNumber) and a public id; internal sequential ids never leave the server.
 *  - Order status and payment status are separate fields.
 *  - Everything displayed comes from the order snapshot (restaurant, items, prices, pickup, currency) — never from the live menu.
 *  - Pickup code + QR token are opaque values generated by the server later; the QR contains only the opaque token.
 *    Their visual presence never proves pickup — the server validates token, order, restaurant, status, validity, used state.
 *  - Reloading a confirmation never creates another order, payment or pickup code.
 */
export type OrderStatus = 'PAYMENT_PENDING' | 'CONFIRMED' | 'ACCEPTED' | 'PREPARING' | 'READY_FOR_PICKUP' | 'PICKED_UP' | 'COMPLETED' | 'CANCELLED' | 'REJECTED' | 'REFUND_PENDING' | 'REFUNDED'
export type OrderPaymentStatus = 'PAYMENT_PENDING' | 'PAID' | 'FAILED' | 'REFUND_PENDING' | 'PARTIALLY_REFUNDED' | 'REFUNDED'
export type PickupVerificationStatus = 'NOT_READY' | 'READY' | 'VERIFICATION_AVAILABLE' | 'VERIFIED' | 'ALREADY_USED' | 'INVALID' | 'EXPIRED'

export type OrderOptionSnapshot = { groupName: string; optionName: string; priceAdjustmentMinor: number }
export type OrderItemSnapshot = {
  lineId: string
  menuItemId: string
  itemName: string
  image: string
  variants: OrderOptionSnapshot[]
  modifiers: OrderOptionSnapshot[]
  specialInstructions: string
  quantity: number
  unitPriceMinor: number
  lineTotalMinor: number
}
export type RestaurantSnapshot = {
  id: string
  slug: string
  name: string
  formattedAddress: string
  countryCode: string
  timezone: string
  lat: number | null
  lng: number | null
  /** Restaurant-published contact (phone / email) — null until the restaurant publishes it. */
  contact: string | null
  pickupInstructions: string | null
  pickupLocation: string | null
}
export type PickupSnapshot = {
  mode: 'asap' | 'scheduled'
  requestedAt: string
  estimatedReadyTime: string
  restaurantTimezone: string
  methodType: string
  methodLabel: string
  instructions: string | null
}
export type PricingLine = { id: string; label: string; amountMinor: number }
export type OrderPricing = { currency: string; subtotalMinor: number; discountMinor: number; promoCode: string | null; taxes: PricingLine[]; fees: PricingLine[]; totalMinor: number }
export type OrderPaymentSummary = {
  status: OrderPaymentStatus
  methodType: string
  methodLabel: string
  providerDisplayName: string
  /** Public payment reference (attempt publicId) — safe to show. */
  reference: string
  paidAmountMinor: number
  currency: string
  /** Approved masked details from the provider later ("Card ending in 4242"); never derived by us. */
  maskedDetails: string | null
}
export type JourneySnapshot = { journeyId: string; originName: string; destinationName: string } | null
export type OrderEvent = { eventId: string; status: string; at: string; actor: 'customer' | 'system' | 'restaurant'; note?: string }

export type Order = {
  /** Public, non-sequential id (ULID-like). */
  publicId: string
  /** Customer-friendly public reference. Format is a development fixture; the backend generates it later. */
  orderNumber: string
  customerId: string
  restaurant: RestaurantSnapshot
  items: OrderItemSnapshot[]
  pricing: OrderPricing
  orderStatus: OrderStatus
  paymentStatus: OrderPaymentStatus
  payment: OrderPaymentSummary
  pickup: PickupSnapshot
  /** Reference to the pickup verification record (code + token live there, not on the order). */
  pickupCodeReference: string
  paymentAttemptId: string
  checkoutReference: string
  journey: JourneySnapshot
  orderNote: string
  events: OrderEvent[]
  createdAt: string
  updatedAt: string
}

export type PickupVerification = {
  reference: string
  orderPublicId: string
  /** Short customer-readable code (fixture format; server-generated, unpredictable later). */
  code: string
  /** Opaque token encoded in the QR — carries no order / customer / payment data. */
  qrToken: string
  status: PickupVerificationStatus
  activatedAt: string | null
  expiresAt: string | null
}

export type Receipt = {
  orderNumber: string
  orderDate: string
  restaurantName: string
  restaurantAddress: string
  customerName: string | null
  items: OrderItemSnapshot[]
  pricing: OrderPricing
  paymentMethodLabel: string
  paymentReference: string
  paymentStatus: OrderPaymentStatus
  pickup: PickupSnapshot
  /** Development receipt — not a tax invoice (jurisdiction rules pending). */
  kind: 'ORDER_RECEIPT'
}

export type CreateOrderInput = {
  paymentAttemptId: string
  checkoutReference: string
  customerId: string
  restaurant: RestaurantSnapshot
  items: OrderItemSnapshot[]
  pricing: OrderPricing
  payment: OrderPaymentSummary
  pickup: PickupSnapshot
  journey: JourneySnapshot
  orderNote: string
}

export interface OrderRepository {
  /** Idempotent per payment attempt — a refresh or repeated handoff returns the same order. */
  createFromPayment(input: CreateOrderInput): Promise<Order>
  getByOrderNumber(orderNumber: string, customerId: string): Promise<Order | null>
  findByPaymentAttempt(paymentAttemptId: string): Promise<Order | null>
  listForCustomer(customerId: string): Promise<Order[]>
}
export interface PickupVerificationRepository {
  getForOrder(order: Order): Promise<PickupVerification | null>
}
export interface ReceiptRepository {
  getReceipt(order: Order, customerName: string | null): Promise<Receipt>
}
