/**
 * Order domain (Module 13) — the confirmed order, its immutable snapshots, pickup verification and receipt.
 *
 * Permanent rules:
 *  - The customer sees a public order reference (orderNumber) and a public id; internal sequential ids never leave the server.
 *  - Order status and payment status are separate fields.
 *  - Everything displayed comes from the order snapshot (restaurant, items, prices, pickup, currency) — never from the live menu.
 *  - Pickup code + QR token are opaque values generated by the server later; the QR contains only the opaque token.
 *    Their visual presence never proves pickup — the server validates token, order, restaurant, status, validity, used state.
 *  - Reloading a confirmation never creates another order, payment or pickup code.
 */
export type OrderStatus = 'PAYMENT_PENDING' | 'CONFIRMED' | 'AWAITING_RESTAURANT_ACCEPTANCE' | 'ACCEPTED' | 'PREPARING' | 'READY_FOR_PICKUP' | 'PICKUP_VERIFICATION' | 'PICKED_UP' | 'COMPLETED' | 'CANCELLED' | 'REJECTED' | 'REFUND_PENDING' | 'REFUNDED'
export type OrderPaymentStatus = 'PAYMENT_PENDING' | 'PAID' | 'FAILED' | 'REFUND_PENDING' | 'PARTIALLY_REFUNDED' | 'REFUNDED'
export type PickupVerificationStatus = 'NOT_READY' | 'READY' | 'VERIFICATION_AVAILABLE' | 'VERIFIED' | 'ALREADY_USED' | 'INVALID' | 'EXPIRED'

export type OrderOptionSnapshot = { groupName: string; optionName: string; priceAdjustmentMinor: number }
export type OrderItemSnapshot = {
  lineId: string
  menuItemId: string
  itemName: string
  image: string
  variants: OrderOptionSnapshot[]
  modifiers: OrderOptionSnapshot[]
  specialInstructions: string
  quantity: number
  unitPriceMinor: number
  lineTotalMinor: number
}
export type RestaurantSnapshot = {
  id: string
  slug: string
  name: string
  formattedAddress: string
  countryCode: string
  timezone: string
  lat: number | null
  lng: number | null
  /** Restaurant-published contact (phone / email) — null until the restaurant publishes it. */
  contact: string | null
  pickupInstructions: string | null
  pickupLocation: string | null
}
export type PickupSnapshot = {
  mode: 'asap' | 'scheduled'
  requestedAt: string
  estimatedReadyTime: string
  restaurantTimezone: string
  methodType: string
  methodLabel: string
  instructions: string | null
  /** Journey-based arrival estimate (mock ETA service) — separate from the food-ready ETA. */
  estimatedCustomerArrival?: string | null
}
export type PricingLine = { id: string; label: string; amountMinor: number }
export type OrderPricing = { currency: string; subtotalMinor: number; discountMinor: number; promoCode: string | null; taxes: PricingLine[]; fees: PricingLine[]; totalMinor: number }
export type OrderPaymentSummary = {
  status: OrderPaymentStatus
  methodType: string
  methodLabel: string
  providerDisplayName: string
  /** Public payment reference (attempt publicId) — safe to show. */
  reference: string
  paidAmountMinor: number
  /** Refunded so far (minor units) — partial refunds are representable; null when no refund exists. */
  refundedAmountMinor?: number | null
  currency: string
  /** Approved masked details from the provider later ("Card ending in 4242"); never derived by us. */
  maskedDetails: string | null
}
export type JourneySnapshot = { journeyId: string; originName: string; destinationName: string; originLat?: number | null; originLng?: number | null } | null
/** Structured, append-only order event (Module 14). `sequence` lets clients ignore duplicates and stale events. */
export type OrderEventType = 'ORDER_CREATED' | 'PAYMENT_VERIFIED' | 'ORDER_CONFIRMED' | 'SENT_TO_RESTAURANT' | 'RESTAURANT_ACCEPTED' | 'RESTAURANT_REJECTED' | 'PREPARING' | 'DELAYED' | 'ETA_UPDATED' | 'READY_FOR_PICKUP' | 'PICKUP_VERIFICATION' | 'PICKED_UP' | 'COMPLETED' | 'CANCELLED' | 'REFUND_UPDATED'
export type OrderEvent = {
  eventId: string
  /** Monotonic per order; the backend will version events the same way (CF-179). */
  sequence: number
  type: OrderEventType
  /** Order status after this event (null when the event does not change it, e.g. ETA_UPDATED). */
  status: OrderStatus | null
  paymentStatus?: OrderPaymentStatus | null
  at: string
  actor: 'customer' | 'system' | 'restaurant'
  /** Customer-safe reason key (track.reason.*) — internal restaurant notes never travel here. */
  reasonKey?: string | null
  /** Updated food-ready ETA (ISO instant) when the event changes it. */
  etaReadyAt?: string | null
  note?: string
}

export type Order = {
  /** Public, non-sequential id (ULID-like). */
  publicId: string
  /** Customer-friendly public reference. Format is a development fixture; the backend generates it later. */
  orderNumber: string
  customerId: string
  restaurant: RestaurantSnapshot
  items: OrderItemSnapshot[]
  pricing: OrderPricing
  orderStatus: OrderStatus
  paymentStatus: OrderPaymentStatus
  payment: OrderPaymentSummary
  pickup: PickupSnapshot
  /** Reference to the pickup verification record (code + token live there, not on the order). */
  pickupCodeReference: string
  pickupVerificationStatus: PickupVerificationStatus
  /** Food-ready ETA (restaurant / backend estimate) — distinct from the customer arrival ETA on the pickup snapshot. */
  etaReadyAt: string | null
  delayed: boolean
  delayReasonKey: string | null
  rejectionReasonKey: string | null
  cancellationReasonKey: string | null
  lastEventSequence: number
  paymentAttemptId: string
  checkoutReference: string
  journey: JourneySnapshot
  orderNote: string
  events: OrderEvent[]
  createdAt: string
  updatedAt: string
}

export type PickupVerification = {
  reference: string
  orderPublicId: string
  /** Short customer-readable code (fixture format; server-generated, unpredictable later). */
  code: string
  /** Opaque token encoded in the QR — carries no order / customer / payment data. */
  qrToken: string
  status: PickupVerificationStatus
  activatedAt: string | null
  expiresAt: string | null
}

export type Receipt = {
  orderNumber: string
  orderDate: string
  restaurantName: string
  restaurantAddress: string
  customerName: string | null
  items: OrderItemSnapshot[]
  pricing: OrderPricing
  paymentMethodLabel: string
  paymentReference: string
  paymentStatus: OrderPaymentStatus
  pickup: PickupSnapshot
  /** Development receipt — not a tax invoice (jurisdiction rules pending). */
  kind: 'ORDER_RECEIPT'
}

export type CreateOrderInput = {
  paymentAttemptId: string
  checkoutReference: string
  customerId: string
  restaurant: RestaurantSnapshot
  items: OrderItemSnapshot[]
  pricing: OrderPricing
  payment: OrderPaymentSummary
  pickup: PickupSnapshot
  journey: JourneySnapshot
  orderNote: string
}

/** Lightweight row for order history — never the full snapshot. */
export type OrderSummary = {
  publicId: string
  orderNumber: string
  restaurantName: string
  restaurantSlug: string
  restaurantImage: string | null
  restaurantTimezone: string
  createdAt: string
  pickupAt: string
  itemCount: number
  itemPreview: string
  currency: string
  totalMinor: number
  orderStatus: OrderStatus
  paymentStatus: OrderPaymentStatus
  reorderEligible: boolean
}
export type OrderGroup = 'all' | 'ongoing' | 'completed' | 'cancelled'
export type OrderSort = 'newest' | 'oldest'
export type OrderListQuery = { group?: OrderGroup; query?: string; sort?: OrderSort; cursor?: string | null; limit?: number }
export type OrderPage = { items: OrderSummary[]; nextCursor: string | null; total: number }

export interface OrderRepository {
  /** Paginated, filtered, sorted history summaries (cursor = opaque token; the backend pages the same way). */
  listSummaries(customerId: string, q?: OrderListQuery): Promise<OrderPage>
  /** Idempotent per payment attempt — a refresh or repeated handoff returns the same order. */
  createFromPayment(input: CreateOrderInput): Promise<Order>
  getByOrderNumber(orderNumber: string, customerId: string): Promise<Order | null>
  findByPaymentAttempt(paymentAttemptId: string): Promise<Order | null>
  listForCustomer(customerId: string): Promise<Order[]>
  /** Applies tracking events in sequence order (duplicates and stale sequences are ignored) and persists the result. */
  applyEvents(orderNumber: string, events: OrderEvent[]): Promise<Order | null>
}
export interface PickupVerificationRepository {
  getForOrder(order: Order): Promise<PickupVerification | null>
}
export interface ReceiptRepository {
  getReceipt(order: Order, customerName: string | null): Promise<Receipt>
}
