/** Platform Admin strings — Hindi. Same keys as the English table (checked by a test). Machine-assisted translation: wording to be reviewed by a native speaker before go-live. */
export const adminStringsHi: Record<string, string> = {
  'adm.brand': 'प्लेटफ़ॉर्म एडमिनिस्ट्रेशन',
  'adm.title': 'FoodOnTheGo एडमिन',
  'adm.nav.label': 'एडमिन नेविगेशन',
  'adm.nav.open': 'नेविगेशन खोलें',
  'adm.nav.expand': 'नेविगेशन फैलाएं',
  'adm.nav.badge': '{n} आइटम पर ध्यान देना ज़रूरी है',
  'adm.nav.group.operations': 'ऑपरेशन्स',
  'adm.nav.group.finance': 'फ़ाइनेंस',
  'adm.nav.group.growth': 'ग्रोथ',
  'adm.nav.group.platform': 'प्लेटफ़ॉर्म',
  'adm.nav.group.security': 'सुरक्षा और एडमिनिस्ट्रेशन',
  'adm.nav.overview': 'ओवरव्यू',
  'adm.nav.restaurants': 'रेस्टोरेंट',
  'adm.nav.customers': 'ग्राहक',
  'adm.nav.orders': 'ऑर्डर',
  'adm.nav.reviews': 'समीक्षाएं',
  'adm.nav.support': 'सहायता',
  'adm.nav.payments': 'भुगतान',
  'adm.nav.refunds': 'रिफ़ंड',
  'adm.nav.settlements': 'सेटलमेंट',
  'adm.nav.promotions': 'प्रमोशन',
  'adm.nav.markets': 'मार्केट',
  'adm.nav.configuration': 'कॉन्फ़िगरेशन',
  'adm.nav.notifications': 'सूचनाएं',
  'adm.nav.analytics': 'एनालिटिक्स',
  'adm.nav.adminUsers': 'एडमिन उपयोगकर्ता',
  'adm.nav.auditLogs': 'ऑडिट लॉग',
  'adm.nav.security': 'सुरक्षा',
  'adm.nav.system': 'सिस्टम की स्थिति',
  'adm.nav.settings': 'सेटिंग्स',
  'adm.nav.help': 'मदद',
  'adm.env.LOCAL': 'लोकल',
  'adm.env.STAGING': 'स्टेजिंग',
  'adm.env.PRODUCTION': 'प्रोडक्शन',
  'adm.env.mock': 'मॉक डेटा',
  'adm.env.title': 'एनवायरनमेंट संकेतक (बिल्ड कॉन्फ़िगरेशन)',
  'adm.header.alerts': 'अलर्ट ({n} बिना पढ़े)',
  'adm.header.alertsTitle': 'गंभीर अलर्ट',
  'adm.header.switchAdmin': 'डेवलपमेंट: एडमिन उपयोगकर्ता बदलें',
  'adm.header.devNote': 'यह स्विच सिर्फ़ डेवलपमेंट के लिए है। एडमिन ऑथेंटिकेशन (MFA के साथ) बाद का मॉड्यूल है; अनुमतियां बैकएंड लागू करता है।',
  'adm.header.exit': 'ग्राहक साइट पर जाएं',
  'adm.search.label': 'ग्लोबल खोज',
  'adm.search.placeholder': 'रेस्टोरेंट, ऑर्डर, ग्राहक खोजें…',
  'adm.search.empty': 'कुछ नहीं मिला।',
  'adm.search.kind.restaurant': 'रेस्टोरेंट',
  'adm.search.kind.order': 'ऑर्डर',
  'adm.search.kind.customer': 'ग्राहक',
  'adm.search.kind.payment': 'भुगतान',
  'adm.search.kind.support': 'सहायता',
  'adm.alerts.empty': 'कोई अलर्ट नहीं।',
  'adm.role.super_admin': 'सुपर एडमिन',
  'adm.role.operations_admin': 'ऑपरेशन्स एडमिन',
  'adm.role.restaurant_onboarding': 'रेस्टोरेंट ऑनबोर्डिंग',
  'adm.role.support_admin': 'सहायता एडमिन',
  'adm.role.finance_admin': 'फ़ाइनेंस एडमिन',
  'adm.role.moderation_admin': 'मॉडरेशन एडमिन',
  'adm.role.analyst': 'एनालिस्ट',
  'adm.userStatus.INVITED': 'आमंत्रित',
  'adm.userStatus.ACTIVE': 'सक्रिय',
  'adm.userStatus.SUSPENDED': 'निलंबित',
  'adm.userStatus.DISABLED': 'अक्षम',
  'adm.error.loadTitle': 'यह व्यू लोड नहीं हो सका',
  'adm.error.loadText': 'एक अस्थायी समस्या के कारण डेटा लोड नहीं हो सका। कृपया फिर से कोशिश करें।',
  'adm.error.forbiddenTitle': 'आपको इस हिस्से की एक्सेस नहीं है',
  'adm.error.forbiddenText': 'आपकी भूमिका ({role}) में यह अनुमति शामिल नहीं है। बैकएंड भी यही नियम लागू करता है।',
  'adm.error.saveFailed': 'बदलाव सेव नहीं हो सका। कृपया फिर से कोशिश करें।',
  'adm.error.notFound': 'नहीं मिला',
  'adm.table.actions': 'कार्रवाई',
  'adm.table.showing': '{total} में से {from}–{to} दिखाए जा रहे हैं',
  'adm.table.pagination': 'पेज नेविगेशन',
  'adm.table.prev': 'पिछला',
  'adm.table.next': 'अगला',
  'adm.table.pageOf': 'पेज {page} / {pages}',
  'adm.table.view': 'देखें',
  'adm.table.details': 'विवरण देखें',
  'adm.table.all': 'सभी',
  'adm.dialog.category': 'श्रेणी',
  'adm.dialog.reasonRequired': 'कारण (ज़रूरी, ऑडिट लॉग में दर्ज होगा)',
  'adm.dialog.reasonOptional': 'नोट (वैकल्पिक)',
  'adm.dialog.reasonError': 'कृपया कम से कम 3 अक्षरों का कारण लिखें।',
  'adm.action.approve': 'स्वीकृत करें',
  'adm.action.reject': 'अस्वीकृत करें',
  'adm.action.requestInfo': 'जानकारी मांगें',
  'adm.action.suspend': 'निलंबित करें',
  'adm.action.reactivate': 'फिर से सक्रिय करें',
  'adm.action.restrict': 'प्रतिबंधित करें',
  'adm.action.deactivate': 'निष्क्रिय करें',
  'adm.action.activate': 'सक्रिय करें',
  'adm.action.reverify': 'दोबारा सत्यापन ज़रूरी करें',
  'adm.action.addNote': 'आंतरिक नोट जोड़ें',
  'adm.action.export': 'एक्सपोर्ट करें',
  'adm.action.save': 'सेव करें',
  'adm.action.invite': 'एडमिन को आमंत्रित करें',
  'adm.action.create': 'बनाएं',
  'adm.action.edit': 'संपादित करें',
  'adm.action.close': 'बंद करें',
  'adm.action.apply': 'लागू करें',
  'adm.action.review': 'जांच करें',
  'adm.action.viewAll': 'सभी देखें',
  'adm.action.retry': 'फिर से कोशिश करें',
  'adm.saved': 'सेव हो गया।',
  'adm.updated': 'अपडेट हो गया।',
  'adm.today': 'आज',
  'adm.range.today': 'आज',
  'adm.range.7d': 'पिछले 7 दिन',
  'adm.range.30d': 'पिछले 30 दिन',
  'adm.range.quarter': 'तिमाही',
  'adm.range.custom': 'कस्टम',
  'adm.range.all': 'अब तक',
  'adm.market.all': 'सभी मार्केट',
  'adm.status.all': 'सभी स्थितियां',
  'adm.currency.all': 'सभी मुद्राएं',
  'adm.mockNote': 'डेवलपमेंट फ़िक्स्चर — हर आंकड़े और कार्रवाई के लिए बैकएंड ही मान्य स्रोत है।',
  'adm.overview.title': 'प्लेटफ़ॉर्म ओवरव्यू',
  'adm.overview.lead': 'आज FoodOnTheGo पर क्या हो रहा है, यहां देखें।',
  'adm.overview.updated': 'पिछला अपडेट: {time}',
  'adm.kpi.restaurants': 'कुल रेस्टोरेंट',
  'adm.kpi.activeRestaurants': 'सक्रिय रेस्टोरेंट',
  'adm.kpi.pending': 'लंबित स्वीकृतियां',
  'adm.kpi.customers': 'सक्रिय ग्राहक',
  'adm.kpi.ordersToday': 'आज के ऑर्डर',
  'adm.kpi.inProgress': 'जारी ऑर्डर',
  'adm.kpi.refunds': 'लंबित रिफ़ंड',
  'adm.kpi.failedPayments': 'विफल भुगतान (24 घंटे)',
  'adm.kpi.openSupport': 'खुले सहायता टिकट',
  'adm.kpi.rating': 'प्लेटफ़ॉर्म रेटिंग',
  'adm.kpi.gmv': 'कुल ऑर्डर मूल्य',
  'adm.overview.ordersChart': 'ऑर्डर ओवरव्यू',
  'adm.overview.ordersByHour': 'घंटे के अनुसार ऑर्डर (आज)',
  'adm.overview.health': 'प्लेटफ़ॉर्म हेल्थ',
  'adm.overview.activity': 'हाल की गतिविधि',
  'adm.overview.pending': 'लंबित रेस्टोरेंट स्वीकृतियां',
  'adm.overview.top': 'सबसे अच्छा प्रदर्शन करने वाले रेस्टोरेंट',
  'adm.overview.gmvNote': 'GMV हर मुद्रा के लिए अलग — अलग-अलग मुद्राओं को कभी जोड़ा नहीं जाता।',
  'adm.overview.noPending': 'कोई रेस्टोरेंट जांच के इंतज़ार में नहीं है।',
  'adm.overview.critical': '{n} गंभीर अलर्ट पर ध्यान देना ज़रूरी है',
  'adm.health.OPERATIONAL': 'चालू',
  'adm.health.DEGRADED': 'धीमा',
  'adm.health.OUTAGE': 'ठप',
  'adm.health.UNKNOWN': 'अज्ञात',
  'adm.restaurants.title': 'रेस्टोरेंट प्रबंधन',
  'adm.restaurants.lead': 'प्लेटफ़ॉर्म के सभी रेस्टोरेंट मैनेज करें।',
  'adm.restaurants.tabs': 'रेस्टोरेंट की स्थितियां',
  'adm.restaurants.tab.all': 'सभी',
  'adm.restaurants.tab.pending': 'लंबित',
  'adm.restaurants.tab.approved': 'स्वीकृत',
  'adm.restaurants.tab.suspended': 'निलंबित',
  'adm.restaurants.tab.rejected': 'अस्वीकृत',
  'adm.restaurants.tab.inactive': 'ड्राफ़्ट',
  'adm.restaurants.search': 'रेस्टोरेंट खोजें…',
  'adm.restaurants.cuisine.all': 'सभी व्यंजन शैलियां',
  'adm.restaurants.sort': 'क्रम',
  'adm.restaurants.sort.created': 'सबसे नए',
  'adm.restaurants.sort.name': 'नाम',
  'adm.restaurants.sort.orders': 'ऑर्डर',
  'adm.restaurants.sort.rating': 'रेटिंग',
  'adm.restaurants.col.restaurant': 'रेस्टोरेंट',
  'adm.restaurants.col.organization': 'संगठन',
  'adm.restaurants.col.locations': 'लोकेशन',
  'adm.restaurants.col.market': 'मार्केट',
  'adm.restaurants.col.status': 'स्थिति',
  'adm.restaurants.col.rating': 'रेटिंग',
  'adm.restaurants.col.orders': 'ऑर्डर',
  'adm.restaurants.col.submitted': 'सबमिट किया गया',
  'adm.restaurants.locations': '{n} लोकेशन',
  'adm.restaurants.empty': 'इन फ़िल्टर से कोई रेस्टोरेंट मेल नहीं खाता।',
  'adm.restaurants.status.DRAFT': 'ड्राफ़्ट',
  'adm.restaurants.status.SUBMITTED': 'सबमिट किया गया',
  'adm.restaurants.status.UNDER_REVIEW': 'जांच जारी',
  'adm.restaurants.status.APPROVED': 'स्वीकृत',
  'adm.restaurants.status.REJECTED': 'अस्वीकृत',
  'adm.restaurants.status.SUSPENDED': 'निलंबित',
  'adm.restaurant.tabs': 'रेस्टोरेंट के सेक्शन',
  'adm.restaurant.tab.overview': 'ओवरव्यू',
  'adm.restaurant.tab.documents': 'दस्तावेज़',
  'adm.restaurant.tab.locations': 'लोकेशन',
  'adm.restaurant.tab.notes': 'आंतरिक नोट',
  'adm.restaurant.tab.history': 'इतिहास',
  'adm.restaurant.profile': 'प्रोफ़ाइल',
  'adm.restaurant.organization': 'संगठन',
  'adm.restaurant.market': 'मार्केट',
  'adm.restaurant.timezone': 'टाइम ज़ोन',
  'adm.restaurant.currency': 'मुद्रा',
  'adm.restaurant.cuisines': 'व्यंजन शैलियां',
  'adm.restaurant.address': 'पता',
  'adm.restaurant.created': 'बनाया गया',
  'adm.restaurant.ordersTotal': 'ऑर्डर (कुल)',
  'adm.restaurant.rating': 'रेटिंग',
  'adm.restaurant.accepting': 'ऑर्डर ले रहे हैं',
  'adm.restaurant.customerLink': 'ग्राहक पेज खोलें',
  'adm.restaurant.dashboardLink': 'रेस्टोरेंट डैशबोर्ड खोलें',
  'adm.restaurant.documentsLead': 'सत्यापन की ज़रूरतें मार्केट के अनुसार तय होती हैं ({market})। हर दस्तावेज़ की जांच अलग से होती है; बैकएंड इन्हें बाद में जांचकर स्टोर करता है।',
  'adm.restaurant.docsComplete': '{total} ज़रूरी दस्तावेज़ों में से {approved} स्वीकृत',
  'adm.restaurant.notesEmpty': 'अभी तक कोई आंतरिक नोट नहीं।',
  'adm.restaurant.notesNote': 'आंतरिक नोट रेस्टोरेंट या ग्राहकों को कभी नहीं दिखाए जाते।',
  'adm.restaurant.locationsLead': '{org} की लोकेशन। किसी लोकेशन को निलंबित करने पर वह ग्राहकों के लिए बंद हो जाती है, संगठन पर कोई असर नहीं पड़ता।',
  'adm.restaurant.locStatus.ACTIVE': 'सक्रिय',
  'adm.restaurant.locStatus.SUSPENDED': 'निलंबित',
  'adm.restaurant.suspendLocation': 'लोकेशन निलंबित करें',
  'adm.restaurant.reactivateLocation': 'लोकेशन फिर से सक्रिय करें',
  'adm.restaurant.notFound': 'रेस्टोरेंट नहीं मिला',
  'adm.restaurant.approvalNeeded': 'यह रेस्टोरेंट प्लेटफ़ॉर्म की जांच के इंतज़ार में है।',
  'adm.doc.NOT_SUBMITTED': 'सबमिट नहीं किया गया',
  'adm.doc.SUBMITTED': 'सबमिट किया गया',
  'adm.doc.UNDER_REVIEW': 'जांच जारी',
  'adm.doc.APPROVED': 'स्वीकृत',
  'adm.doc.REJECTED': 'अस्वीकृत',
  'adm.doc.EXPIRED': 'समय-सीमा समाप्त',
  'adm.doc.expires': '{date} को समाप्त होगा',
  'adm.doc.submitted': '{date} को सबमिट किया गया',
  'adm.doc.setStatus': 'दस्तावेज़ की स्थिति सेट करें',
  'adm.doc.reviewTitle': 'दस्तावेज़ की जांच करें: {doc}',
  'adm.approve.title': '{name} को स्वीकृत करें?',
  'adm.approve.text': 'रेस्टोरेंट अपने मार्केट में ग्राहकों को दिखने लगेगा और पिकअप ऑर्डर ले सकेगा। इसके लिए अनिवार्य दस्तावेज़ों का स्वीकृत होना ज़रूरी है।',
  'adm.approve.blocked': 'स्वीकृति रोकी गई: {n} ज़रूरी दस्तावेज़ स्वीकृत नहीं हैं।',
  'adm.approve.override': 'फिर भी स्वीकृत करें (ऑडिट लॉग में दर्ज होगा)',
  'adm.reject.title': '{name} को अस्वीकृत करें',
  'adm.reject.text': 'एक श्रेणी चुनें, रेस्टोरेंट को दिखाया जाने वाला कारण लिखें और (चाहें तो) एक आंतरिक नोट जोड़ें।',
  'adm.reject.category': 'अस्वीकृति की श्रेणी',
  'adm.reject.public': 'रेस्टोरेंट को दिखाया जाने वाला कारण',
  'adm.reject.internal': 'आंतरिक नोट (रेस्टोरेंट को कभी नहीं दिखाया जाता)',
  'adm.reject.cat.incomplete_documents': 'अधूरे दस्तावेज़',
  'adm.reject.cat.invalid_business': 'व्यवसाय का विवरण अमान्य',
  'adm.reject.cat.duplicate': 'डुप्लिकेट लिस्टिंग',
  'adm.reject.cat.policy': 'नीति का उल्लंघन',
  'adm.reject.cat.other': 'अन्य',
  'adm.requestInfo.title': '{name} से जानकारी मांगें',
  'adm.requestInfo.text': 'संदेश रेस्टोरेंट को जाएगा; आवेदन की स्थिति "जांच जारी" हो जाएगी।',
  'adm.requestInfo.message': 'रेस्टोरेंट के लिए संदेश',
  'adm.suspend.title': '{name} को निलंबित करें?',
  'adm.suspend.text': 'निलंबन तुरंत और पूरे प्लेटफ़ॉर्म पर लागू होता है।',
  'adm.suspend.impact1': 'रेस्टोरेंट ग्राहकों की खोज से हट जाता है और ऑर्डर लेना बंद कर देता है।',
  'adm.suspend.impact2': 'जो ऑर्डर पहले से चल रहे हैं वे जारी रहेंगे और उन्हें पूरा या रद्द करना होगा।',
  'adm.suspend.impact3': 'रेस्टोरेंट स्टाफ़ डैशबोर्ड को केवल देख सकेगा; सेटलमेंट रोक दिए जाते हैं।',
  'adm.reactivate.title': '{name} को फिर से सक्रिय करें?',
  'adm.reactivate.text': 'रेस्टोरेंट ग्राहकों को फिर से दिखने लगेगा और ऑर्डर ले सकेगा।',
  'adm.customers.title': 'ग्राहक प्रबंधन',
  'adm.customers.lead': 'ग्राहक खाते, सहायता और सुरक्षा के लिए ज़रूरी न्यूनतम पहचान के साथ। ग्राहक के रूप में लॉगिन नहीं, बिना मास्क का संपर्क डेटा नहीं।',
  'adm.customers.search': 'नाम या संदर्भ से खोजें…',
  'adm.customers.col.customer': 'ग्राहक',
  'adm.customers.col.ref': 'संदर्भ',
  'adm.customers.col.phone': 'फ़ोन',
  'adm.customers.col.status': 'स्थिति',
  'adm.customers.col.orders': 'ऑर्डर',
  'adm.customers.col.market': 'मार्केट',
  'adm.customers.col.lastOrder': 'पिछला ऑर्डर',
  'adm.customers.col.joined': 'जुड़ने की तारीख',
  'adm.customers.empty': 'इन फ़िल्टर से कोई ग्राहक नहीं मिला।',
  'adm.customers.verified': 'सत्यापित',
  'adm.customers.unverified': 'असत्यापित',
  'adm.customers.reverify': 'दोबारा सत्यापन ज़रूरी',
  'adm.customerStatus.ACTIVE': 'सक्रिय',
  'adm.customerStatus.RESTRICTED': 'प्रतिबंधित',
  'adm.customerStatus.SUSPENDED': 'निलंबित',
  'adm.customerStatus.DEACTIVATED': 'निष्क्रिय किया गया',
  'adm.customer.title': 'ग्राहक',
  'adm.customer.identity': 'पहचान (न्यूनतम)',
  'adm.customer.recentOrders': 'हाल के ऑर्डर',
  'adm.customer.support': 'सहायता मामले',
  'adm.customer.reviews': 'समीक्षाएं',
  'adm.customer.security': 'सुरक्षा घटनाएं',
  'adm.customer.noOrders': 'डेवलपमेंट स्टोर में कोई ऑर्डर नहीं।',
  'adm.customer.noSupport': 'कोई सहायता मामला नहीं।',
  'adm.customer.noReviews': 'कोई समीक्षा नहीं।',
  'adm.customer.noSecurity': 'कोई सुरक्षा घटना नहीं।',
  'adm.customer.piiNote': 'संपर्क विवरण मास्क किए गए हैं; बैकएंड इन्हें केवल सहायता भूमिकाओं को दिखाता है, और कारण लॉग में दर्ज होता है।',
  'adm.customer.statusTitle': '{name} की स्थिति बदलकर {status} करें?',
  'adm.customer.statusText': 'ग्राहक को खाता नीति के अनुसार सूचना दी जाती है। प्रतिबंध से नए ऑर्डर रुक जाते हैं; निलंबन से ग्राहक हर जगह से साइन आउट भी हो जाता है।',
  'adm.customer.reverifyTitle': '{name} के लिए फ़ोन का दोबारा सत्यापन ज़रूरी करें?',
  'adm.customer.notFound': 'ग्राहक नहीं मिला',
  'adm.orders.title': 'ऑर्डर प्रबंधन',
  'adm.orders.lead': 'पूरे प्लेटफ़ॉर्म के ऑर्डर की निगरानी। एडमिन केवल देखते हैं और नोट जोड़ते हैं; स्थिति में बदलाव रेस्टोरेंट, ग्राहक और बैकएंड ही करते हैं।',
  'adm.orders.tabs': 'ऑर्डर के चरण',
  'adm.orders.tab.all': 'सभी',
  'adm.orders.tab.active': 'सक्रिय',
  'adm.orders.tab.preparing': 'तैयार हो रहा है',
  'adm.orders.tab.ready': 'तैयार',
  'adm.orders.tab.completed': 'पूरा हुआ',
  'adm.orders.tab.cancelled': 'रद्द',
  'adm.orders.tab.rejected': 'अस्वीकृत',
  'adm.orders.tab.exception': 'अपवाद',
  'adm.orders.search': 'ऑर्डर नंबर, रेस्टोरेंट या ग्राहक से खोजें…',
  'adm.orders.col.order': 'ऑर्डर #',
  'adm.orders.col.restaurant': 'रेस्टोरेंट',
  'adm.orders.col.customer': 'ग्राहक',
  'adm.orders.col.pickup': 'पिकअप का समय',
  'adm.orders.col.status': 'स्थिति',
  'adm.orders.col.payment': 'भुगतान',
  'adm.orders.col.total': 'कुल',
  'adm.orders.col.market': 'मार्केट',
  'adm.orders.empty': 'इस व्यू में कोई ऑर्डर नहीं।',
  'adm.orders.emptyException': 'कोई अपवाद नहीं मिला। ऑर्डर सामान्य रूप से चल रहे हैं।',
  'adm.order.title': 'ऑर्डर {n}',
  'adm.order.notFound': 'ऑर्डर नहीं मिला',
  'adm.order.timeline': 'टाइमलाइन',
  'adm.order.items': 'आइटम',
  'adm.order.payment': 'भुगतान',
  'adm.order.refunds': 'रिफ़ंड',
  'adm.order.support': 'सहायता मामले',
  'adm.order.notes': 'एडमिन नोट',
  'adm.order.notesEmpty': 'कोई एडमिन नोट नहीं।',
  'adm.order.exceptions': 'अपवाद',
  'adm.order.noExceptions': 'इस ऑर्डर के लिए कोई अपवाद नहीं।',
  'adm.order.pickupVerification': 'पिकअप सत्यापन',
  'adm.order.customer': 'ग्राहक',
  'adm.order.restaurant': 'रेस्टोरेंट',
  'adm.order.journey': 'यात्रा',
  'adm.order.overrideNote': 'फ़्रंटएंड में स्थिति ओवरराइड उपलब्ध नहीं है। असाधारण बदलाव बैकएंड से होते हैं, कारण और ऑडिट एंट्री के साथ।',
  'adm.order.noPayment': 'डेवलपमेंट स्टोर में भुगतान का कोई रिकॉर्ड नहीं।',
  'adm.order.noRefunds': 'कोई रिफ़ंड नहीं।',
  'adm.order.noSupport': 'कोई सहायता मामला नहीं।',
  'adm.order.openSupport': 'सहायता में खोलें',
  'adm.order.note': 'ऑर्डर नोट',
  'adm.exception.payment_without_confirmation': 'भुगतान हुआ, पुष्टि नहीं',
  'adm.exception.restaurant_no_response': 'रेस्टोरेंट से जवाब नहीं',
  'adm.exception.pickup_verification_issue': 'पिकअप सत्यापन में समस्या',
  'adm.exception.refund_overdue': 'रिफ़ंड में देरी',
  'adm.exception.status_mismatch': 'स्थिति मेल नहीं खाती',
  'adm.paymentStatus.PAYMENT_PENDING': 'लंबित',
  'adm.paymentStatus.PAID': 'भुगतान हो गया',
  'adm.paymentStatus.FAILED': 'विफल',
  'adm.paymentStatus.REFUND_PENDING': 'रिफ़ंड लंबित',
  'adm.paymentStatus.PARTIALLY_REFUNDED': 'आंशिक रिफ़ंड हुआ',
  'adm.paymentStatus.REFUNDED': 'रिफ़ंड हो गया',
  'adm.payments.title': 'भुगतान प्रबंधन',
  'adm.payments.lead': 'भुगतान के प्रयास और उनके प्रोवाइडर संदर्भ। कार्ड, UPI या वॉलेट का डेटा कभी नहीं दिखाया जाता।',
  'adm.payments.tabs': 'भुगतान और रिफ़ंड',
  'adm.payments.search': 'संदर्भ, ऑर्डर या रेस्टोरेंट से खोजें…',
  'adm.payments.col.reference': 'संदर्भ',
  'adm.payments.col.order': 'ऑर्डर',
  'adm.payments.col.restaurant': 'रेस्टोरेंट',
  'adm.payments.col.method': 'तरीका',
  'adm.payments.col.amount': 'राशि',
  'adm.payments.col.status': 'स्थिति',
  'adm.payments.col.date': 'तारीख',
  'adm.payments.col.provider': 'प्रोवाइडर',
  'adm.payments.empty': 'इन फ़िल्टर से कोई भुगतान नहीं मिला।',
  'adm.payments.kpi.successful': 'कैप्चर हुए (दिख रहे)',
  'adm.payments.kpi.failed': 'विफल',
  'adm.payments.kpi.mismatch': 'मिलान में अंतर',
  'adm.payments.kpi.refundPending': 'लंबित रिफ़ंड',
  'adm.payment.title': 'भुगतान {ref}',
  'adm.payment.events': 'इवेंट इतिहास',
  'adm.payment.reconciliation': 'मिलान (तैयारी)',
  'adm.payment.expected': 'अपेक्षित',
  'adm.payment.providerStatus': 'प्रोवाइडर की स्थिति',
  'adm.payment.platformStatus': 'प्लेटफ़ॉर्म की स्थिति',
  'adm.payment.mismatch': 'अंतर — मिलान ज़रूरी',
  'adm.payment.match': 'मेल खाता है',
  'adm.payment.providerRef': 'प्रोवाइडर संदर्भ',
  'adm.payment.customer': 'ग्राहक',
  'adm.payment.methodNote': 'केवल भुगतान के तरीके की श्रेणी। कार्ड नंबर, CVV, UPI PIN और वॉलेट पहचान कभी प्लेटफ़ॉर्म तक नहीं पहुंचते।',
  'adm.payment.method.card': 'कार्ड',
  'adm.payment.method.upi': 'UPI',
  'adm.payment.method.wallet': 'वॉलेट',
  'adm.payState.CREATED': 'बनाया गया',
  'adm.payState.PENDING': 'लंबित',
  'adm.payState.AUTHORIZED': 'अधिकृत',
  'adm.payState.CAPTURED': 'कैप्चर हुआ',
  'adm.payState.FAILED': 'विफल',
  'adm.payState.CANCELLED': 'रद्द',
  'adm.payState.REFUND_PENDING': 'रिफ़ंड लंबित',
  'adm.payState.PARTIALLY_REFUNDED': 'आंशिक रिफ़ंड हुआ',
  'adm.payState.REFUNDED': 'रिफ़ंड हो गया',
  'adm.refunds.title': 'रिफ़ंड प्रबंधन',
  'adm.refunds.lead': 'रिफ़ंड के अनुरोध और प्रोवाइडर से मिले नतीजे। रिफ़ंड जारी करना बैकएंड के नियंत्रण में है; यह व्यू केवल उन्हें ट्रैक करता है।',
  'adm.refunds.tabs': 'रिफ़ंड की स्थितियां',
  'adm.refunds.search': 'संदर्भ या ऑर्डर से खोजें…',
  'adm.refunds.col.reference': 'संदर्भ',
  'adm.refunds.col.order': 'ऑर्डर',
  'adm.refunds.col.restaurant': 'रेस्टोरेंट',
  'adm.refunds.col.requested': 'मांगी गई राशि',
  'adm.refunds.col.refunded': 'रिफ़ंड की गई राशि',
  'adm.refunds.col.kind': 'प्रकार',
  'adm.refunds.col.status': 'स्थिति',
  'adm.refunds.col.date': 'तारीख',
  'adm.refunds.col.reason': 'कारण',
  'adm.refunds.empty': 'इस व्यू में कोई रिफ़ंड नहीं।',
  'adm.refunds.kind.full': 'पूरा',
  'adm.refunds.kind.partial': 'आंशिक',
  'adm.refunds.issueNote': 'रिफ़ंड जारी करना (पूरा / आंशिक) बैकएंड का काम है, जिसमें प्रोवाइडर की पुष्टि और ऑडिट शामिल है; फ़्रंटएंड कभी पैसे का लेन-देन नहीं करता।',
  'adm.refundStatus.PENDING': 'लंबित',
  'adm.refundStatus.PROCESSING': 'प्रोसेस हो रहा है',
  'adm.refundStatus.PARTIAL': 'आंशिक',
  'adm.refundStatus.COMPLETED': 'पूरा हुआ',
  'adm.refundStatus.FAILED': 'विफल',
  'adm.settlements.title': 'सेटलमेंट',
  'adm.settlements.lead': 'हर अवधि और हर मुद्रा के अनुसार रेस्टोरेंट पेआउट। राशियां डेवलपमेंट फ़िक्स्चर हैं; सेटलमेंट इंजन एक बैकएंड मॉड्यूल है।',
  'adm.settlements.col.id': 'सेटलमेंट',
  'adm.settlements.col.restaurant': 'रेस्टोरेंट',
  'adm.settlements.col.period': 'अवधि',
  'adm.settlements.col.gross': 'सकल',
  'adm.settlements.col.refunds': 'रिफ़ंड',
  'adm.settlements.col.fees': 'शुल्क',
  'adm.settlements.col.adjustments': 'समायोजन',
  'adm.settlements.col.net': 'शुद्ध पेआउट',
  'adm.settlements.col.status': 'स्थिति',
  'adm.settlements.col.orders': 'ऑर्डर',
  'adm.settlements.empty': 'इन फ़िल्टर से कोई सेटलमेंट नहीं मिला।',
  'adm.settlements.totals': 'मुद्रा के अनुसार शुद्ध पेआउट',
  'adm.settlements.totalsNote': '{n} सेटलमेंट',
  'adm.settlementStatus.PENDING': 'लंबित',
  'adm.settlementStatus.PROCESSING': 'प्रोसेस हो रहा है',
  'adm.settlementStatus.PAID': 'भुगतान हो गया',
  'adm.settlementStatus.FAILED': 'विफल',
  'adm.settlementStatus.ON_HOLD': 'रोका गया',
  'adm.reviews.title': 'समीक्षा मॉडरेशन',
  'adm.reviews.lead': 'ग्राहकों की समीक्षाओं और रेस्टोरेंट के जवाबों को मॉडरेट करें। प्लेटफ़ॉर्म रेटिंग और टेक्स्ट को कभी संपादित नहीं करता।',
  'adm.reviews.tabs': 'मॉडरेशन कतारें',
  'adm.reviews.tab.all': 'सभी',
  'adm.reviews.tab.pending': 'लंबित',
  'adm.reviews.tab.flagged': 'फ़्लैग की गई',
  'adm.reviews.tab.published': 'प्रकाशित',
  'adm.reviews.tab.hidden': 'छिपाई गई',
  'adm.reviews.tab.rejected': 'अस्वीकृत',
  'adm.reviews.search': 'समीक्षाएं खोजें…',
  'adm.reviews.col.rating': 'रेटिंग',
  'adm.reviews.col.restaurant': 'रेस्टोरेंट',
  'adm.reviews.col.customer': 'ग्राहक',
  'adm.reviews.col.review': 'समीक्षा',
  'adm.reviews.col.reports': 'रिपोर्ट',
  'adm.reviews.col.status': 'स्थिति',
  'adm.reviews.col.date': 'तारीख',
  'adm.reviews.empty': 'इस कतार में कोई समीक्षा नहीं है।',
  'adm.reviews.reports': '{n} रिपोर्ट',
  'adm.reviews.response': 'रेस्टोरेंट का जवाब',
  'adm.reviews.hideResponse': 'जवाब छिपाएं',
  'adm.reviews.history': 'मॉडरेशन इतिहास',
  'adm.reviews.noHistory': 'अभी तक कोई मॉडरेशन कार्रवाई नहीं हुई।',
  'adm.reviews.reasons': 'रिपोर्ट के कारण',
  'adm.reviews.order': 'ऑर्डर',
  'adm.reviews.action.publish': 'प्रकाशित करें',
  'adm.reviews.action.hide': 'छिपाएं',
  'adm.reviews.action.reject': 'अस्वीकार करें',
  'adm.reviews.action.restore': 'बहाल करें',
  'adm.reviews.action.hide_response': 'जवाब छिपाएं',
  'adm.reviews.confirm.publish': 'यह समीक्षा प्रकाशित करें?',
  'adm.reviews.confirm.hide': 'यह समीक्षा छिपाएं?',
  'adm.reviews.confirm.reject': 'यह समीक्षा अस्वीकार करें?',
  'adm.reviews.confirm.restore': 'यह समीक्षा बहाल करें?',
  'adm.reviews.confirm.hide_response': 'रेस्टोरेंट का जवाब छिपाएं?',
  'adm.reviews.confirmText': 'फ़ैसला और कारण ऑडिट लॉग में दर्ज होते हैं। ग्राहक की रेटिंग और लिखी हुई बात बनी रहती है।',
  'adm.reviewStatus.SUBMITTED': 'सबमिट हुई',
  'adm.reviewStatus.PENDING_MODERATION': 'लंबित',
  'adm.reviewStatus.PUBLISHED': 'प्रकाशित',
  'adm.reviewStatus.HIDDEN': 'छिपी हुई',
  'adm.reviewStatus.REJECTED': 'अस्वीकृत',
  'adm.reviewStatus.FLAGGED': 'फ़्लैग की गई',
  'adm.promotions.title': 'प्रमोशन',
  'adm.promotions.lead': 'प्रोमो कोड और कैंपेन। पात्रता और छूट की गणना चेकआउट पर बैकएंड ही तय करता है।',
  'adm.promotions.new': 'नया प्रमोशन',
  'adm.promotions.edit': 'प्रमोशन संपादित करें',
  'adm.promotions.search': 'कोड या नाम से खोजें…',
  'adm.promotions.col.code': 'कोड',
  'adm.promotions.col.name': 'नाम',
  'adm.promotions.col.type': 'प्रकार',
  'adm.promotions.col.value': 'मूल्य',
  'adm.promotions.col.scope': 'दायरा',
  'adm.promotions.col.period': 'अवधि',
  'adm.promotions.col.usage': 'उपयोग',
  'adm.promotions.col.status': 'स्थिति',
  'adm.promotions.empty': 'इन फ़िल्टर से कोई प्रमोशन मेल नहीं खाता।',
  'adm.promotions.type.fixed': 'निश्चित राशि',
  'adm.promotions.type.percentage': 'प्रतिशत',
  'adm.promotions.scope.platform': 'प्लेटफ़ॉर्म',
  'adm.promotions.scope.market': 'मार्केट',
  'adm.promotions.scope.restaurant': 'रेस्टोरेंट',
  'adm.promotions.usage': '{used} / {limit}',
  'adm.promotions.unlimited': 'असीमित',
  'adm.promotions.f.code': 'कोड',
  'adm.promotions.f.name': 'नाम',
  'adm.promotions.f.description': 'विवरण',
  'adm.promotions.f.type': 'छूट का प्रकार',
  'adm.promotions.f.value': 'मूल्य',
  'adm.promotions.f.valuePct': 'प्रतिशत (1–100)',
  'adm.promotions.f.valueFixed': 'सबसे छोटी इकाई में राशि ({currency})',
  'adm.promotions.f.currency': 'मुद्रा',
  'adm.promotions.f.starts': 'शुरू',
  'adm.promotions.f.ends': 'समाप्त',
  'adm.promotions.f.minSpend': 'न्यूनतम खर्च (सबसे छोटी इकाई में)',
  'adm.promotions.f.maxDiscount': 'अधिकतम छूट (सबसे छोटी इकाई में)',
  'adm.promotions.f.usageLimit': 'उपयोग सीमा',
  'adm.promotions.f.perCustomer': 'प्रति ग्राहक सीमा',
  'adm.promotions.f.scope': 'दायरा',
  'adm.promotions.f.market': 'मार्केट',
  'adm.promotions.f.restaurant': 'रेस्टोरेंट',
  'adm.promotions.f.status': 'स्थिति',
  'adm.promotions.err.required': 'ज़रूरी',
  'adm.promotions.err.invalid': 'अमान्य मूल्य (कोड: 3–20 बड़े अक्षर, अंक, - या _; निश्चित राशि: धनात्मक पूर्ण संख्या)',
  'adm.promotions.err.range': 'सीमा से बाहर',
  'adm.promotions.err.dates': 'समाप्ति शुरुआत के बाद होनी चाहिए',
  'adm.promotions.err.currency': 'निश्चित राशि के लिए मुद्रा साफ़ तौर पर बतानी ज़रूरी है',
  'adm.promotions.statusTitle': '{code} को {status} करें?',
  'adm.promotions.pause': 'रोकें',
  'adm.promotions.resume': 'फिर शुरू करें',
  'adm.promotions.disable': 'अक्षम करें',
  'adm.promotions.activate': 'सक्रिय करें',
  'adm.promoStatus.DRAFT': 'ड्राफ़्ट',
  'adm.promoStatus.SCHEDULED': 'शेड्यूल्ड',
  'adm.promoStatus.ACTIVE': 'सक्रिय',
  'adm.promoStatus.PAUSED': 'रुका हुआ',
  'adm.promoStatus.EXPIRED': 'समाप्त',
  'adm.promoStatus.DISABLED': 'अक्षम',
  'adm.support.title': 'सहायता प्रबंधन',
  'adm.support.lead': 'ग्राहक, रेस्टोरेंट और सिस्टम के मामले — असाइनमेंट, प्राथमिकता और आंतरिक नोट के साथ।',
  'adm.support.tabs': 'मामलों की कतारें',
  'adm.support.tab.open': 'खुले',
  'adm.support.tab.in_progress': 'जारी',
  'adm.support.tab.waiting': 'प्रतीक्षा में',
  'adm.support.tab.resolved': 'हल हुए',
  'adm.support.tab.all': 'सभी',
  'adm.support.search': 'टिकट, अनुरोधकर्ता या सारांश से खोजें…',
  'adm.support.col.ticket': 'टिकट #',
  'adm.support.col.type': 'प्रकार',
  'adm.support.col.requester': 'अनुरोधकर्ता',
  'adm.support.col.priority': 'प्राथमिकता',
  'adm.support.col.status': 'स्थिति',
  'adm.support.col.assignee': 'असाइनी',
  'adm.support.col.updated': 'अपडेट हुआ',
  'adm.support.empty': 'इस कतार में कोई मामला नहीं है।',
  'adm.support.unassigned': 'असाइन नहीं',
  'adm.support.priority.all': 'सभी प्राथमिकताएं',
  'adm.support.assign': 'इन्हें असाइन करें',
  'adm.support.status': 'स्थिति',
  'adm.support.priority': 'प्राथमिकता',
  'adm.support.reply': 'जवाब',
  'adm.support.internalNote': 'आंतरिक नोट',
  'adm.support.internalHint': 'आंतरिक नोट ग्राहकों या रेस्टोरेंट को कभी नहीं दिखते।',
  'adm.support.messages': 'बातचीत',
  'adm.support.noMessages': 'अभी तक कोई संदेश नहीं।',
  'adm.support.send': 'जवाब भेजें',
  'adm.support.addNote': 'नोट जोड़ें',
  'adm.support.linked': 'जुड़े हुए',
  'adm.support.order': 'ऑर्डर',
  'adm.support.restaurant': 'रेस्टोरेंट',
  'adm.support.customer': 'ग्राहक',
  'adm.support.notFound': 'मामला नहीं मिला',
  'adm.support.internalBadge': 'आंतरिक',
  'adm.support.source.customer': 'ग्राहक',
  'adm.support.source.restaurant': 'रेस्टोरेंट',
  'adm.support.source.system': 'सिस्टम',
  'adm.support.source.admin': 'एडमिन',
  'adm.supportStatus.OPEN': 'खुला',
  'adm.supportStatus.IN_PROGRESS': 'जारी',
  'adm.supportStatus.WAITING_CUSTOMER': 'प्रतीक्षा में (ग्राहक)',
  'adm.supportStatus.WAITING_RESTAURANT': 'प्रतीक्षा में (रेस्टोरेंट)',
  'adm.supportStatus.RESOLVED': 'हल हुआ',
  'adm.supportStatus.CLOSED': 'बंद',
  'adm.priority.LOW': 'कम',
  'adm.priority.MEDIUM': 'मध्यम',
  'adm.priority.HIGH': 'उच्च',
  'adm.priority.URGENT': 'अत्यावश्यक',
  'adm.notifications.title': 'सूचनाएं',
  'adm.notifications.lead': 'गंभीर अलर्ट, प्लेटफ़ॉर्म की घोषणाएं और टेम्पलेट की तैयारी।',
  'adm.notifications.tabs': 'सूचना के हिस्से',
  'adm.notifications.tab.alerts': 'अलर्ट',
  'adm.notifications.tab.announcements': 'घोषणाएं',
  'adm.notifications.tab.templates': 'टेम्पलेट',
  'adm.notifications.tab.delivery': 'भेजे जाने की स्थिति',
  'adm.notifications.new': 'नई घोषणा',
  'adm.notifications.edit': 'घोषणा संपादित करें',
  'adm.notifications.col.title': 'शीर्षक',
  'adm.notifications.col.audience': 'प्राप्तकर्ता',
  'adm.notifications.col.markets': 'मार्केट',
  'adm.notifications.col.channel': 'चैनल',
  'adm.notifications.col.status': 'स्थिति',
  'adm.notifications.col.scheduled': 'शेड्यूल्ड',
  'adm.notifications.f.title': 'शीर्षक',
  'adm.notifications.f.audience': 'प्राप्तकर्ता',
  'adm.notifications.f.markets': 'मार्केट (खाली = सभी)',
  'adm.notifications.f.channel': 'चैनल',
  'adm.notifications.f.status': 'स्थिति',
  'adm.notifications.f.scheduledAt': 'भेजने का समय',
  'adm.notifications.audience.customers': 'ग्राहक',
  'adm.notifications.audience.restaurants': 'रेस्टोरेंट',
  'adm.notifications.audience.admins': 'एडमिन',
  'adm.notifications.channel.email': 'ई-मेल',
  'adm.notifications.channel.sms': 'SMS',
  'adm.notifications.channel.push': 'पुश',
  'adm.notifications.channel.in_app': 'इन-ऐप',
  'adm.notifications.annStatus.DRAFT': 'ड्राफ़्ट',
  'adm.notifications.annStatus.SCHEDULED': 'शेड्यूल्ड',
  'adm.notifications.annStatus.SENT': 'भेजी गई',
  'adm.notifications.allMarkets': 'सभी मार्केट',
  'adm.notifications.tplCol.key': 'टेम्पलेट',
  'adm.notifications.tplCol.channel': 'चैनल',
  'adm.notifications.tplCol.audience': 'प्राप्तकर्ता',
  'adm.notifications.tplCol.locales': 'लोकेल',
  'adm.notifications.tplCol.status': 'स्थिति',
  'adm.notifications.deliveryNote': 'भेजे जाने की ट्रैकिंग (हर चैनल पर भेजा गया / पहुंचा / विफल) बैकएंड और प्रोवाइडर की क्षमता है; यह व्यू सिर्फ़ तैयारी दिखाता है।',
  'adm.notifications.alertsEmpty': 'कोई अलर्ट नहीं।',
  'adm.notifications.sendNote': 'भेजना बैकएंड का काम है; यहां सेव की गई घोषणाएं ड्राफ़्ट हैं या बाद में भेजने के लिए शेड्यूल हैं।',
  'adm.markets.title': 'मार्केट',
  'adm.markets.lead': 'देश / मार्केट कॉन्फ़िगरेशन: ISO 3166-1 देश, ISO 4217 मुद्रा, लोकेल, टाइम ज़ोन, इकाइयां, भुगतान प्रोवाइडर और टैक्स संदर्भ। ऐप में कुछ भी हार्डकोड नहीं है।',
  'adm.markets.tabs': 'मार्केट कॉन्फ़िगरेशन',
  'adm.markets.tab.markets': 'मार्केट',
  'adm.markets.tab.taxes': 'टैक्स',
  'adm.markets.tab.fees': 'शुल्क और कमीशन',
  'adm.markets.col.market': 'मार्केट',
  'adm.markets.col.currency': 'मुद्रा',
  'adm.markets.col.locale': 'लोकेल',
  'adm.markets.col.timezone': 'टाइम ज़ोन',
  'adm.markets.col.units': 'इकाइयां',
  'adm.markets.col.providers': 'भुगतान प्रोवाइडर',
  'adm.markets.col.tax': 'टैक्स कॉन्फ़िगरेशन',
  'adm.markets.col.restaurants': 'रेस्टोरेंट',
  'adm.markets.col.status': 'स्थिति',
  'adm.markets.edit': 'मार्केट संपादित करें',
  'adm.markets.new': 'मार्केट जोड़ें',
  'adm.markets.f.code': 'देश कोड (ISO 3166-1 alpha-2)',
  'adm.markets.f.name': 'नाम',
  'adm.markets.f.currency': 'मुद्रा (ISO 4217)',
  'adm.markets.f.locale': 'डिफ़ॉल्ट लोकेल',
  'adm.markets.f.languages': 'भाषाएं (कॉमा से अलग करें)',
  'adm.markets.f.timezone': 'डिफ़ॉल्ट टाइम ज़ोन (IANA)',
  'adm.markets.f.units': 'इकाई प्रणाली',
  'adm.markets.f.providers': 'भुगतान प्रोवाइडर (कॉमा से अलग करें)',
  'adm.markets.f.status': 'स्थिति',
  'adm.markets.err': 'देश कोड 2 बड़े अक्षरों का और मुद्रा 3 बड़े अक्षरों की होनी चाहिए, टाइम ज़ोन ज़रूरी है।',
  'adm.markets.status.ACTIVE': 'सक्रिय',
  'adm.markets.status.PILOT': 'पायलट',
  'adm.markets.status.INACTIVE': 'निष्क्रिय',
  'adm.markets.units.metric': 'मीट्रिक',
  'adm.markets.units.imperial': 'इंपीरियल',
  'adm.markets.noProviders': 'कोई कॉन्फ़िगर नहीं',
  'adm.taxes.col.name': 'टैक्स',
  'adm.taxes.col.market': 'मार्केट',
  'adm.taxes.col.kind': 'किस्म',
  'adm.taxes.col.rate': 'दर',
  'adm.taxes.col.applies': 'किस पर लागू',
  'adm.taxes.col.effective': 'लागू होने की तारीख',
  'adm.taxes.col.status': 'स्थिति',
  'adm.taxes.providerRate': 'प्रोवाइडर द्वारा गणना',
  'adm.taxes.note': 'टैक्स की गणना बैकएंड / प्रोवाइडर की ज़िम्मेदारी है; ये संदर्भ हैं जिन्हें बैकएंड हर मार्केट के लिए तय करता है।',
  'adm.fees.col.name': 'शुल्क',
  'adm.fees.col.market': 'मार्केट',
  'adm.fees.col.kind': 'प्रकार',
  'adm.fees.col.model': 'मॉडल',
  'adm.fees.col.value': 'मान',
  'adm.fees.col.applies': 'किस पर लागू',
  'adm.fees.col.status': 'स्थिति',
  'adm.fees.kind.platform_fee': 'प्लेटफ़ॉर्म शुल्क',
  'adm.fees.kind.restaurant_commission': 'रेस्टोरेंट कमीशन',
  'adm.fees.kind.other': 'अन्य',
  'adm.fees.model.percentage': 'प्रतिशत',
  'adm.fees.model.fixed': 'निश्चित',
  'adm.fees.edit': 'शुल्क संपादित करें',
  'adm.fees.f.value': 'मान',
  'adm.fees.f.status': 'स्थिति',
  'adm.fees.err': 'निश्चित शुल्क के लिए मुद्रा और शून्य या उससे अधिक मान ज़रूरी है।',
  'adm.fees.allMarkets': 'सभी मार्केट',
  'adm.fees.note': 'शुल्क और कमीशन के ढांचे सिर्फ़ कॉन्फ़िगरेशन शेल हैं; बैकएंड इन्हें चेकआउट और सेटलमेंट के समय लागू करता है।',
  'adm.config.title': 'प्लेटफ़ॉर्म कॉन्फ़िगरेशन',
  'adm.config.lead': 'ऑर्डर, पिकअप, भुगतान और शुल्क की सेटिंग्स तथा फ़ीचर फ़्लैग। ये मान डेवलपमेंट शेल हैं; असली स्रोत बैकएंड है।',
  'adm.config.tabs': 'कॉन्फ़िगरेशन के हिस्से',
  'adm.config.tab.settings': 'सेटिंग्स',
  'adm.config.tab.flags': 'फ़ीचर फ़्लैग',
  'adm.config.col.key': 'सेटिंग',
  'adm.config.col.value': 'मान',
  'adm.config.col.description': 'विवरण',
  'adm.config.locked': 'लॉक है',
  'adm.config.editTitle': '{key} बदलें',
  'adm.config.newValue': 'नया मान',
  'adm.config.category.ordering': 'ऑर्डर',
  'adm.config.category.pickup': 'पिकअप',
  'adm.config.category.payments': 'भुगतान',
  'adm.config.category.fees': 'शुल्क',
  'adm.config.category.markets': 'मार्केट',
  'adm.config.category.notifications': 'सूचनाएं',
  'adm.config.category.restaurants': 'रेस्टोरेंट',
  'adm.config.flagTitle': '{key} को {state} करें?',
  'adm.config.flagOn': 'चालू',
  'adm.config.flagOff': 'बंद',
  'adm.config.flagNote': 'यहां दिखाए गए फ़ीचर फ़्लैग अंतिम नहीं हैं; बैकएंड हर अनुरोध पर फ़्लैग की जांच करता है।',
  'adm.config.scope.platform': 'प्लेटफ़ॉर्म',
  'adm.config.scope.market': 'मार्केट',
  'adm.users.title': 'एडमिन उपयोगकर्ता',
  'adm.users.lead': 'प्लेटफ़ॉर्म एडमिनिस्ट्रेटर, भूमिकाएं और अनुमतियां। आमंत्रण, MFA और सेशन बाद में बैकएंड द्वारा लागू किए जाएंगे।',
  'adm.users.leadLive': 'प्लेटफ़ॉर्म एडमिनिस्ट्रेटर, भूमिकाएं और अनुमतियां। आमंत्रण, भूमिकाएं, खाते की स्थिति और MFA रीसेट बैकएंड द्वारा लागू किए जाते हैं।',
  'adm.users.tabs': 'उपयोगकर्ता और भूमिकाएं',
  'adm.users.tab.users': 'उपयोगकर्ता',
  'adm.users.tab.roles': 'भूमिकाएं और अनुमतियां',
  'adm.users.col.user': 'उपयोगकर्ता',
  'adm.users.col.role': 'भूमिका',
  'adm.users.col.status': 'स्थिति',
  'adm.users.col.mfa': 'MFA',
  'adm.users.col.lastLogin': 'पिछला लॉगिन',
  'adm.users.col.created': 'बनाया गया',
  'adm.users.never': 'कभी नहीं',
  'adm.users.mfaOn': 'चालू है',
  'adm.users.mfaOff': 'चालू नहीं है',
  'adm.users.invite': 'एडमिन को आमंत्रित करें',
  'adm.users.f.name': 'नाम',
  'adm.users.f.email': 'काम का ई-मेल',
  'adm.users.f.role': 'भूमिका',
  'adm.users.err.invalid': 'नाम और सही ई-मेल डालें।',
  'adm.users.err.duplicate': 'इस ई-मेल वाला एडमिन पहले से मौजूद है।',
  'adm.users.changeRole': 'भूमिका बदलें',
  'adm.users.roleTitle': '{name} की भूमिका बदलें',
  'adm.users.statusTitle': '{name} को {status} पर सेट करें?',
  'adm.users.selfNote': 'आप अपने खुद के खाते को निलंबित नहीं कर सकते और न ही उसकी भूमिका घटा सकते हैं।',
  'adm.users.mfaNote': 'प्रोडक्शन में हर एडमिन के लिए MFA ज़रूरी है (आगे के लिए: एडमिन ऑथेंटिकेशन मॉड्यूल)।',
  'adm.users.permissions': 'अनुमतियां',
  'adm.users.roleDesc.super_admin': 'पूरा एक्सेस, जिसमें एडमिन उपयोगकर्ता, सुरक्षा और सेटिंग्स शामिल हैं।',
  'adm.users.roleDesc.operations_admin': 'रोज़मर्रा का संचालन: रेस्टोरेंट, ग्राहक, ऑर्डर, सहायता, निगरानी।',
  'adm.users.roleDesc.restaurant_onboarding': 'रेस्टोरेंट के आवेदनों और दस्तावेज़ों की जांच करता है।',
  'adm.users.roleDesc.support_admin': 'ग्राहकों और रेस्टोरेंट के सहायता मामले संभालता है।',
  'adm.users.roleDesc.finance_admin': 'भुगतान, रिफ़ंड और सेटलमेंट।',
  'adm.users.roleDesc.moderation_admin': 'समीक्षाओं और जवाबों का मॉडरेशन।',
  'adm.users.roleDesc.analyst': 'सिर्फ़ देखने के लिए एनालिटिक्स और रिपोर्टिंग।',
  'adm.audit.title': 'ऑडिट लॉग',
  'adm.audit.lead': 'एडमिन की कार्रवाइयों का न बदलने वाला रिकॉर्ड। एंट्री को फ़िल्टर करके देखा जा सकता है, लेकिन संपादित या हटाया कभी नहीं जा सकता।',
  'adm.audit.search': 'कर्ता, लक्ष्य या विवरण खोजें…',
  'adm.audit.col.time': 'समय',
  'adm.audit.col.actor': 'कर्ता',
  'adm.audit.col.action': 'कार्रवाई',
  'adm.audit.col.target': 'लक्ष्य',
  'adm.audit.col.result': 'नतीजा',
  'adm.audit.col.description': 'विवरण',
  'adm.audit.action.all': 'सभी कार्रवाइयां',
  'adm.audit.target.all': 'सभी लक्ष्य',
  'adm.audit.result.all': 'सभी नतीजे',
  'adm.audit.from': 'से',
  'adm.audit.to': 'तक',
  'adm.audit.empty': 'इन फ़िल्टर से कोई ऑडिट एंट्री मेल नहीं खाती।',
  'adm.audit.detail': 'ऑडिट एंट्री',
  'adm.audit.before': 'पहले',
  'adm.audit.after': 'बाद में',
  'adm.audit.reason': 'कारण',
  'adm.audit.ip': 'IP पता',
  'adm.audit.immutable': 'बदला नहीं जा सकता — ऑडिट एंट्री बैकएंड लिखता है; यहां कुछ भी बदला नहीं जा सकता।',
  'adm.audit.none': '—',
  'adm.auditResult.SUCCESS': 'सफल',
  'adm.auditResult.DENIED': 'अस्वीकार',
  'adm.auditResult.FAILED': 'विफल',
  'adm.security.title': 'सुरक्षा',
  'adm.security.lead': 'एडमिन ऑथेंटिकेशन, ऑथराइज़ेशन और संवेदनशील कार्रवाइयों के संकेत। पहचान और रोकथाम बैकएंड में होती है।',
  'adm.security.kpi.failedLogins': 'विफल एडमिन लॉगिन (24 घंटे)',
  'adm.security.kpi.suspicious': 'संदिग्ध गतिविधि',
  'adm.security.kpi.locked': 'लॉक किए गए खाते',
  'adm.security.kpi.highRisk': 'ज़्यादा जोखिम वाली कार्रवाइयां (24 घंटे)',
  'adm.security.kpi.permChanges': 'अनुमति में बदलाव',
  'adm.security.kpi.mfa': 'MFA कवरेज',
  'adm.security.alerts': 'सक्रिय अलर्ट',
  'adm.security.events': 'सुरक्षा इवेंट',
  'adm.security.col.time': 'समय',
  'adm.security.col.kind': 'प्रकार',
  'adm.security.col.severity': 'गंभीरता',
  'adm.security.col.actor': 'कर्ता',
  'adm.security.col.detail': 'विवरण',
  'adm.security.col.ip': 'IP',
  'adm.security.noAlerts': 'कोई सक्रिय अलर्ट नहीं।',
  'adm.security.kind.auth_failure': 'ऑथेंटिकेशन विफल',
  'adm.security.kind.authz_denied': 'अनुमति नहीं मिली',
  'adm.security.kind.rate_limit': 'रेट लिमिट',
  'adm.security.kind.permission_change': 'अनुमति में बदलाव',
  'adm.security.kind.sensitive_action': 'संवेदनशील कार्रवाई',
  'adm.security.kind.lockout': 'लॉकआउट',
  'adm.alertSeverity.info': 'जानकारी',
  'adm.alertSeverity.warning': 'चेतावनी',
  'adm.alertSeverity.critical': 'गंभीर',
  'adm.security.sev.low': 'कम',
  'adm.security.sev.medium': 'मध्यम',
  'adm.security.sev.high': 'ज़्यादा',
  'adm.security.mfaNote': '{total} सक्रिय एडमिन में से {enrolled} में MFA चालू है',
  'adm.analytics.title': 'प्लेटफ़ॉर्म एनालिटिक्स',
  'adm.analytics.lead': 'पूरे प्लेटफ़ॉर्म का प्रदर्शन। GMV आय नहीं है; रकम हर मुद्रा के लिए अलग दिखाई जाती है और अलग-अलग मुद्राओं को कभी जोड़ा नहीं जाता।',
  'adm.analytics.range': 'तारीख की सीमा',
  'adm.analytics.market': 'मार्केट',
  'adm.analytics.kpi.orders': 'ऑर्डर',
  'adm.analytics.kpi.activeRestaurants': 'सक्रिय रेस्टोरेंट',
  'adm.analytics.kpi.activeCustomers': 'सक्रिय ग्राहक',
  'adm.analytics.kpi.refundRate': 'रिफ़ंड दर',
  'adm.analytics.kpi.prep': 'औसत तैयारी समय',
  'adm.analytics.kpi.rating': 'औसत रेटिंग',
  'adm.analytics.kpi.conversion': 'चेकआउट कन्वर्ज़न',
  'adm.analytics.kpi.onTime': 'समय पर पिकअप',
  'adm.analytics.ordersTrend': 'ऑर्डर का रुझान',
  'adm.analytics.byMarket': 'मार्केट के अनुसार ऑर्डर',
  'adm.analytics.byCurrency': 'मुद्रा के अनुसार GMV, प्लेटफ़ॉर्म आय और रिफ़ंड',
  'adm.analytics.col.currency': 'मुद्रा',
  'adm.analytics.col.orders': 'ऑर्डर',
  'adm.analytics.col.gmv': 'GMV',
  'adm.analytics.col.revenue': 'प्लेटफ़ॉर्म आय',
  'adm.analytics.col.refunds': 'रिफ़ंड',
  'adm.analytics.ratings': 'रेटिंग का वितरण',
  'adm.analytics.top': 'शीर्ष रेस्टोरेंट',
  'adm.analytics.col.restaurant': 'रेस्टोरेंट',
  'adm.analytics.col.rating': 'रेटिंग',
  'adm.analytics.exportNote': 'एक्सपोर्ट (CSV) बाद में बैकएंड की रिपोर्टिंग सेवा द्वारा तैयार किए जाएंगे।',
  'adm.analytics.from': 'से',
  'adm.analytics.to': 'तक',
  'adm.analytics.empty': 'इस चयन के लिए कोई डेटा नहीं है।',
  'adm.system.title': 'सिस्टम की स्थिति',
  'adm.system.lead': 'प्लेटफ़ॉर्म की सेवाओं और प्रोवाइडर, क्यू और वेबहुक की सेहत। यह तैयारी दिखाने वाला व्यू डेवलपमेंट फ़िक्स्चर पर आधारित है।',
  'adm.system.services': 'सेवाएं',
  'adm.system.queues': 'क्यू',
  'adm.system.webhooks': 'वेबहुक',
  'adm.system.maps': 'मैप और रूटिंग',
  'adm.system.col.service': 'सेवा',
  'adm.system.col.kind': 'प्रकार',
  'adm.system.col.state': 'स्थिति',
  'adm.system.col.latency': 'लेटेंसी',
  'adm.system.col.note': 'नोट',
  'adm.system.col.checked': 'जांच का समय',
  'adm.system.kind.internal': 'आंतरिक',
  'adm.system.kind.provider': 'प्रोवाइडर',
  'adm.system.q.name': 'क्यू',
  'adm.system.q.pending': 'लंबित',
  'adm.system.q.failed': 'विफल',
  'adm.system.q.oldest': 'सबसे पुराना जॉब',
  'adm.system.q.workers': 'वर्कर',
  'adm.system.w.provider': 'प्रोवाइडर',
  'adm.system.w.event': 'इवेंट',
  'adm.system.w.received': 'प्राप्त',
  'adm.system.w.processed': 'प्रोसेस हुए',
  'adm.system.w.failed': 'विफल',
  'adm.system.w.retrying': 'फिर से कोशिश जारी',
  'adm.system.w.last': 'पिछला',
  'adm.system.maps.requests': 'अनुरोध (24 घंटे)',
  'adm.system.maps.failures': 'विफलताएं (24 घंटे)',
  'adm.system.overall': 'कुल मिलाकर',
  'adm.system.seconds': '{n} सेकंड',
  'adm.system.ms': '{n} ms',
  'adm.settings.title': 'एडमिन सेटिंग्स',
  'adm.settings.lead': 'प्लेटफ़ॉर्म की सामान्य सेटिंग्स, ब्रांड, सहायता संपर्क, कानूनी दस्तावेज़ों के संस्करण, सुरक्षा और इंटीग्रेशन।',
  'adm.settings.general': 'सामान्य',
  'adm.settings.platformName': 'प्लेटफ़ॉर्म का नाम',
  'adm.settings.defaultLocale': 'डिफ़ॉल्ट लोकेल',
  'adm.settings.brand': 'ब्रांड',
  'adm.settings.brandNote': 'ब्रांड एसेट डिज़ाइन सिस्टम (public/brand) में संभाले जाते हैं; अपलोड बाद के मॉड्यूल में आएगा।',
  'adm.settings.support': 'सहायता संपर्क',
  'adm.settings.supportEmail': 'सहायता ई-मेल',
  'adm.settings.supportPhone': 'सहायता फ़ोन',
  'adm.settings.legal': 'कानूनी दस्तावेज़',
  'adm.settings.legalNote': 'सारा कानूनी टेक्स्ट ड्राफ़्ट है / अंतिम स्वीकृति लंबित है। संस्करणों का रिकॉर्ड रखा जाता है; प्रकाशन बैकएंड का वर्कफ़्लो है।',
  'adm.settings.legal.terms': 'सेवा की शर्तें',
  'adm.settings.legal.privacy': 'गोपनीयता नीति',
  'adm.settings.legal.refund': 'रिफ़ंड नीति',
  'adm.settings.legal.cookie': 'कुकी नीति',
  'adm.settings.version': 'संस्करण {v}',
  'adm.settings.pendingApproval': 'ड्राफ़्ट · अंतिम स्वीकृति लंबित',
  'adm.settings.security': 'सुरक्षा',
  'adm.settings.mfa': 'सभी एडमिन के लिए MFA ज़रूरी करें',
  'adm.settings.sessionTimeout': 'एडमिन सेशन टाइमआउट (मिनट)',
  'adm.settings.ipAllowlist': 'IP अलाउलिस्ट (तैयारी)',
  'adm.settings.integrations': 'इंटीग्रेशन',
  'adm.settings.integrationsNote': 'प्रोवाइडर के क्रेडेंशियल कभी भी फ़्रंटएंड में सेव नहीं किए जाते। यहां सिर्फ़ कॉन्फ़िगरेशन की स्थिति दिखती है।',
  'adm.settings.int.payments': 'भुगतान प्रोवाइडर',
  'adm.settings.int.maps': 'मैप और रूटिंग',
  'adm.settings.int.notifications': 'सूचनाएं',
  'adm.settings.int.sms': 'SMS',
  'adm.settings.int.sandbox': 'सैंडबॉक्स',
  'adm.settings.int.notConfigured': 'कॉन्फ़िगर नहीं है',
  'adm.settings.int.configured': 'कॉन्फ़िगर है (बैकएंड)',
  'adm.settings.saved': 'सेटिंग्स सेव हो गईं (डेवलपमेंट स्टोर)।',
  'adm.market.label': 'मार्केट',
  'adm.market.selector': 'मार्केट संदर्भ: {market}',
  'adm.market.allMarkets': 'सभी मार्केट',
  'adm.market.allNote': '{n} लॉन्च हो चुके मार्केट',
  'adm.market.future': 'भविष्य के मार्केट',
  'adm.market.comingLater': 'बाद में आएगा',
  'adm.marketStatus.ACTIVE': 'सक्रिय',
  'adm.marketStatus.PILOT': 'पायलट',
  'adm.marketStatus.DRAFT': 'ड्राफ़्ट',
  'adm.marketStatus.PAUSED': 'रोका गया',
  'adm.marketStatus.CLOSED': 'बंद',
  'adm.marketStatus.AVAILABLE': 'उपलब्ध',
  'adm.marketStatus.PLANNED': 'नियोजित',
  'adm.marketStatus.DISABLED': 'अक्षम',
  'adm.marketStatus.UNAVAILABLE': 'अनुपलब्ध',
  'adm.marketStatus.TESTING': 'टेस्टिंग',
  'adm.mkt.title': 'मार्केट कंट्रोल सेंटर',
  'adm.mkt.lead': '{market} सक्रिय मार्केट है। FoodOnTheGo कहां उपलब्ध है, यह यहां से संभालें: राज्य, शहर, सेवा क्षेत्र और रूट कॉरिडोर।',
  'adm.mkt.manage': '{market} संभालें',
  'adm.mkt.open': '{market} मार्केट खोलें',
  'adm.mkt.registry': 'टैक्स और शुल्क',
  'adm.mkt.kpi.activeMarkets': 'सक्रिय मार्केट',
  'adm.mkt.kpi.activeCities': 'सक्रिय शहर',
  'adm.mkt.kpi.serviceAreas': 'सेवा क्षेत्र',
  'adm.mkt.kpi.restaurants': 'सक्रिय रेस्टोरेंट',
  'adm.mkt.kpi.ordersToday': 'आज के ऑर्डर',
  'adm.mkt.kpi.customers': 'ग्राहक',
  'adm.mkt.kpi.gmv': 'कुल ऑर्डर मूल्य ({currency})',
  'adm.mkt.kpi.pending': 'लंबित लोकेशन स्वीकृतियां',
  'adm.mkt.kpi.routes': 'सक्रिय रूट कॉरिडोर',
  'adm.mkt.f.country': 'देश',
  'adm.mkt.f.code': 'देश कोड',
  'adm.mkt.f.currency': 'मुद्रा',
  'adm.mkt.f.locale': 'लोकेल',
  'adm.mkt.f.timezone': 'टाइम ज़ोन',
  'adm.mkt.f.units': 'दूरी',
  'adm.mkt.f.phone': 'ग्राहक फ़ोन डिफ़ॉल्ट',
  'adm.mkt.f.serviceAreas': 'सेवा क्षेत्र (लाइव / सभी)',
  'adm.mkt.f.restaurants': 'रेस्टोरेंट',
  'adm.mkt.f.orders': 'ऑर्डर',
  'adm.mkt.units.metric': 'किलोमीटर (मीट्रिक)',
  'adm.mkt.units.imperial': 'मील (इंपीरियल)',
  'adm.mkt.coverage': 'कवरेज मैप',
  'adm.mkt.coverageSub': '{market} के शहर, सेवा क्षेत्र और रूट कॉरिडोर',
  'adm.mkt.attention': 'ध्यान देने की ज़रूरत',
  'adm.mkt.future': 'भविष्य के मार्केट',
  'adm.mkt.futureSub': 'आर्किटेक्चर में तैयार हैं, पर लॉन्च नहीं हुए। ग्राहक इन मार्केट को न देख सकते हैं, न इस्तेमाल कर सकते हैं।',
  'adm.mkt.empty.future': 'भविष्य का कोई मार्केट कॉन्फ़िगर नहीं है।',
  'adm.sec.event.OTP_REQUESTED': 'कोड मांगा गया',
  'adm.sec.event.OTP_FAILED': 'गलत कोड',
  'adm.sec.event.OTP_VERIFIED': 'कोड सत्यापित',
  'adm.sec.event.LOGIN_SUCCESS': 'साइन इन किया',
  'adm.sec.event.LOGIN_FAILED': 'साइन इन विफल',
  'adm.sec.event.LOGOUT': 'साइन आउट किया',
  'adm.sec.event.SESSION_REVOKED': 'सेशन रद्द किया गया',
  'adm.sec.event.PASSWORD_RESET_REQUESTED': 'पासवर्ड रीसेट मांगा गया',
  'adm.sec.event.PASSWORD_CHANGED': 'पासवर्ड बदला गया',
  'adm.sec.event.ACCOUNT_STATUS_CHANGED': 'खाते की स्थिति बदली गई',
  'adm.sec.event.PERMISSION_CHANGED': 'अनुमति बदली गई',
  'adm.sec.event.MFA_CHALLENGE_FAILED': 'गलत MFA कोड',
  'adm.sec.event.MFA_ENABLED': 'MFA चालू किया गया',
  'adm.sec.event.MFA_DISABLED': 'MFA बंद किया गया',
  'adm.sec.event.all': 'सभी इवेंट',
  'adm.sec.lead': 'बैकएंड द्वारा दर्ज किए गए साइन इन, वन-टाइम कोड, MFA, सेशन, पासवर्ड और अनुमति के बदलाव। सिर्फ़ देखने के लिए।',
  'adm.sec.col.event': 'इवेंट',
  'adm.sec.col.account': 'खाता',
  'adm.sec.kpi.failedSignIns': 'विफल साइन इन, सभी खाते (24 घंटे)',
  'adm.sec.kpi.failedCodes': 'गलत कोड (24 घंटे)',
  'adm.sec.kpi.blocked': 'ब्लॉक किए गए खाते',
  'adm.sec.kpi.permChanges': 'अनुमति में बदलाव (7 दिन)',
  'adm.sec.noAlerts': 'पिछले एक घंटे में किसी भी पते से 5 या उससे ज़्यादा विफल कोशिशें नहीं हुईं।',
  'adm.sec.alert.repeated': '{ip} से पिछले {minutes} मिनट में {failures} विफल कोशिशें',
  'adm.sec.accounts': 'खाते',
  'adm.sec.blocked.admin': 'निलंबित / अक्षम एडमिनिस्ट्रेटर',
  'adm.sec.blocked.restaurant': 'निलंबित / अक्षम रेस्टोरेंट उपयोगकर्ता',
  'adm.sec.blocked.customer': 'निलंबित ग्राहक',
  'adm.sec.statusChanges': 'खाते की स्थिति में बदलाव (7 दिन)',
  'adm.sec.accountType.all': 'सभी खाता प्रकार',
  'adm.sec.accountType.admin_user': 'एडमिनिस्ट्रेटर',
  'adm.sec.accountType.restaurant_user': 'रेस्टोरेंट उपयोगकर्ता',
  'adm.sec.accountType.customer': 'ग्राहक',
  'adm.sec.account.unknown': 'किसी खाते से जुड़ा नहीं है',
  'adm.sec.account.removed': 'खाता अब मौजूद नहीं है',
  'adm.sec.failedOnly': 'सिर्फ़ विफल',
  'adm.sec.empty': 'इन फ़िल्टर से कोई सुरक्षा इवेंट मेल नहीं खाता।',
  'adm.sec.detail': 'सुरक्षा इवेंट',
  'adm.sec.device': 'डिवाइस / ब्राउज़र',
  'adm.sec.note': 'बैकएंड द्वारा दर्ज किया जाता है और एप्लिकेशन इसे कभी संपादित या हटाता नहीं है। किसी इवेंट में कभी कोड, पासवर्ड, टोकन, फ़ोन नंबर या ई-मेल नहीं होता; अनजान कॉलर को सिर्फ़ हैश के रूप में सेव किया जाता है, जो दिखाया नहीं जाता।',
  'adm.users.invited': 'आमंत्रण भेज दिया गया। जब तक व्यक्ति पासवर्ड सेट नहीं करता, खाता निष्क्रिय रहेगा।',
  'adm.users.resend': 'आमंत्रण फिर से भेजें',
  'adm.users.f.locale': 'ई-मेल की भाषा',
  'adm.users.locale.all': 'एक ही संदेश में सभी भाषाएं',
  'adm.users.localeHint': 'आमंत्रण इसी भाषा में लिखा जाता है। व्यक्ति इसे बाद में खाता सुरक्षा में बदल सकता है।',
  'adm.users.search': 'नाम या ई-मेल खोजें…',
  'adm.users.status.all': 'सभी स्थितियां',
  'adm.users.empty': 'इस खोज से कोई एडमिनिस्ट्रेटर मेल नहीं खाता।',
  'adm.users.f.scope': 'इन पर लागू',
  'adm.users.scope.all': 'सभी मार्केट (पूरे प्लेटफ़ॉर्म पर)',
  'adm.users.scopeHint': 'एक मार्केट तक सीमित भूमिका सिर्फ़ उसी मार्केट के डेटा पर काम करती है। इससे पूरे प्लेटफ़ॉर्म की स्क्रीन नहीं खुलतीं: एडमिनिस्ट्रेटर खाते, भूमिकाएं और सुरक्षा।',
  'adm.users.disable': 'अक्षम करें',
  'adm.users.disableWarn': 'अक्षम करना स्थायी है: {name} हर जगह से साइन आउट हो जाएंगे और खाता फिर कभी सक्रिय नहीं किया जा सकेगा। बाद में एक्सेस वापस देने के लिए नया आमंत्रण भेजना होगा। अगर यह अस्थायी हो सकता है, तो निलंबित करें का इस्तेमाल करें।',
  'adm.users.disabled': '{name} अक्षम हैं।',
  'adm.users.resetMfa': 'MFA रीसेट करें',
  'adm.users.resetMfaTitle': '{name} के लिए मल्टी-फ़ैक्टर ऑथेंटिकेशन रीसेट करें?',
  'adm.users.resetMfaWarn': 'यह तभी करें जब आपने इस स्क्रीन के बाहर पुष्टि कर ली हो कि अनुरोध सच में {name} की ओर से है। उनका ऑथेंटिकेटर ऐप और रिकवरी कोड काम करना बंद कर देंगे और वे हर डिवाइस से साइन आउट हो जाएंगे। जब तक वे MFA फिर से सेट नहीं करते, खाता सिर्फ़ पासवर्ड से सुरक्षित रहेगा। {name} को रीसेट की जानकारी ई-मेल से दी जाती है।',
  'adm.users.resetMfaDone': '{name} के लिए MFA रीसेट कर दिया गया। वे हर जगह से साइन आउट हो गए हैं और उन्हें इसे फिर से सेट करना होगा।',
  'adm.users.resent': '{name} को नया आमंत्रण लिंक भेज दिया गया। पुराने लिंक अब काम नहीं करेंगे।',
  'adm.users.noRole': 'कोई भूमिका नहीं',
  'adm.users.inviteNote': 'व्यक्ति को अपना पासवर्ड खुद चुनने के लिए एक बार इस्तेमाल होने वाला लिंक मिलता है (72 घंटे तक मान्य)। आप कभी पासवर्ड नहीं देखते और न ही सेट करते हैं। इस लोकल सेटअप पर कोई ई-मेल नहीं भेजा जाता: संदेश सिर्फ़ सर्वर लॉग में लिखा जाता है।',
  'adm.users.liveNote': 'खाते और भूमिकाएं बैकएंड में सेव होती हैं। आप यहां अपनी खुद की स्थिति या भूमिका नहीं बदल सकते और न ही अपना MFA रीसेट कर सकते हैं, आप ऐसी भूमिका नहीं दे सकते जिसकी अनुमतियां आपके पास नहीं हैं, और आखिरी पूर्ण एडमिनिस्ट्रेटर को हटाया नहीं जा सकता। हर बदलाव ऑडिट में दर्ज होता है।',
  'adm.audit.src.label': 'ऑडिट स्रोत',
  'adm.audit.src.backend': 'बैकएंड ऑडिट ट्रेल',
  'adm.audit.src.dev': 'डेवलपमेंट लॉग (मॉक हिस्से)',
  'adm.audit.searchBackend': 'कार्रवाई या कारण खोजें…',
  'adm.audit.requestId': 'रिक्वेस्ट ID',
  'adm.audit.backendNote': 'बदलाव होने पर बैकएंड इसे लिखता है, और एप्लिकेशन इसे कभी संपादित या हटाता नहीं है। फ़िलहाल इसमें मार्केट, राज्य, शहर, सेवा क्षेत्र, रूट कॉरिडोर, फ़ीचर और कॉन्फ़िगरेशन शामिल हैं। अस्वीकार की गई कोशिशें यहां दर्ज नहीं होतीं।',
  'adm.audit.devNote': 'डेवलपमेंट लॉग, जिसे एडमिन के वे हिस्से इस ब्राउज़र में रखते हैं जिनका अभी बैकएंड नहीं है (रेस्टोरेंट, रिफ़ंड, उपयोगकर्ता …)। यह असली ऑडिट ट्रेल नहीं है।',
  'adm.geo.addRegion': 'राज्य / क्षेत्र जोड़ें',
  'adm.geo.createRegion': 'बनाएं',
  'adm.geo.regionCreated': 'नियोजित के रूप में बनाया गया',
  'adm.geo.editRegion': '{name} संपादित करें',
  'adm.geo.f.regionCode': 'कोड',
  'adm.geo.f.regionCodeHint': 'ISO 3166-2 शैली, बड़े अक्षर, अंक और हाइफ़न, जैसे IN-UP',
  'adm.geo.f.regionName': 'नाम',
  'adm.geo.f.regionType': 'प्रकार',
  'adm.geo.codeFixed': 'कोड बदला नहीं जा सकता।',
  'adm.geo.type.STATE': 'राज्य',
  'adm.geo.type.UNION_TERRITORY': 'केंद्र शासित प्रदेश',
  'adm.geo.type.PROVINCE': 'प्रांत',
  'adm.geo.type.REGION': 'क्षेत्र',
  'adm.geo.err.code': '2 से 12 बड़े अक्षरों, अंकों या हाइफ़न का कोड डालें।',
  'adm.geo.addRoute': 'रूट कॉरिडोर जोड़ें',
  'adm.geo.createRoute': 'कॉरिडोर बनाएं',
  'adm.geo.routeCreated': 'रूट कॉरिडोर नियोजित के रूप में बनाया गया',
  'adm.geo.f.routeName': 'कॉरिडोर का नाम',
  'adm.geo.f.highway': 'हाईवे',
  'adm.geo.f.highwayHint': 'जैसे NH44 (वैकल्पिक)',
  'adm.geo.f.origin': 'कहां से (शहर)',
  'adm.geo.f.destination': 'कहां तक (शहर)',
  'adm.geo.f.via': 'बीच के शहर, यात्रा के क्रम में',
  'adm.geo.f.viaHint': 'उन शहरों पर टिक करें जिनसे कॉरिडोर गुज़रता है; वे दोनों सिरों के बीच अपनी जगह के हिसाब से क्रम में लगते हैं।',
  'adm.geo.f.width': 'कॉरिडोर की चौड़ाई (m)',
  'adm.geo.f.widthHint': 'सेंटरलाइन के दोनों ओर की दूरी, 100 से 100000 m',
  'adm.geo.citiesFixed': 'कॉरिडोर बनने के बाद उसके शहर बदले नहीं जा सकते।',
  'adm.geo.centreline': 'सेंटरलाइन',
  'adm.geo.replaceCentreline': 'सेव की गई सेंटरलाइन बदलें',
  'adm.geo.line.cities': 'शहरों से होकर सीधी रेखाएं',
  'adm.geo.line.geojson': 'GeoJSON पेस्ट करें',
  'adm.geo.f.lineGeojson': 'GeoJSON LineString',
  'adm.geo.f.lineGeojsonHint': 'सड़क के साथ चलने वाली LineString (या ऐसा Feature जिसमें वह हो)। पोज़िशन [देशांतर, अक्षांश] के रूप में होती हैं, WGS84।',
  'adm.geo.centrelineNote': 'शहर के केंद्रों के बीच की सीधी रेखाएं सिर्फ़ अस्थायी विकल्प हैं: सड़क की असली ज्योमेट्री उपलब्ध होने पर उसे पेस्ट करें। बैकएंड सेव करने से पहले रेखा की जांच करता है।',
  'adm.geo.linePreview': '{points} बिंदु',
  'adm.geo.err.origin': 'कॉरिडोर के दोनों सिरे चुनें।',
  'adm.geo.err.sameCity': 'दोनों सिरे अलग-अलग शहर होने चाहिए।',
  'adm.geo.err.width': 'चौड़ाई 100 और 100000 के बीच की पूर्ण संख्या होनी चाहिए।',
  'adm.geo.err.line': 'दोनों सिरे चुनें, या पेस्ट किए गए GeoJSON पर जाएं।',
  'adm.geo.err.lineGeojson': 'यह कम से कम दो पोज़िशन वाली GeoJSON LineString नहीं है।',
  'adm.geo.editConfig': 'कॉन्फ़िगरेशन संपादित करें',
  'adm.geo.configTitle': 'मार्केट कॉन्फ़िगरेशन संपादित करें',
  'adm.geo.cfg.payments': 'भुगतान के तरीके',
  'adm.geo.cfg.paymentsHint': 'सिर्फ़ उपलब्धता। प्रोवाइडर की कुंजियां यहां कभी नहीं डाली जातीं।',
  'adm.geo.cfg.status.PLANNED': 'नियोजित',
  'adm.geo.cfg.status.ENABLED': 'चालू',
  'adm.geo.cfg.status.NOT_APPROVED': 'स्वीकृत नहीं',
  'adm.geo.cfg.locked': 'इस मार्केट के लिए लॉक है — चालू नहीं किया जा सकता',
  'adm.geo.cfg.tax': 'टैक्स',
  'adm.geo.cfg.taxRegime': 'टैक्स व्यवस्था',
  'adm.geo.cfg.taxStatus': 'टैक्स सेटअप',
  'adm.geo.cfg.tax.PENDING': 'लंबित',
  'adm.geo.cfg.tax.CONFIGURED': 'कॉन्फ़िगर है',
  'adm.geo.cfg.taxHint': 'यहां कोई टैक्स दर नहीं डाली जाती; दरें प्राइसिंग मॉड्यूल के साथ आएंगी।',
  'adm.geo.cfg.address': 'पते का फ़ॉर्मैट',
  'adm.geo.cfg.postalLabel': 'पिन कोड का लेबल',
  'adm.geo.cfg.postalPattern': 'पिन कोड का पैटर्न',
  'adm.geo.cfg.postalPatternHint': 'रेगुलर एक्सप्रेशन, जैसे ^[1-9][0-9]{5}$',
  'adm.geo.cfg.adminArea': 'राज्य / क्षेत्र का लेबल',
  'adm.geo.cfg.reason': 'बदलाव का कारण',
  'adm.geo.cfg.reasonHint': 'ऑडिट ट्रेल में दर्ज किया जाता है।',
  'adm.geo.err.reason': 'कारण डालें (कम से कम 3 अक्षर)।',
  'adm.geo.err.pattern': 'यह मान्य रेगुलर एक्सप्रेशन नहीं है।',
  'adm.geo.err.label': 'लेबल डालें।',
  'adm.geo.addCity': 'शहर जोड़ें',
  'adm.geo.editCity': '{name} संपादित करें',
  'adm.geo.createCity': 'शहर बनाएं',
  'adm.geo.cityCreated': 'शहर नियोजित के रूप में बनाया गया',
  'adm.geo.addArea': 'सेवा क्षेत्र जोड़ें',
  'adm.geo.editArea': '{name} संपादित करें',
  'adm.geo.createArea': 'सेवा क्षेत्र बनाएं',
  'adm.geo.areaCreated': 'सेवा क्षेत्र नियोजित के रूप में बनाया गया',
  'adm.geo.edit': 'संपादित करें',
  'adm.geo.saveChanges': 'बदलाव सेव करें',
  'adm.geo.choose': 'चुनें…',
  'adm.geo.newIsPlanned': 'नए रिकॉर्ड नियोजित स्थिति से शुरू होते हैं और ग्राहकों को नहीं दिखते। बाद में टेबल में दिए स्थिति कंट्रोल से उन्हें खोलें।',
  'adm.geo.checkFields': 'कृपया हाइलाइट किए गए फ़ील्ड जांचें।',
  'adm.geo.f.cityName': 'शहर का नाम',
  'adm.geo.f.areaName': 'सेवा क्षेत्र का नाम',
  'adm.geo.f.lat': 'अक्षांश (शहर का केंद्र)',
  'adm.geo.f.latHint': 'दशमलव डिग्री, जैसे 28.5355',
  'adm.geo.f.lng': 'देशांतर (शहर का केंद्र)',
  'adm.geo.f.lngHint': 'दशमलव डिग्री, जैसे 77.3910',
  'adm.geo.f.timezone': 'टाइम ज़ोन',
  'adm.geo.f.timezoneHint': 'IANA नाम, जैसे Asia/Kolkata',
  'adm.geo.f.aliases': 'अन्य नाम',
  'adm.geo.f.aliasesHint': 'कॉमा से अलग करें, जैसे Gurgaon',
  'adm.geo.f.launchStage': 'लॉन्च नोट (आंतरिक)',
  'adm.geo.f.launchStageHint': 'ग्राहकों को कभी नहीं दिखता',
  'adm.geo.f.priority': 'प्राथमिकता',
  'adm.geo.f.priorityHint': 'जहां क्षेत्र एक-दूसरे पर आते हैं, वहां बड़ी संख्या वाला लागू होता है',
  'adm.geo.f.centreLat': 'केंद्र का अक्षांश',
  'adm.geo.f.centreLng': 'केंद्र का देशांतर',
  'adm.geo.f.radius': 'दायरा (km)',
  'adm.geo.f.radiusHint': '0.2 से 100 km',
  'adm.geo.f.geojson': 'GeoJSON',
  'adm.geo.f.geojsonHint': 'Polygon या MultiPolygon (या ऐसा Feature जिसमें इनमें से एक हो)। पोज़िशन [देशांतर, अक्षांश] के क्रम में, WGS84।',
  'adm.geo.regionFixed': 'शहर को किसी दूसरे राज्य में नहीं ले जाया जा सकता।',
  'adm.geo.cityFixed': 'सेवा क्षेत्र को किसी दूसरे शहर में नहीं ले जाया जा सकता।',
  'adm.geo.boundary': 'सीमा',
  'adm.geo.replaceBoundary': 'सेव की गई सीमा बदलें',
  'adm.geo.boundaryMode': 'सीमा कैसे दर्ज करें',
  'adm.geo.mode.circle': 'गोला (केंद्र + दायरा)',
  'adm.geo.mode.geojson': 'GeoJSON पेस्ट करें',
  'adm.geo.useCityCentre': 'शहर का केंद्र इस्तेमाल करें',
  'adm.geo.boundaryNote': 'बैकएंड सीमा को सेव करने से पहले जांचता है (मान्य पॉलीगॉन, मार्केट के अंदर)। अभी बनाने के लिए कोई नक्शा नहीं है — प्रीव्यू सिर्फ़ आकार दिखाता है।',
  'adm.geo.previewAria': 'सीमा की रूपरेखा, {points} बिंदु',
  'adm.geo.previewCaption': '{points} बिंदु · पश्चिम {w}, दक्षिण {s}, पूर्व {e}, उत्तर {n}',
  'adm.geo.err.name': 'नाम दर्ज करें (कम से कम 2 अक्षर)।',
  'adm.geo.err.region': 'राज्य / केंद्र शासित प्रदेश चुनें।',
  'adm.geo.err.city': 'शहर चुनें।',
  'adm.geo.err.lat': 'अक्षांश -90 और 90 के बीच की संख्या होनी चाहिए।',
  'adm.geo.err.lng': 'देशांतर -180 और 180 के बीच की संख्या होनी चाहिए।',
  'adm.geo.err.timezone': 'टाइम ज़ोन दर्ज करें।',
  'adm.geo.err.priority': 'प्राथमिकता -1000 और 1000 के बीच की पूर्ण संख्या होनी चाहिए।',
  'adm.geo.err.circle': 'केंद्र और 0.2 से 100 km के बीच का दायरा दर्ज करें।',
  'adm.geo.err.geojson': 'यह GeoJSON Polygon या MultiPolygon नहीं है।',
  'adm.mkt.apiNote': 'मार्केट, राज्य, शहर, सेवा क्षेत्र और रूट कॉरिडोर लोकल बैकएंड (PostgreSQL + PostGIS) से पढ़े जाते हैं; बदलाव वहीं सेव होते हैं और ऑडिट किए जाते हैं। रेस्टोरेंट पिन, ऑर्डर की गिनती और आय अभी भी डेवलपमेंट फ़िक्स्चर हैं। कवरेज नक्शा सांकेतिक है, बेसमैप नहीं।',
  'adm.mkt.devNote': 'डेवलपमेंट फ़िक्स्चर: सूची में किसी शहर या रूट के होने का मतलब यह नहीं कि FoodOnTheGo वहां काम करता है। मार्केट, भूगोल और उपलब्धता बाद में बैकएंड (PostgreSQL + PostGIS) संभालेगा।',
  'adm.mkt.loading.market': 'मार्केट लोड हो रहा है…',
  'adm.mkt.error.market': 'मार्केट उपलब्ध नहीं है',
  'adm.mkt.error.config': 'इस मार्केट के लिए कॉन्फ़िगरेशन उपलब्ध नहीं है।',
  'adm.mkt.notFound': 'मार्केट नहीं मिला',
  'adm.mkt.draftTitle': '{market} भविष्य का मार्केट है',
  'adm.mkt.draftText': 'अभी कोई भूगोल या कॉन्फ़िगरेशन मौजूद नहीं है। कॉन्फ़िगर और लॉन्च होने तक यह ग्राहकों को नहीं दिखता।',
  'adm.mkt.subnav': '{market} मार्केट के सेक्शन',
  'adm.mkt.tab.overview': 'ओवरव्यू',
  'adm.mkt.tab.states': 'राज्य और केंद्र शासित प्रदेश',
  'adm.mkt.tab.cities': 'शहर',
  'adm.mkt.tab.serviceAreas': 'सेवा क्षेत्र',
  'adm.mkt.tab.routes': 'रूट कॉरिडोर',
  'adm.mkt.tab.configuration': 'कॉन्फ़िगरेशन',
  'adm.mkt.tab.features': 'फ़ीचर',
  'adm.mkt.pause': 'मार्केट रोकें',
  'adm.mkt.resume': 'मार्केट फिर से शुरू करें',
  'adm.mkt.pauseTitle': '{market} मार्केट रोकें?',
  'adm.mkt.resumeTitle': '{market} मार्केट फिर से शुरू करें?',
  'adm.mkt.highImpact': 'यह बड़े असर वाला बदलाव है। कारण ज़रूरी है और बदलाव ऑडिट लॉग में दर्ज होता है।',
  'adm.mkt.pauseImpact1': '{n} रेस्टोरेंट ग्राहक ऐप से तुरंत हट जाएंगे।',
  'adm.mkt.pauseImpact2': 'ग्राहकों को दिखेगा “FoodOnTheGo अभी इस जगह उपलब्ध नहीं है।”',
  'adm.mkt.pauseImpact3': 'पहले से चल रहे ऑर्डर जारी रहेंगे।',
  'adm.mkt.cityList': 'नक्शे पर शहर',
  'adm.mkt.nRestaurants': '{n} रेस्टोरेंट',
  'adm.mkt.selected': '{city}: {areas} सेवा क्षेत्र, {restaurants} स्वीकृत रेस्टोरेंट। नक्शे पर हाइलाइट किया गया है।',
  'adm.mkt.map.layers': 'नक्शे की लेयर',
  'adm.mkt.map.layer.cities': 'शहर',
  'adm.mkt.map.layer.areas': 'सेवा क्षेत्र',
  'adm.mkt.map.layer.routes': 'रूट',
  'adm.mkt.map.layer.restaurants': 'रेस्टोरेंट',
  'adm.mkt.map.view': 'नक्शे का दायरा',
  'adm.mkt.map.view.served': 'सेवा वाला क्षेत्र',
  'adm.mkt.map.view.all': 'पूरा मार्केट',
  'adm.mkt.map.aria': '{market} का सांकेतिक कवरेज नक्शा: {cities} लाइव शहर, {areas} लाइव सेवा क्षेत्र, {routes} सक्रिय रूट कॉरिडोर। यही डेटा तालिकाओं में भी दिया गया है।',
  'adm.mkt.map.legend': 'नक्शे के संकेत',
  'adm.mkt.map.lg.active': 'सक्रिय शहर (गोला)',
  'adm.mkt.map.lg.pilot': 'पायलट शहर (हीरा)',
  'adm.mkt.map.lg.paused': 'रोका गया शहर (त्रिकोण)',
  'adm.mkt.map.lg.planned': 'नियोजित / अनुपलब्ध (खोखला)',
  'adm.mkt.map.lg.route': 'रूट कॉरिडोर (डैश वाली रेखा = सक्रिय नहीं)',
  'adm.mkt.map.lg.restaurant': 'रेस्टोरेंट (चौकोर)',
  'adm.mkt.map.note': 'डेवलपमेंट फ़िक्स्चर का सांकेतिक चित्र — यह भौगोलिक बेसमैप नहीं है और लाइव कवरेज भी नहीं। मैप प्रोवाइडर इंटीग्रेशन लंबित है।',
  'adm.mkt.col.state': 'राज्य / केंद्र शासित प्रदेश',
  'adm.mkt.col.code': 'कोड',
  'adm.mkt.col.status': 'स्थिति',
  'adm.mkt.col.activeCities': 'लाइव शहर',
  'adm.mkt.col.serviceAreas': 'सेवा क्षेत्र',
  'adm.mkt.col.restaurants': 'रेस्टोरेंट',
  'adm.mkt.col.city': 'शहर',
  'adm.mkt.col.orders': 'ऑर्डर',
  'adm.mkt.col.launch': 'लॉन्च चरण',
  'adm.mkt.col.area': 'क्षेत्र',
  'adm.mkt.col.routes': 'रूट कवरेज',
  'adm.mkt.col.geometry': 'सीमा',
  'adm.mkt.col.updated': 'अपडेट किया गया',
  'adm.mkt.col.route': 'रूट / कॉरिडोर',
  'adm.mkt.col.region': 'क्षेत्र',
  'adm.mkt.kind.state': 'राज्य',
  'adm.mkt.kind.union_territory': 'केंद्र शासित प्रदेश',
  'adm.mkt.kind.region': 'क्षेत्र',
  'adm.mkt.via': '{cities} होकर',
  'adm.mkt.geometry.radius': 'दायरा {km} km',
  'adm.mkt.geometry.polygon': 'पॉलीगॉन',
  'adm.mkt.statesSub': 'इस सूची में किसी राज्य के होने का मतलब यह नहीं कि पूरे राज्य में सेवा है — यह शहर और सेवा क्षेत्र तय करते हैं।',
  'adm.mkt.statesNote': 'किसी राज्य को अक्षम करने या उसका लॉन्च वापस लेने पर उसके शहरों के सभी रेस्टोरेंट ग्राहकों से छिप जाते हैं।',
  'adm.mkt.citiesSub': 'सक्रिय शहर का मतलब पूरा कवरेज नहीं है: ऑर्डर कहां हो सकता है, यह सेवा क्षेत्र और रूट कॉरिडोर तय करते हैं।',
  'adm.mkt.citiesNote': 'ग्राहकों के लिए सिर्फ़ सक्रिय और पायलट शहर उपलब्ध हैं। किसी शहर को रोकने पर वहां ग्राहकों के नए ऑर्डर बंद हो जाते हैं।',
  'adm.mkt.areasSub': 'वे क्षेत्र जहां रूट के आधार पर रेस्टोरेंट खोजना और ऑर्डर करना उपलब्ध है।',
  'adm.mkt.areasNote': 'सीमाएं अभी दायरे वाले फ़िक्स्चर हैं। पॉलीगॉन / मल्टीपॉलीगॉन / कॉरिडोर ज्योमेट्री PostGIS (SRID 4326) के साथ आएगी।',
  'adm.mkt.routesSub': 'शहरों के बीच के वे कॉरिडोर जिन्हें FoodOnTheGo कवर करता है। उदाहरण डेवलपमेंट फ़िक्स्चर हैं, प्रोडक्ट का दायरा नहीं।',
  'adm.mkt.routesNote': 'कॉरिडोर ज्योमेट्री और रेस्टोरेंट मैचिंग बैकएंड के रूटिंग प्रोवाइडर और PostGIS में जाएंगे।',
  'adm.mkt.search.states': 'राज्य खोजें…',
  'adm.mkt.search.cities': 'शहर खोजें…',
  'adm.mkt.search.areas': 'सेवा क्षेत्र खोजें…',
  'adm.mkt.search.routes': 'रूट खोजें…',
  'adm.mkt.empty.states': 'कोई राज्य मेल नहीं खाता।',
  'adm.mkt.empty.cities': 'कोई शहर मेल नहीं खाता। फ़िल्टर हटाएं या बाद में बैकएंड में शहर जोड़ें।',
  'adm.mkt.empty.areas': 'कोई सेवा क्षेत्र मेल नहीं खाता।',
  'adm.mkt.empty.routes': 'इस फ़िल्टर के लिए कोई रूट कॉन्फ़िगर नहीं है।',
  'adm.mkt.changeStatus': '{name} की स्थिति बदलें',
  'adm.mkt.statusTitle': '{name} को {status} पर सेट करें?',
  'adm.mkt.impact.state': '{cities} लाइव शहर और {restaurants} रेस्टोरेंट प्रभावित होंगे।',
  'adm.mkt.impact.city': '{restaurants} स्वीकृत रेस्टोरेंट ग्राहकों के लिए अनुपलब्ध हो जाएंगे।',
  'adm.mkt.impact.orders': 'यहां ग्राहकों के नए ऑर्डर बंद हो जाएंगे; चल रहे ऑर्डर जारी रहेंगे।',
  'adm.mkt.cfg.regional': 'क्षेत्रीय',
  'adm.mkt.cfg.payments': 'भुगतान',
  'adm.mkt.cfg.tax': 'टैक्स',
  'adm.mkt.cfg.legal': 'कानूनी',
  'adm.mkt.cfg.currency': 'मुद्रा',
  'adm.mkt.cfg.currencySub': 'ऑर्डर की मुद्रा मार्केट और रेस्टोरेंट लोकेशन से तय होती है। ग्राहक और रेस्टोरेंट स्टाफ़ इसे नहीं बदल सकते।',
  'adm.mkt.cfg.currencyNote': 'असली ऑर्डर आ जाने के बाद मार्केट की मुद्रा बदलना एक प्रतिबंधित बैकएंड कार्रवाई है; यहां इसके लिए कोई विकल्प नहीं है।',
  'adm.mkt.cfg.sample': 'फ़ॉर्मैट का नमूना',
  'adm.mkt.cfg.locale': 'लोकेल',
  'adm.mkt.cfg.localeSub': 'तारीख, समय और संख्याएं लोकेल फ़ॉर्मैटर से दिखाई जाती हैं।',
  'adm.mkt.cfg.primaryLocale': 'मुख्य लोकेल',
  'adm.mkt.cfg.dateSample': 'तारीख का नमूना',
  'adm.mkt.cfg.timeSample': 'समय का नमूना',
  'adm.mkt.cfg.plannedLocales': 'नियोजित लोकेल (आर्किटेक्चर तैयार, अनुवाद नहीं हुआ)',
  'adm.mkt.cfg.timezone': 'टाइम ज़ोन',
  'adm.mkt.cfg.timezoneSub': 'सिर्फ़ IANA टाइम ज़ोन ID; हर रेस्टोरेंट लोकेशन फिर भी अपना ज़ोन खुद रखती है।',
  'adm.mkt.cfg.strategy': 'रणनीति',
  'adm.mkt.cfg.strategy.single': 'पूरे मार्केट का एक ज़ोन',
  'adm.mkt.cfg.strategy.per-location': 'हर लोकेशन के अनुसार',
  'adm.mkt.cfg.units': 'इकाइयां और फ़ोन',
  'adm.mkt.cfg.phoneNote': 'इनपुट डिफ़ॉल्ट; नंबर अंतरराष्ट्रीय E.164 फ़ॉर्मैट में सेव होते हैं',
  'adm.mkt.cfg.address': 'पते का फ़ॉर्मैट',
  'adm.mkt.cfg.addressSub': 'लचीला अंतरराष्ट्रीय मॉडल; मार्केट के अनुसार जांच बाद में आएगी।',
  'adm.mkt.cfg.postal': 'पिन कोड',
  'adm.mkt.cfg.adminArea': 'क्षेत्र का लेबल',
  'adm.mkt.cfg.method': 'तरीका',
  'adm.mkt.cfg.note': 'नोट',
  'adm.mkt.cfg.providers': 'संभावित प्रोवाइडर',
  'adm.mkt.cfg.paymentsNote': 'असल तरीके हर ऑर्डर के लिए भुगतान प्रोवाइडर / बैकएंड से मिलते हैं। कुछ भी अपने आप चालू नहीं होता।',
  'adm.mkt.cfg.pendingBackend': 'बैकएंड लंबित',
  'adm.mkt.cfg.taxNote': 'ग्राहक चेकआउट में टैक्स की लाइनें तभी दिखती हैं जब बैकएंड उन्हें भेजता है।',
  'adm.mkt.pay.upi': 'UPI',
  'adm.mkt.pay.card': 'कार्ड',
  'adm.mkt.pay.netbanking': 'नेट बैंकिंग',
  'adm.mkt.pay.wallet': 'वॉलेट',
  'adm.mkt.pay.cash_at_pickup': 'पिकअप पर नकद',
  'adm.mkt.payStatus.ENABLED': 'चालू (सैंडबॉक्स)',
  'adm.mkt.payStatus.PLANNED': 'नियोजित',
  'adm.mkt.payStatus.NOT_APPROVED': 'स्वीकृत नहीं',
  'adm.mkt.featuresSub': '{market} के लिए फ़ीचर कॉन्फ़िगरेशन। शहर और सेवा क्षेत्र के ओवरराइड मॉडल में समर्थित हैं और बैकएंड के साथ आएंगे।',
  'adm.mkt.feature.journey_ordering': 'यात्रा के दौरान ऑर्डर',
  'adm.mkt.feature.journey_ordering.desc': 'तय किए गए रूट पर ऑर्डर करें।',
  'adm.mkt.feature.scheduled_pickup': 'शेड्यूल्ड पिकअप',
  'adm.mkt.feature.scheduled_pickup.desc': 'पिकअप का समय पहले से चुनें।',
  'adm.mkt.feature.asap_pickup': 'जल्द से जल्द (ASAP) पिकअप',
  'adm.mkt.feature.asap_pickup.desc': 'ऑर्डर तैयार होते ही पिकअप।',
  'adm.mkt.feature.reviews': 'समीक्षाएं',
  'adm.mkt.feature.reviews.desc': 'ग्राहक पूरे हुए ऑर्डर की समीक्षा कर सकते हैं।',
  'adm.mkt.feature.promotions': 'प्रमोशन',
  'adm.mkt.feature.promotions.desc': 'चेकआउट पर प्रोमो कोड।',
  'adm.mkt.feature.curbside_pickup': 'कर्बसाइड पिकअप',
  'adm.mkt.feature.curbside_pickup.desc': 'रेस्टोरेंट गाड़ी तक ऑर्डर पहुंचाने की सुविधा दे सकते हैं।',
  'adm.mkt.feature.restaurant_responses': 'रेस्टोरेंट के जवाब',
  'adm.mkt.feature.restaurant_responses.desc': 'रेस्टोरेंट समीक्षाओं का जवाब दे सकते हैं।',
  'adm.mkt.feature.customer_notifications': 'ग्राहक सूचनाएं',
  'adm.mkt.feature.customer_notifications.desc': 'ऑर्डर की स्थिति की सूचनाएं।',
  'adm.mkt.feature.cross_border_ordering': 'सीमा पार ऑर्डर',
  'adm.mkt.feature.cross_border_ordering.desc': 'ऐसी यात्राएं जो देश की सीमा पार करती हैं।',
  'adm.mkt.feature.cash_at_pickup': 'पिकअप पर नकद',
  'adm.mkt.feature.cash_at_pickup.desc': 'रेस्टोरेंट पर नकद भुगतान करें।',
  'adm.mkt.registryTitle': 'टैक्स, शुल्क और मार्केट रजिस्ट्री',
  'adm.mkt.registryStatusNote': 'मार्केट की स्थिति मार्केट कंट्रोल सेंटर में बदली जाती है।',
  'adm.pickupStatus.NOT_READY': 'तैयार नहीं',
  'adm.pickupStatus.READY': 'पिकअप के लिए तैयार',
  'adm.pickupStatus.VERIFICATION_AVAILABLE': 'सत्यापन उपलब्ध',
  'adm.pickupStatus.VERIFIED': 'सत्यापित',
  'adm.pickupStatus.ALREADY_USED': 'पहले ही इस्तेमाल हो चुका',
  'adm.pickupStatus.INVALID': 'अमान्य',
  'adm.pickupStatus.EXPIRED': 'समय-सीमा समाप्त',
  'adm.help.title': 'मदद',
  'adm.help.lead': 'एडमिन वर्कफ़्लो, RBAC और बैकएंड क्या लागू करेगा।',
  'adm.help.rbac': 'भूमिकाएं और अनुमतियां',
  'adm.help.rbacText': 'अनुमतियां इस डैशबोर्ड में कार्रवाइयों को छिपाती या अक्षम करती हैं। बैकएंड हर कार्रवाई को दोबारा जांचता है; बटन छिपाना कभी भी अनुमति देना नहीं है।',
  'adm.help.audit': 'ऑडिट',
  'adm.help.auditText': 'प्लेटफ़ॉर्म की स्थिति बदलने वाली हर कार्रवाई के लिए कारण ज़रूरी है और वह ऑडिट लॉग में दिखती है। एंट्री बदली नहीं जा सकतीं।',
  'adm.help.money': 'पैसा',
  'adm.help.moneyText': 'सभी रकम पूर्णांक छोटी इकाइयों में होती हैं और मुद्रा साफ़ बताई जाती है। GMV आय नहीं है। अलग-अलग मुद्राओं के कुल कभी नहीं जोड़े जाते।',
  'adm.help.mock': 'डेवलपमेंट डेटा',
  'adm.help.mockText': 'यह बिल्ड तय मॉक फ़िक्स्चर पर चलता है (LOCAL / MOCK DATA बैज)। ब्राउज़र स्टोरेज रीसेट करने पर फ़िक्स्चर वापस आ जाते हैं।',
  'adm.help.shortcuts': 'ग्लोबल खोज',
  'adm.help.shortcutsText': 'हेडर से रेस्टोरेंट, ऑर्डर, ग्राहक, भुगतान और सहायता केस खोजें। नतीजे आपकी अनुमतियों के अनुसार दिखते हैं।',
}
